### Imports

In [1]:
import json
import numpy as np
import pandas as pd
import pingouin as pg
import seaborn as sn

print(pg.__version__) # 0.5.3
print(pd.__version__) # 2.0.3
print(np.__version__) # 1.24.3
print(sn.__version__) # 0.13.0

from utils_MS import *

# %load_ext autotime

0.5.3
2.2.2
1.26.4
0.13.2

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.6.1.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
# def run(exp):

### Parameters

In [3]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"]

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

data_variations = params["data_variations"]
print("Data variations:", data_variations)

has_transformation = params["has_transformation"]
print("Has transformation:", has_transformation)

threshold_corr = params["threshold_corr"]
print("Threshold corr:\t", threshold_corr)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

groups_id_no = params["groups_id_no"]
print("Groups id (no):\t", groups_id_no)

Exp:		 exp9
Data variations: ['none']
Has transformation: True
Threshold corr:	 0.5
Groups id:	 ['AR', 'CRS', 'OSA', 'LPRD', 'SGB', 'LSNB', 'RCC', 'BC', 'BPH', 'PCa', 'PD']
Subgroups id:	 {'AR': ['1', '2'], 'CRS': ['1', '2'], 'OSA': ['1', '2'], 'LPRD': ['1', '2'], 'SGB': ['1', '2'], 'LSNB': ['1', '2'], 'RCC': ['1', '2'], 'BC': ['1', '2'], 'BPH': ['1', '2'], 'PCa': ['1', '2'], 'PD': ['1', '2']}
Groups id (no):	 ['Blank', 'QC', 'Std']

In [4]:
# Remove
# groups_id = ["OSA"]

### Load dataset

In [5]:
# read raw data
df_join_raw = pd.read_csv("experiments/input/{}_raw.csv".format(exp), index_col=0)
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,...,PD_2.43,PD_2.44,PD_2.45,PD_2.46,PD_2.47,PD_2.48,PD_2.49,PD_2.50,PD_2.51,PD_2.52
0,1.0,69.99951,Unknown,3.761221,0.006085,0.013273,3.028000e-02,0.039917,0.050244,0.061226,...,0.080008,2.152889,1.877989,3.006645,0.097180,0.083553,3.686441,0.084316,0.090964,0.083807
1,1.0,70.04025,Unknown,330.900909,3.345932,7.288550,1.660211e+01,21.875132,27.522388,33.526282,...,98.324448,113.265571,220.143630,114.840334,217.630894,111.705774,157.403484,115.633361,154.460280,112.483808
2,1.0,70.04151,Unknown,3.810500,0.323930,0.609772,1.190270e+00,1.489259,1.794746,2.106842,...,3.315511,3.413731,3.824988,3.421265,3.817551,3.406194,3.631237,3.428796,3.623766,66.207625
3,1.0,70.04908,Unknown,371.967656,0.779912,1.640943,3.603099e+00,4.689464,5.839993,7.051657,...,23.200059,4.981860,352.301595,5.012925,152.542561,4.950816,312.257226,5.028466,5.371851,4.966335
4,1.0,70.06267,Unknown,14.383827,0.705709,1.341339,1.985815e+00,2.645173,3.320973,4.013620,...,13.346583,14.103080,691.069505,587.099070,16.853497,14.034201,15.417710,977.423380,15.382943,14.068638
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1.0,732.79951,Unknown,163.972145,0.257934,0.408042,6.627189e-01,0.779649,17223.650862,0.892598,...,1.267927,1.498143,2.841460,1.518527,2.825464,1.477947,2.080693,1.528791,2.042619,1.488022
5440,1.0,748.76437,Unknown,5.318578,0.037040,0.088541,2.224989e-01,0.302977,0.391783,0.488620,...,1.576491,1.885946,3.803859,1.913544,3.757898,1.858634,2.703381,1.927451,2.650225,1.872254
5441,1.0,794.79590,Unknown,44.795976,0.062477,0.158303,4.230803e-01,0.588121,0.773688,0.979274,...,2.081027,2.412741,4.164254,2.447782,4.113120,2.378048,421.344464,2.465433,3.246804,2.395351
5442,1.0,800.81295,Unknown,32.469955,0.091943,0.246783,7.009899e-01,0.994539,1.330769,1.709164,...,5.679157,6.495188,10.681201,40.563104,10.573695,6.418109,8.392011,6.572858,8.300825,6.456575
5443,1.0,860.74167,Unknown,87.571560,0.016108,0.035769,1.076772e+06,0.083146,0.110302,0.139565,...,0.447106,0.522984,0.976927,0.529973,0.966075,0.516059,0.722467,0.533492,0.709443,0.519513

In [6]:
# get metadata
df_join_raw_metadata = df_join_raw.iloc[:, :2]
df_join_raw_metadata

      Average Rt  Average Mz
0            1.0    69.99951
1            1.0    70.04025
2            1.0    70.04151
3            1.0    70.04908
4            1.0    70.06267
...          ...         ...
5439         1.0   732.79951
5440         1.0   748.76437
5441         1.0   794.79590
5442         1.0   800.81295
5443         1.0   860.74167

[5444 rows x 2 columns]

In [7]:
# filter by samples
columns_sample = [column for column in df_join_raw.columns if column.split("_")[0] not in groups_id_no]
df_join_raw_intensity = df_join_raw.loc[:, columns_sample]
df_join_raw_intensity = df_join_raw_intensity.iloc[:, 3:]
df_join_raw_intensity

,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,AR_1.8,AR_1.9,AR_1.10,...,PD_2.43,PD_2.44,PD_2.45,PD_2.46,PD_2.47,PD_2.48,PD_2.49,PD_2.50,PD_2.51,PD_2.52
0,3.761221,0.006085,0.013273,3.028000e-02,0.039917,0.050244,0.061226,0.072841,0.125292,0.170628,...,0.080008,2.152889,1.877989,3.006645,0.097180,0.083553,3.686441,0.084316,0.090964,0.083807
1,330.900909,3.345932,7.288550,1.660211e+01,21.875132,27.522388,33.526282,39.873536,68.517547,93.257600,...,98.324448,113.265571,220.143630,114.840334,217.630894,111.705774,157.403484,115.633361,154.460280,112.483808
2,3.810500,0.323930,0.609772,1.190270e+00,1.489259,1.794746,2.106842,2.425556,3.765647,4.837455,...,3.315511,3.413731,3.824988,3.421265,3.817551,3.406194,3.631237,3.428796,3.623766,66.207625
3,371.967656,0.779912,1.640943,3.603099e+00,4.689464,5.839993,7.051657,8.322116,13.959503,18.740646,...,23.200059,4.981860,352.301595,5.012925,152.542561,4.950816,312.257226,5.028466,5.371851,4.966335
4,14.383827,0.705709,1.341339,1.985815e+00,2.645173,3.320973,4.013620,4.723118,7.726113,10.145765,...,13.346583,14.103080,691.069505,587.099070,16.853497,14.034201,15.417710,977.423380,15.382943,14.068638
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,163.972145,0.257934,0.408042,6.627189e-01,0.779649,17223.650862,0.892598,1.002637,1.321292,1.629611,...,1.267927,1.498143,2.841460,1.518527,2.825464,1.477947,2.080693,1.528791,2.042619,1.488022
5440,5.318578,0.037040,0.088541,2.224989e-01,0.302977,0.391783,0.488620,0.593275,1.087500,1.535636,...,1.576491,1.885946,3.803859,1.913544,3.757898,1.858634,2.703381,1.927451,2.650225,1.872254
5441,44.795976,0.062477,0.158303,4.230803e-01,0.588121,0.773688,0.979274,1.204545,2.299264,2.962123,...,2.081027,2.412741,4.164254,2.447782,4.113120,2.378048,421.344464,2.465433,3.246804,2.395351
5442,32.469955,0.091943,0.246783,7.009899e-01,0.994539,1.330769,1.709164,2.129490,4.231004,6.255025,...,5.679157,6.495188,10.681201,40.563104,10.573695,6.418109,8.392011,6.572858,8.300825,6.456575
5443,87.571560,0.016108,0.035769,1.076772e+06,0.083146,0.110302,0.139565,0.170840,0.314832,0.441628,...,0.447106,0.522984,0.976927,0.529973,0.966075,0.516059,0.722467,0.533492,0.709443,0.519513

In [8]:
df_join_raw_intensity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5444 entries, 0 to 5443
Columns: 1248 entries, AR_1.1 to PD_2.52
dtypes: float64(1248)
memory usage: 51.9 MB

In [9]:
check_dataset(df_join_raw_intensity)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 6794112

### Generate graphs

In [10]:
""" from sklearn import preprocessing

X_scaled = preprocessing.RobustScaler().fit_transform(df_join_raw)

df_join_raw_log = pd.DataFrame(X_scaled, columns=df_join_raw.columns)
df_join_raw_log """

' from sklearn import preprocessing\n\nX_scaled = preprocessing.RobustScaler().fit_transform(df_join_raw)\n\ndf_join_raw_log = pd.DataFrame(X_scaled, columns=df_join_raw.columns)\ndf_join_raw_log '

In [11]:
# Transformation (log10)

if not has_transformation:
	df_join_raw_log = log10_global(df_join_raw_intensity)
else:
	df_join_raw_log = df_join_raw_intensity.copy()
df_join_raw_log.head()

,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,AR_1.8,AR_1.9,AR_1.10,...,PD_2.43,PD_2.44,PD_2.45,PD_2.46,PD_2.47,PD_2.48,PD_2.49,PD_2.50,PD_2.51,PD_2.52
0,3.761221,0.006085,0.013273,0.030280,0.039917,0.050244,0.061226,0.072841,0.125292,0.170628,...,0.080008,2.152889,1.877989,3.006645,0.097180,0.083553,3.686441,0.084316,0.090964,0.083807
1,330.900909,3.345932,7.288550,16.602111,21.875132,27.522388,33.526282,39.873536,68.517547,93.257600,...,98.324448,113.265571,220.143630,114.840334,217.630894,111.705774,157.403484,115.633361,154.460280,112.483808
2,3.810500,0.323930,0.609772,1.190270,1.489259,1.794746,2.106842,2.425556,3.765647,4.837455,...,3.315511,3.413731,3.824988,3.421265,3.817551,3.406194,3.631237,3.428796,3.623766,66.207625
3,371.967656,0.779912,1.640943,3.603099,4.689464,5.839993,7.051657,8.322116,13.959503,18.740646,...,23.200059,4.981860,352.301595,5.012925,152.542561,4.950816,312.257226,5.028466,5.371851,4.966335
4,14.383827,0.705709,1.341339,1.985815,2.645173,3.320973,4.013620,4.723118,7.726113,10.145765,...,13.346583,14.103080,691.069505,587.099070,16.853497,14.034201,15.417710,977.423380,15.382943,14.068638

In [12]:
check_dataset(df_join_raw_log)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 6794112

In [13]:
# split graph in groups and subgroups

""" def split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id, by_group=False):
	list_df_groups_subgroups = []
	for group in groups_id:
		df_aux = df_join_raw_log.filter(like=group)
		list_aux = []
		
		if by_group:
			list_aux.append(df_aux)
		else:
			for subgroup in subgroups_id[group]:
				list_aux.append(df_aux.filter(like="{}_{}.".format(group, subgroup)))
		list_df_groups_subgroups.append(list_aux)
	return list_df_groups_subgroups """

dict_df_groups_subgroups = split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id)
dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,AR_1.8,AR_1.9,AR_1.10,...,AR_1.221,AR_1.222,AR_1.223,AR_1.224,AR_1.225,AR_1.226,AR_1.227,AR_1.228,AR_1.229,AR_1.230
0,3.761221,0.006085,0.013273,0.030280,0.039917,0.050244,0.061226,0.072841,0.125292,0.170628,...,0.115679,2.591635,0.116000,0.117606,0.118249,3.152372,2.739992,5.079413,7.373953,2.656724
1,330.900909,3.345932,7.288550,16.602111,21.875132,27.522388,33.526282,39.873536,68.517547,93.257600,...,167.035094,168.051756,173.202682,183.848824,186.034213,188.238621,193.833710,196.105717,198.397337,199.550543
2,3.810500,0.323930,0.609772,1.190270,1.489259,1.794746,2.106842,2.425556,3.765647,4.837455,...,61.398011,3.468835,48.126401,3.538710,3.545692,45.525540,61.387017,3.566630,45.540835,44.316094
3,371.967656,0.779912,1.640943,3.603099,4.689464,5.839993,7.051657,8.322116,13.959503,18.740646,...,5.657818,72.845627,5.690376,5.706667,17.329060,419.508552,21.376463,219.669060,38.173112,212.791064
4,14.383827,0.705709,1.341339,1.985815,2.645173,3.320973,4.013620,4.723118,7.726113,10.145765,...,12.064185,12.090685,12.223326,29.969955,12.436053,588.303200,12.542658,12.596023,12.622721,12.649430

In [14]:
check_dataset(dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 1252120

In [15]:
# Transpose
dict_groups_subgroups_t = transpose_global(dict_df_groups_subgroups)
dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,3.761221,330.900909,3.810500,371.967656,14.383827,18.712536,417.143534,436.417402,447.090337,546.476338,...,44.344399,97.695020,0.490535,17.259178,74.363399,163.972145,5.318578,44.795976,32.469955,8.757156e+01
1,0.006085,3.345932,0.323930,0.779912,0.705709,1.268857,2.415192,2.922833,2.590675,3.762715,...,1.133275,0.837680,0.009950,0.498313,0.545725,0.257934,0.037040,0.062477,0.091943,1.610846e-02
2,0.013273,7.288550,0.609772,1.640943,1.341339,2.303849,4.318308,5.183555,4.703248,6.515885,...,2.634712,1.662149,0.023167,1.027306,0.918779,0.408042,0.088541,0.158303,0.246783,3.576926e-02
3,0.030280,16.602111,1.190270,3.603099,1.985815,4.328700,7.982784,9.500080,8.835714,11.644681,...,6.429114,3.430323,0.056623,2.207620,1.593778,0.662719,0.222499,0.423080,0.700990,1.076772e+06
4,0.039917,21.875132,1.489259,4.689464,2.645173,5.347228,9.807522,11.638008,10.914225,14.145286,...,8.668720,4.372835,0.076389,2.852567,1.916802,0.779649,0.302977,0.588121,0.994539,8.314640e-02

In [16]:
check_dataset(dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 1252120

In [17]:
# Correlation matrix

dict_groups_subgroups_t_corr = correlation_global(exp, dict_groups_subgroups_t)
dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

AR 1 (230, 5444)

AR 2 (230, 5444)
CRS 1 (14, 5444)
CRS 2 (14, 5444)

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/pingouin/correlation.py:954: RuntimeWarning: invalid value encountered in sqrt
  D = np.diag(np.sqrt(1 / np.diag(Vi)))

OSA 1 (29, 5444)
OSA 2 (30, 5444)
LPRD 1 (16, 5444)
LPRD 2 (16, 5444)
SGB 1 (43, 5444)
SGB 2 (44, 5444)
LSNB 1 (34, 5444)
LSNB 2 (35, 5444)
RCC 1 (71, 5444)
RCC 2 (72, 5444)
BC 1 (41, 5444)
BC 2 (42, 5444)
BPH 1 (39, 5444)
BPH 2 (39, 5444)
PCa 1 (53, 5444)
PCa 2 (53, 5444)
PD 1 (51, 5444)
PD 2 (52, 5444)

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,1.000000,-0.000263,0.000323,0.000319,-0.000306,-0.000372,-0.000628,0.000112,-0.000132,0.000371,...,-0.074758,0.164191,0.004363,-0.002529,0.004560,-0.036402,0.042348,0.000487,-0.004211,0.002699
1,-0.000263,1.000000,1.000000,1.000000,-1.000000,-1.000000,-0.999994,-1.000000,-1.000000,1.000000,...,0.957228,-0.788030,-0.997870,-0.995818,-0.998317,0.951918,0.947874,0.997395,-0.998506,-0.999291
2,0.000323,1.000000,1.000000,-1.000000,1.000000,1.000000,0.999994,0.999999,1.000000,-1.000000,...,-0.957223,0.788003,0.997873,0.995823,0.998321,-0.951922,-0.947868,-0.997398,0.998509,0.999294
3,0.000319,1.000000,-1.000000,1.000000,1.000000,1.000000,0.999994,0.999999,1.000000,-1.000000,...,-0.957222,0.788005,0.997873,0.995823,0.998321,-0.951921,-0.947866,-0.997399,0.998509,0.999294
4,-0.000306,-1.000000,1.000000,1.000000,1.000000,-1.000000,-0.999994,-1.000000,-1.000000,1.000000,...,0.957229,-0.788016,-0.997869,-0.995822,-0.998319,0.951905,0.947873,0.997395,-0.998506,-0.999292

In [18]:
# Check correlation matrices

dict_groups_subgroups_t_corr

{'AR': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.000263  0.000323  0.000319 -0.000306 -0.000372 -0.000628
  1    -0.000263  1.000000  1.000000  1.000000 -1.000000 -1.000000 -0.999994
  2     0.000323  1.000000  1.000000 -1.000000  1.000000  1.000000  0.999994
  3     0.000319  1.000000 -1.000000  1.000000  1.000000  1.000000  0.999994
  4    -0.000306 -1.000000  1.000000  1.000000  1.000000 -1.000000 -0.999994
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.036402  0.951918 -0.951922 -0.951921  0.951905  0.951873  0.951912
  5440  0.042348  0.947874 -0.947868 -0.947866  0.947873  0.947872  0.947816
  5441  0.000487  0.997395 -0.997398 -0.997399  0.997395  0.997391  0.997439
  5442 -0.004211 -0.998506  0.998509  0.998509 -0.998506 -0.998502 -0.998506
  5443  0.002699 -0.999291  0.999294  0.999294 -0.999292 -0.999287 -0.999297

            7         8         9     ...      5434      5435      5436  \
  0     0.000112 -0.000132  0.000371  ... -0.074758  0.164191  0.004363
  1    -1.000000 -1.000000  1.000000  ...  0.957228 -0.788030 -0.997870
  2     0.999999  1.000000 -1.000000  ... -0.957223  0.788003  0.997873
  3     0.999999  1.000000 -1.000000  ... -0.957222  0.788005  0.997873
  4    -1.000000 -1.000000  1.000000  ...  0.957229 -0.788016 -0.997869
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.951908  0.951936 -0.951917  ... -0.905420  0.736448  0.949916
  5440  0.947949  0.947855 -0.947860  ... -0.907034  0.723301  0.945181
  5441  0.997388  0.997396 -0.997399  ... -0.951536  0.791784  0.995648
  5442 -0.998500 -0.998513  0.998508  ...  0.954680 -0.790109 -0.999418
  5443 -0.999286 -0.999294  0.999294  ...  0.956076 -0.787933 -0.997289

            5437      5438      5439      5440      5441      5442      5443
  0    -0.002529  0.004560 -0.036402  0.042348  0.000487 -0.004211  0.002699
  1    -0.995818 -0.998317  0.951918  0.947874  0.997395 -0.998506 -0.999291
  2     0.995823  0.998321 -0.951922 -0.947868 -0.997398  0.998509  0.999294
  3     0.995823  0.998321 -0.951921 -0.947866 -0.997399  0.998509  0.999294
  4    -0.995822 -0.998319  0.951905  0.947873  0.997395 -0.998506 -0.999292
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.948529  0.948207  1.000000 -0.927911 -0.947885  0.950470  0.952488
  5440  0.940392  0.943697 -0.927911  1.000000 -0.944125  0.944802  0.946522
  5441  0.993068  0.995781 -0.947885 -0.944125  1.000000  0.995924  0.996747
  5442 -0.994217 -0.997081  0.950470  0.944802  0.995924  1.000000 -0.997859
  5443 -0.995231 -0.997874  0.952488  0.946522  0.996747 -0.997859  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000  0.136320 -0.153833  0.169077 -0.102607 -0.086576  0.060449
  1     0.136320  1.000000 -0.264262 -0.242369 -0.413567 -0.171860 -0.362385
  2    -0.153833 -0.264262  1.000000  0.236117  0.095081  0.160630  0.046933
  3     0.169077 -0.242369  0.236117  1.000000 -0.508966 -0.599625 -0.516818
  4    -0.102607 -0.413567  0.095081 -0.508966  1.000000 -0.698700 -0.708443
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.115613  0.149367  0.198331 -0.192535  0.049622 -0.171067 -0.161190
  5440 -0.029644  0.152338  0.519694 -0.298998 -0.145469 -0.286141 -0.177061
  5441  0.272440  0.146618  0.264276 -0.023831  0.092433 -0.055263  0.030747
  5442  0.206369  0.160144  0.011807 -0.013524  0.058271  0.029726 -0.114563
  5443 -0.206824 -0.014754  0.066570 -0.010488 -0.096282 -0.021074 -0.004653

            7         8         9     ...      5434      5435      5436  \
  0     0.007258  0.079516  0.076771  ...  0.173172  0.035174 -0.153803
  1    -0.274849 -0.193533 -0.268334  ...  0.087986  0.108345  0.213399
  2     0.017404  0.251048  0.311965  ...  0.291022 -0.135869  0.065615
  3    -0.609111 -0.581217 -0.513669  ... -0.046241 -0.038432  0.123265
  4    -0.675244 -0.623278 -0.668047  ... -0.063783 -0.006437 -0.046513
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.182127 -0.291065 -0.157608  ... -0.179424 -0.641539  0.256398
  5440 -0.204785 -0.338143 -0.309706  ... -0.096060 -0.292313  0.134657
  5441  0.111781 -0.062316 -0.192880  ... -0.700524 -0.439089 -0.116108
  5442 -0.047689 -0.081697 -0.057556  ... -0.563019 -0.827951  0.066610
  5443 -0.138721 -0.221670 -0.144423  ... -0.300094 -0.519483  0.116413

            5437      5438      5439      5440      5441      5442      5443
  0    -0.171964  0.169854  0.115613 -0.029644  0.272440  0.206369 -0.206824
  1    -0.041364  0.095070  0.149367  0.152338  0.146618  0.160144 -0.014754
  2    -0.180094  0.334249  0.198331  0.519694  0.264276  0.011807  0.066570
  3     0.115643 -0.209908 -0.192535 -0.298998 -0.023831 -0.013524 -0.010488
  4    -0.126360  0.079549  0.049622 -0.145469  0.092433  0.058271 -0.096282
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.234715 -0.798531  1.000000 -0.481799 -0.564501 -0.672055 -0.575049
  5440  0.288115 -0.547933 -0.481799  1.000000 -0.161527 -0.108477 -0.492863
  5441  0.330280 -0.733472 -0.564501 -0.161527  1.000000 -0.751441 -0.466329
  5442  0.222094 -0.645965 -0.672055 -0.108477 -0.751441  1.000000 -0.525969
  5443  0.261602 -0.612101 -0.575049 -0.492863 -0.466329 -0.525969  1.000000

  [5444 rows x 5444 columns]},
 'CRS': {'1':           0         1         2         3         4         5         6     \
  0     1.000000  0.682235 -0.999781 -0.999058 -0.720585 -0.999517 -0.999636
  1     0.682235  1.000000  0.675348  0.671961  0.487887  0.673975  0.674210
  2    -0.999781  0.675348  1.000000 -0.998290 -0.724986 -0.998934 -0.999128
  3    -0.999058  0.671961 -0.998290  1.000000 -0.714554 -0.999919 -0.999856
  4    -0.720585  0.487887 -0.724986 -0.714554  1.000000 -0.716085 -0.717028
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.138144 -0.208042  0.147796  0.105560  0.472705  0.114128  0.117411
  5440  0.855751 -0.711550  0.857375  0.841705  0.470297  0.846401  0.847533
  5441 -0.442014  0.382837 -0.442565 -0.442624 -0.026042 -0.444006 -0.443847
  5442 -0.111414 -0.073619 -0.114982 -0.123342  0.198235 -0.121670 -0.120932
  5443  0.116667 -0.283361  0.125606  0.083118  0.401790  0.092221  0.095466

            7         8         9     ...      5434      5435      5436  \
  0    -0.999603 -0.999423 -0.999646  ...  0.530614 -0.124086 -0.469762
  1     0.674124  0.673484  0.673162  ... -0.746283 -0.178836  0.540634
  2    -0.999074 -0.998810 -0.999202  ...  0.522401 -0.131715 -0.466850
  3    -0.999876 -0.999949 -0.999825  ...  0.517358 -0.134959 -0.467789
  4    -0.716770 -0.715753 -0.717536  ...  0.339421  0.038344 -0.040104
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.116460  0.111960  0.117852  ... -0.369500 -0.519798 -0.293593
  5440  0.847197  0.845382  0.847466  ... -0.636656  0.130662  0.716204
  5441 -0.443892 -0.444707 -0.444428  ...  0.151495 -0.648274 -0.959083
  5442 -0.121165 -0.123264 -0.122576  ... -0.457745 -0.951126 -0.616512
  5443  0.094522  0.090324  0.095878  ... -0.417377 -0.416818 -0.047671

            5437      5438      5439      5440      5441      5442      5443
  0     0.579543 -0.383131  0.138144  0.855751 -0.442014 -0.111414  0.116667
  1    -0.841228  0.482378 -0.208042 -0.711550  0.382837 -0.073619 -0.283361
  2     0.569346 -0.376686  0.147796  0.857375 -0.442565 -0.114982  0.125606
  3     0.570330 -0.389044  0.105560  0.841705 -0.442624 -0.123342  0.083118
  4     0.239192  0.114442  0.472705  0.470297 -0.026042  0.198235  0.401790
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.198243 -0.520365  1.000000 -0.115608 -0.395066 -0.649029 -0.948165
  5440 -0.668400  0.623502 -0.115608  1.000000  0.664551  0.218597 -0.173109
  5441  0.267269 -0.930719 -0.395066  0.664551  1.000000 -0.797522 -0.167907
  5442 -0.272382 -0.666043 -0.649029  0.218597 -0.797522  1.000000 -0.488886
  5443 -0.263569 -0.295811 -0.948165 -0.173109 -0.167907 -0.488886  1.000000

  [5444 rows x 5444 columns],
  '2':               0     1             2             3     4     5     6     \
  0     1.000000e+00   NaN -1.065836e-09  1.322147e-11   NaN   NaN   NaN
  1              NaN   1.0           NaN           NaN   NaN   NaN   NaN
  2    -1.065836e-09   NaN  1.000000e+00  1.732679e+00   NaN   NaN   NaN
  3     1.322147e-11   NaN  1.732679e+00  1.000000e+00   NaN   NaN   NaN
  4              NaN   NaN           NaN           NaN   1.0   NaN   NaN
  ...            ...   ...           ...           ...   ...   ...   ...
  5439 -5.911729e-06   NaN -1.008406e+00  1.931095e+00   NaN   NaN   NaN
  5440 -6.201069e-06   NaN -1.038732e+00  2.197403e+00   NaN   NaN   NaN
  5441           NaN   NaN           NaN           NaN   NaN   NaN   NaN
  5442           NaN   NaN           NaN           NaN   NaN   NaN   NaN
  5443 -3.148360e-06   NaN -1.100289e+00  1.257040e+00   NaN   NaN   NaN

                7             8             9     ...  5434      5435      5436  \
  0     4.778362e-11  1.430433e-11  4.691041e-11  ...   NaN -0.000004  0.000004
  1              NaN           NaN           NaN  ...   NaN       NaN       NaN
  2    -4.054693e+00  1.000162e+00  1.003175e+00  ...   NaN -1.002542  1.102044
  3     1.465385e+00 -1.758419e+00 -1.851029e+00  ...   NaN  1.636130 -1.254150
  4              NaN           NaN           NaN  ...   NaN       NaN       NaN
  ...            ...           ...           ...  ...   ...       ...       ...
  5439 -4.599337e+00  1.006231e+00  1.001245e+00  ...   NaN -1.020239  1.171484
  5440 -5.315926e+00  1.033843e+00  1.019619e+00  ...   NaN -1.061420  1.274872
  5441           NaN           NaN           NaN  ...   NaN       NaN       NaN
  5442           NaN           NaN           NaN  ...   NaN       NaN       NaN
  5443 -2.657912e+00  1.108725e+00  1.140385e+00  ...   NaN -1.070342  1.000007

            5437      5438      5439      5440  5441  5442      5443
  0    -0.000002 -0.000003 -0.000006 -0.000006   NaN   NaN -0.000003
  1          NaN       NaN       NaN       NaN   NaN   NaN       NaN
  2     2.964056 -1.107483 -1.008406 -1.038732   NaN   NaN -1.100289
  3    -1.187568  1.245466  1.931095  2.197403   NaN   NaN  1.257040
  4          NaN       NaN       NaN       NaN   NaN   NaN       NaN
  ...        ...       ...       ...       ...   ...   ...       ...
  5439  3.351518 -1.178632  1.000000 -1.010951   NaN   NaN -1.169170
  5440  3.862936 -1.284118 -1.010951  1.000000   NaN   NaN -1.271872
  5441       NaN       NaN       NaN       NaN   1.0   NaN       NaN
  5442       NaN       NaN       NaN       NaN   NaN   1.0       NaN
  5443  1.980720 -1.000118 -1.169170 -1.271872   NaN   NaN  1.000000

  [5444 rows x 5444 columns]},
 'OSA': {'1':           0         1         2         3         4         5         6     \
  0     1.000000  0.317971  0.047228  0.124503  0.117411  0.132670  0.114239
  1     0.317971  1.000000 -0.592825 -0.641016 -0.636000 -0.644556 -0.636799
  2     0.047228 -0.592825  1.000000 -0.992985 -0.994379 -0.991804 -0.994271
  3     0.124503 -0.641016 -0.992985  1.000000 -0.999918 -0.999943 -0.999923
  4     0.117411 -0.636000 -0.994379 -0.999918  1.000000 -0.999754 -0.999978
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.410185  0.212489  0.069278  0.111927  0.106979  0.114868  0.107511
  5440 -0.830381  0.104836 -0.071951 -0.010356 -0.015100 -0.002915 -0.019346
  5441 -0.393757  0.235511  0.436183  0.458229  0.456602  0.459869  0.455305
  5442 -0.477633  0.263659  0.301983  0.336307  0.332678  0.338212  0.331720
  5443 -0.288668  0.378217  0.454232  0.486300  0.482891  0.486896  0.482587

            7         8         9     ...      5434      5435      5436  \
  0     0.112563  0.076109  0.127532  ... -0.542247 -0.705527  0.471175
  1    -0.636345 -0.613925 -0.642053  ...  0.242537  0.183160 -0.217988
  2    -0.994330 -0.983892 -0.992579  ...  0.408358  0.231514  0.159121
  3    -0.999908 -0.991386 -0.999991  ...  0.445919  0.274445  0.101539
  4    -0.999967 -0.991135 -0.999874  ...  0.443535  0.271424  0.105962
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.107243  0.109466  0.112840  ... -0.504535 -0.625467  0.057623
  5440 -0.020880 -0.060889 -0.007335  ... -0.738834 -0.893935  0.713179
  5441  0.455027  0.432747  0.458965  ... -0.886419 -0.863842  0.258823
  5442  0.331554  0.302621  0.336868  ... -0.711679 -0.793661  0.174983
  5443  0.483085  0.461314  0.486359  ... -0.717460 -0.643925  0.311255

            5437      5438      5439      5440      5441      5442      5443
  0     0.383497 -0.769764 -0.410185 -0.830381 -0.393757 -0.477633 -0.288668
  1    -0.121751  0.157376  0.212489  0.104836  0.235511  0.263659  0.378217
  2     0.161852  0.059954  0.069278 -0.071951  0.436183  0.301983  0.454232
  3     0.135553  0.122046  0.111927 -0.010356  0.458229  0.336307  0.486300
  4     0.137171  0.117223  0.106979 -0.015100  0.456602  0.332678  0.482891
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.555145 -0.528315  1.000000 -0.454853 -0.724767 -0.886939 -0.643310
  5440  0.725788 -0.957314 -0.454853  1.000000 -0.566718 -0.538718 -0.350081
  5441  0.565080 -0.723951 -0.724767 -0.566718  1.000000 -0.906669 -0.833004
  5442  0.558246 -0.633847 -0.886939 -0.538718 -0.906669  1.000000 -0.865039
  5443  0.425953 -0.503913 -0.643310 -0.350081 -0.833004 -0.865039  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000 -0.593374  0.338839 -0.999177 -0.992442 -0.995767 -0.183090
  1    -0.593374  1.000000  0.669848 -0.587934 -0.567078 -0.576892 -0.061893
  2     0.338839  0.669848  1.000000  0.341816  0.336892  0.325708 -0.045875
  3    -0.999177 -0.587934  0.341816  1.000000 -0.988762 -0.992185 -0.212655
  4    -0.992442 -0.567078  0.336892 -0.988762  1.000000 -0.996750 -0.095541
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.094591 -0.221607  0.088541  0.118085  0.091381  0.069274  0.190951
  5440  0.075497 -0.163605  0.056952  0.101617  0.056325  0.037199  0.301730
  5441  0.012839 -0.303494  0.138168  0.034776  0.012236 -0.002500  0.092288
  5442  0.065448 -0.268320  0.097230  0.087570  0.066972  0.047576  0.116023
  5443  0.095294 -0.250420  0.103701  0.116920  0.100389  0.077053  0.129698

            7         8         9     ...      5434      5435      5436  \
  0    -0.998837 -0.998984 -0.999442  ... -0.176215 -0.009955 -0.017476
  1    -0.583077 -0.586693 -0.583964  ...  0.341174 -0.250390 -0.335461
  2     0.334953  0.341698  0.335028  ... -0.029124  0.138658  0.203987
  3    -0.996924 -0.997251 -0.998086  ... -0.187204  0.012418  0.003979
  4    -0.995694 -0.995564 -0.994711  ... -0.220202 -0.014212 -0.019256
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.091019  0.094078  0.095458  ...  0.606762 -0.966988 -0.976139
  5440  0.064819  0.069026  0.071398  ...  0.511976 -0.976060 -0.916922
  5441  0.014710  0.017014  0.017584  ...  0.545181 -0.952951 -0.996960
  5442  0.066005  0.068626  0.069180  ...  0.603059 -0.950254 -0.988780
  5443  0.095400  0.097944  0.098656  ...  0.630816 -0.952178 -0.982144

            5437      5438      5439      5440      5441      5442      5443
  0    -0.578470 -0.177994  0.094591  0.075497  0.012839  0.065448  0.095294
  1    -0.369393  0.006407 -0.221607 -0.163605 -0.303494 -0.268320 -0.250420
  2     0.306434  0.314770  0.088541  0.056952  0.138168  0.097230  0.103701
  3    -0.558235 -0.170860  0.118085  0.101617  0.034776  0.087570  0.116920
  4    -0.621246 -0.228658  0.091381  0.056325  0.012236  0.066972  0.100389
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.236755  0.100427  1.000000 -0.964842 -0.981714 -0.991951 -0.995002
  5440 -0.353398 -0.122790 -0.964842  1.000000 -0.921259 -0.932224 -0.935635
  5441 -0.205380  0.156233 -0.981714 -0.921259  1.000000 -0.995442 -0.988159
  5442 -0.184373  0.183276 -0.991951 -0.932224 -0.995442  1.000000 -0.996868
  5443 -0.181939  0.173902 -0.995002 -0.935635 -0.988159 -0.996868  1.000000

  [5444 rows x 5444 columns]},
 'LPRD': {'1':       0         1         2     3     4     5     6     7     8     9     ...  \
  0      1.0       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
  1      NaN  1.000000  5.804388   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
  2      NaN  5.804388  1.000000   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
  3      NaN       NaN       NaN   1.0   NaN   NaN   NaN   NaN   NaN   NaN  ...
  4      NaN       NaN       NaN   NaN   1.0   NaN   NaN   NaN   NaN   NaN  ...
  ...    ...       ...       ...   ...   ...   ...   ...   ...   ...   ...  ...
  5439   NaN -1.888170  2.341096   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
  5440   NaN -1.071494  4.175219   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
  5441   NaN       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
  5442   NaN       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
  5443   NaN -1.118783  3.796079   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...

        5434  5435       5436  5437  5438      5439      5440  5441  5442  \
  0      NaN   NaN        NaN   NaN   NaN       NaN       NaN   NaN   NaN
  1      NaN   NaN   1.625013   NaN   NaN -1.888170 -1.071494   NaN   NaN
  2      NaN   NaN -11.636622   NaN   NaN  2.341096  4.175219   NaN   NaN
  3      NaN   NaN        NaN   NaN   NaN       NaN       NaN   NaN   NaN
  4      NaN   NaN        NaN   NaN   NaN       NaN       NaN   NaN   NaN
  ...    ...   ...        ...   ...   ...       ...       ...   ...   ...
  5439   NaN   NaN   4.177544   NaN   NaN  1.000000 -1.493893   NaN   NaN
  5440   NaN   NaN   1.757798   NaN   NaN -1.493893  1.000000   NaN   NaN
  5441   NaN   NaN        NaN   NaN   NaN       NaN       NaN   1.0   NaN
  5442   NaN   NaN        NaN   NaN   NaN       NaN       NaN   NaN   1.0
  5443   NaN   NaN   1.905071   NaN   NaN -1.385387 -1.006878   NaN   NaN

            5443
  0          NaN
  1    -1.118783
  2     3.796079
  3          NaN
  4          NaN
  ...        ...
  5439 -1.385387
  5440 -1.006878
  5441       NaN
  5442       NaN
  5443  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000  0.692312 -0.295868 -0.999760 -0.999570 -0.999744 -0.999818
  1     0.692312  1.000000  0.202745  0.699478  0.702080  0.699975  0.698757
  2    -0.295868  0.202745  1.000000 -0.292170 -0.288784 -0.292915 -0.293163
  3    -0.999760  0.699478 -0.292170  1.000000 -0.999967 -0.999997 -0.999993
  4    -0.999570  0.702080 -0.288784 -0.999967  1.000000 -0.999967 -0.999940
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.872371 -0.798152  0.135876  0.879654  0.882115  0.879605  0.878455
  5440  0.879071 -0.798461  0.139554  0.885803  0.888113  0.885762  0.884707
  5441  0.723961 -0.896518  0.116094  0.734088  0.738352  0.734607  0.733113
  5442  0.782675 -0.913876  0.130153  0.791751  0.795239  0.792133  0.790723
  5443  0.866858 -0.817338  0.136387  0.874310  0.876859  0.874308  0.873129

            7         8         9     ...      5434      5435      5436  \
  0    -0.999744 -0.999708 -0.999705  ...  0.688452  0.723297 -0.999027
  1     0.699634  0.700158  0.700205  ... -0.926479 -0.811755  0.701137
  2    -0.291879 -0.291795 -0.291800  ...  0.042350  0.065953 -0.276297
  3    -1.000000 -0.999998 -0.999997  ...  0.697214  0.730535 -0.999556
  4    -0.999973 -0.999980 -0.999981  ...  0.700545  0.733088 -0.999710

In [19]:
check_dataset(dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][1]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 15052776
Count zero:	 0
Count positive:	 14584360

In [20]:
# Build graph (corpus graphs)

dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

      source  target    weight subgroup
3547       0    3548  0.586009        1
3639       0    3640 -0.595230        1
5443       1       2  1.000000        1
5444       1       3  1.000000        1
5445       1       4 -1.000000        1

In [21]:
def create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups, df_join_raw_metadata):	
	for group_id in tqdm(groups_id):
		for subgroup_id in tqdm(subgroups_id[group_id]):
			df_weighted_edges = pd.read_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id))
			# print(df_weighted_edges)
			G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight", "subgroup"])
			dict_id_idx = dict(zip(list(G.nodes()), range(G.number_of_nodes())))
			G = nx.relabel_nodes(G, dict_id_idx)

			df_nodes = dict_df_groups_subgroups[group_id][subgroup_id].loc[list(dict_id_idx.keys())] # A_1.1, A_1.2, A_1.3
			# from IPython.display import display
			# display(df_nodes)

			# nodes, with node features
			metadata = df_join_raw_metadata.loc[df_nodes.index] # Average Rt, Average Mz
			# intensity = df_join_raw_log.loc[df_nodes.index] # A_1.1, A_1.2, A_1.3, A_2.1, ...

			""" e = 1e-8
			mz = metadata.iloc[:, 1].values
			rt = metadata.iloc[:, 0].values
			intensity_mean = df_nodes.mean(axis=1).values
			intensity_std = df_nodes.std(axis=1).values
			intensity_cv = intensity_std / intensity_mean
			presence_ratio = (df_nodes > 0).mean(axis=1)

			mz_log = np.log10(mz + e)
			# intensity_mean_log = np.log10(intensity_mean + e)
			
			# mz_z = (mz_log - mz_log.mean()) / mz_log.std() # z-score
			rt_z = (rt - rt.mean()) / rt.std() # z-score
			# intensity_mean_z = (intensity_mean_log - intensity_mean_log.mean()) / intensity_mean_log.std() # z-score

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": mz_log,
				"rt": rt_z,
				"intensity_mean": intensity_mean,
				"intensity_std": intensity_std,
				"intensity_cv": intensity_cv,
				"presence_ratio": presence_ratio
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			# df_node_features.insert(0, "idx", list(dict_id_idx.values()))
			# df_node_features.insert(1, "id", list(dict_id_idx.keys()))
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features) """

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": metadata.iloc[:, 1].values,
				"rt": metadata.iloc[:, 0].values,
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features)

			# edges
			edges = list(G.edges())
			df_edges = pd.DataFrame(edges, columns=["source", "target"])
			df_edges["weight"] = [G.get_edge_data(*edge)["weight"] for edge in edges]
			df_edges["subgroup"] = [G.get_edge_data(*edge)["subgroup"] for edge in edges]
			df_edges.to_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)

In [22]:
# create dataset - nodes/edge data for PyTorch Geometric/DGL framework

# IMPORTANT
dict_df_groups_subgroups_ = split_groups_subgroups(df_join_raw_intensity, groups_id, subgroups_id) # Important (intesities without Log)

for data_variation in data_variations:
	if data_variation == "none":
		create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, df_join_raw_metadata)
	else:
		# dynamic graph to static graph
		create_graph_data_directed_variation(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, data_variation)

  0%|          | 0/11 [00:00<?, ?it/s]

100%|██████████| 2/2 [01:06<00:00, 33.10s/it]
100%|██████████| 2/2 [00:46<00:00, 23.34s/it]]
100%|██████████| 2/2 [00:46<00:00, 23.28s/it]]
100%|██████████| 2/2 [01:07<00:00, 33.95s/it]]
100%|██████████| 2/2 [00:21<00:00, 10.91s/it]]
100%|██████████| 2/2 [00:21<00:00, 10.64s/it]]
100%|██████████| 2/2 [00:08<00:00,  4.31s/it]]
100%|██████████| 2/2 [00:30<00:00, 15.38s/it]]
100%|██████████| 2/2 [00:24<00:00, 12.24s/it]]
100%|██████████| 2/2 [01:14<00:00, 37.14s/it]]
100%|██████████| 2/2 [00:33<00:00, 16.71s/it]t]
100%|██████████| 11/11 [07:22<00:00, 40.18s/it]

In [23]:
# details
list_details = []
	
for group_id in groups_id:
	subgroups_id_ = []
	for data_variation in data_variations:
		if data_variation == "none":
			subgroups_id_ += subgroups_id[group_id]
		else:
			subgroups_id_ += [data_variation]
	# print(subgroups)
	
	for subgroup_id_ in subgroups_id_:
		try:
			df_edges = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id_))

			G = nx.from_pandas_edgelist(df_edges.iloc[:, [0, 1]])
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), nx.density(G), np.nan, nx.is_connected(G)])
		except:
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), np.nan, np.nan, np.nan])

df_details = pd.DataFrame(list_details, columns=["Group", "Subgroup", "Num. nodes", "Num. edges", "Density", "Diameter", "Is connected"])
df_details.to_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp), index=False)

df_details = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp))
df_details

   Group  Subgroup  Num. nodes  Num. edges   Density  Diameter  Is connected
0     AR         1        5426    13817755  0.938832       NaN         False
1     AR         2        5367      107977  0.007499       NaN         False
2    CRS         1        5444     4870424  0.328731       NaN          True
3    CRS         2        3521     6196960  1.000000       NaN          True
4    OSA         1        5444     4952086  0.334243       NaN          True
5    OSA         2        5443     3641622  0.245883       NaN          True
6   LPRD         1        4035     8138595  1.000000       NaN          True
7   LPRD         2        5444     8015568  0.541013       NaN         False
8    SGB         1        5442     2102654  0.142024       NaN          True
9    SGB         2           2           1  1.000000       NaN          True
10  LSNB         1        5444     2912019  0.196548       NaN          True
11  LSNB         2        5444     1702327  0.114899       NaN          True
12   RCC         1        5441      738796  0.049920       NaN          True
13   RCC         2        5443     1030667  0.069591       NaN          True
14    BC         1        5444     3420096  0.230840       NaN          True
15    BC         2        5442     2339111  0.157995       NaN          True
16   BPH         1        5443     2681801  0.181075       NaN          True
17   BPH         2        5444     2590523  0.174848       NaN         False
18   PCa         1        5442     1737682  0.117372       NaN          True
19   PCa         2        5443    14794090  0.998899       NaN          True
20    PD         1        5444     2403274  0.162210       NaN          True
21    PD         2        5444     2420712  0.163387       NaN          True

---

In [24]:
X = dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]]
X

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,3.761221,330.900909,3.810500,371.967656,14.383827,18.712536,417.143534,436.417402,447.090337,546.476338,...,44.344399,97.695020,0.490535,17.259178,74.363399,163.972145,5.318578,44.795976,32.469955,8.757156e+01
1,0.006085,3.345932,0.323930,0.779912,0.705709,1.268857,2.415192,2.922833,2.590675,3.762715,...,1.133275,0.837680,0.009950,0.498313,0.545725,0.257934,0.037040,0.062477,0.091943,1.610846e-02
2,0.013273,7.288550,0.609772,1.640943,1.341339,2.303849,4.318308,5.183555,4.703248,6.515885,...,2.634712,1.662149,0.023167,1.027306,0.918779,0.408042,0.088541,0.158303,0.246783,3.576926e-02
3,0.030280,16.602111,1.190270,3.603099,1.985815,4.328700,7.982784,9.500080,8.835714,11.644681,...,6.429114,3.430323,0.056623,2.207620,1.593778,0.662719,0.222499,0.423080,0.700990,1.076772e+06
4,0.039917,21.875132,1.489259,4.689464,2.645173,5.347228,9.807522,11.638008,10.914225,14.145286,...,8.668720,4.372835,0.076389,2.852567,1.916802,0.779649,0.302977,0.588121,0.994539,8.314640e-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,3.152372,188.238621,45.525540,419.508552,588.303200,632.905658,868.230825,893.355253,891.266566,1017.304303,...,2266.695130,789.492613,0.353199,125.045388,813.632647,2.595428,3.301592,717.376519,526.243502,2.091185e+02
226,2.739992,193.833710,61.387017,21.376463,12.542658,16.362260,26.896021,27.274930,24.390295,24.720117,...,126.410739,20.395373,26.030318,689.883993,5.830708,2.671095,3.405531,88.003434,10.043272,9.183591e-01
227,5.079413,196.105717,3.566630,219.669060,12.596023,16.428755,298.451725,329.900933,324.857513,422.506955,...,36.772413,20.607614,0.358340,13.005563,5.900927,2.686421,3.447796,3.938186,10.147011,9.288274e-01
228,7.373953,198.397337,45.540835,38.173112,12.622721,16.462014,26.947281,27.381806,24.489886,28.985015,...,36.970233,20.821374,0.360064,13.118376,5.936268,2.717266,3.490459,3.962902,10.251487,9.393837e-01
229,2.656724,199.550543,44.316094,212.791064,12.649430,16.495280,304.702629,349.185508,356.609496,409.640533,...,37.168748,20.928826,0.361793,13.175006,5.971763,2.732787,3.511941,3.987730,10.304002,9.446950e-01

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 0.96013323, -0.18319677, -0.06898287, ..., -0.11258906,
        -0.07363153, -0.07805489],
       [-0.91476946, -0.21063439, -0.06945523, ..., -0.11268725,
        -0.07365321, -0.07926111],
       [-0.91118024, -0.21030414, -0.06941651, ..., -0.11268704,
        -0.07365311, -0.07926084],
       ...,
       [ 1.61829342, -0.19448788, -0.06901591, ..., -0.11267875,
        -0.07364648, -0.07924854],
       [ 2.76393481, -0.19429592, -0.06332917, ..., -0.11267869,
        -0.07364641, -0.07924839],
       [ 0.40866874, -0.19419933, -0.0634951 , ..., -0.11267864,
        -0.07364637, -0.07924832]])

In [26]:
import numpy as np
from sklearn.covariance import GraphicalLassoCV

cv = min(5, X_scaled.shape[0])

# X_scaled: matriz (n_muestras, p_metabolitos), ya estandarizada (media 0, var 1)
modelo = GraphicalLassoCV(cv=3, n_jobs=-1) # cv=3, max_iter=200)
modelo.fit(X_scaled)

Omega = modelo.precision_          # matriz de precisión dispersa (p x p)
lambda_optimo = modelo.alpha_      # lambda elegido por CV

# Correlación parcial a partir de Omega
d = np.sqrt(np.diag(Omega))
P = -Omega / np.outer(d, d)
np.fill_diagonal(P, 1.0)           # P[i,j] = correlación parcial entre i y j

""" # Matriz de adyacencia binaria para tu grafo (umbral en 0, ya que glasso fuerza ceros exactos)
adyacencia = (Omega != 0).astype(int)
np.fill_diagonal(adyacencia, 0)
adyacencia """
P

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.007372212094168162, tolerance: 0.006431368037763544
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.008086189842913427, tolerance: 0.007031509353046799
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.04142898136007034, tolerance: 0.02406804804190885
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.012925719703339666, tolerance: 0.004600739137233801
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0096105057133542, tolerance: 0.008256563425185087
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.008548095315504156, tolerance: 0.008350636785357897
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.015515697166762266, tolerance: 0.01287620869103032
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.01125109125004542, tolerance: 0.004718816614448247
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.060367767201455536, tolerance: 0.024141128179017736
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.007069937774517143, tolerance: 0.0033319194912064974
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.007446882768320506, tolerance: 0.0026923601322367246
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.018964857524807144, tolerance: 0.013095010874775227
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.004761019289382773, tolerance: 0.004532446351497916
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.007630753806516566, tolerance: 0.00615454824080052
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.01092016522182604, tolerance: 0.004107371592959297
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.014115334739358332, tolerance: 0.012707561899555605
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.017974904437622286, tolerance: 0.01269468942597303
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.032251356255741825, tolerance: 0.008665003983831835
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.007156400193949253, tolerance: 0.005333507159069807
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.010403408161565153, tolerance: 0.004323666306290409
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.01492189231703378, tolerance: 0.01232615442397956
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.019574842833677053, tolerance: 0.012332367104889655
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.004952271246249751, tolerance: 0.0029181541954519706
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.035755177609303246, tolerance: 0.008783950532529469
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.02669743871538799, tolerance: 0.02265955638964
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.025857998426005224, tolerance: 0.021888447001181553
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.019209926981645253, tolerance: 0.012332633905830495
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.017891003222842983, tolerance: 0.012407747921258901
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.07902982450360696, tolerance: 0.026191839455606453
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.09212519624881566, tolerance: 0.02627516844721571
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0073504036829064034, tolerance: 0.006884926252002379
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.004788233974064582, tolerance: 0.002643612607731043
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.025690526758125998, tolerance: 0.024708244463015165
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.013207204866944267, tolerance: 0.012207754569844942
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.007921215759274958, tolerance: 0.0045620968110596976
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.02007671816556922, tolerance: 0.015495412988491147
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.009481866968307884, tolerance: 0.004566603319447108
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.011809072793198538, tolerance: 0.009994690191913376
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.004036331851565933, tolerance: 0.003538906914469352
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.005932379426177192, tolerance: 0.00436788661350802
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0069905720805039095, tolerance: 0.004368292548572742
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.01678686388930828, tolerance: 0.013649856806974078
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.008869200218072137, tolerance: 0.0045679624826485314
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.02527280547207056, tolerance: 0.011817630420066923
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.012670658655054012, tolerance: 0.009003395350639895
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.010019771950766199, tolerance: 0.008390773322305938
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.003868899900638212, tolerance: 0.003604952624541273
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.018773714219690874, tolerance: 0.01803163998961045
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.005369022866290152, tolerance: 0.004366078571729222
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.03151807956629682, tolerance: 0.026676385475859515
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.027665299888980144, tolerance: 0.009427621284475373
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.01669498588049123, tolerance: 0.012365583416529083
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.01754481998762003, tolerance: 0.013697441663953586
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.03334513837114628, tolerance: 0.02729462325293282
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.03365569793905365, tolerance: 0.00869261280659528
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0055771339005659115, tolerance: 0.002886738328423205
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.013622133805469616, tolerance: 0.009451755830352949
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.045185710462646966, tolerance: 0.026808202208044824
  coefs, _, _, _ = cd_fast.enet_coordinate_descent_gram(
/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/sklearn/covariance/_graph_lasso.py:139: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.05455876383430791, tolerance: 0.025858377857091427

KeyboardInterrupt: