### Imports

In [1]:
import json
import numpy as np
import pandas as pd
import pingouin as pg
import seaborn as sn

print(pg.__version__) # 0.5.3
print(pd.__version__) # 2.0.3
print(np.__version__) # 1.24.3
print(sn.__version__) # 0.13.0

from utils_MS import *

# %load_ext autotime

0.5.3
2.2.2
1.26.4
0.13.2

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.6.1.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
# def run(exp):

### Parameters

In [3]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"]

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

data_variations = params["data_variations"]
print("Data variations:", data_variations)

apply_transformation = params["apply_transformation"]
print("Apply transformation:", apply_transformation)

threshold_corr = params["threshold_corr"]
print("Threshold corr:\t", threshold_corr)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

groups_id_no = params["groups_id_no"]
print("Groups id (no):\t", groups_id_no)

Exp:		 exp13
Data variations: ['none']
Apply transformation: False
Threshold corr:	 0.5
Groups id:	 ['AR', 'BC', 'BPH', 'CKD14', 'CKD5', 'CRS', 'ED', 'HC', 'LP', 'LPRD', 'LSNB', 'OSA', 'PCa', 'PD', 'PSG', 'RCC', 'SGB', 'health']
Subgroups id:	 {'AR': ['1', '2'], 'BC': ['1', '2'], 'BPH': ['1', '2'], 'CKD14': ['1', '2'], 'CKD5': ['1', '2'], 'CRS': ['1', '2'], 'ED': ['1', '2'], 'HC': ['1', '2'], 'LP': ['1', '2'], 'LPRD': ['1', '2'], 'LSNB': ['1', '2'], 'OSA': ['1', '2'], 'PCa': ['1', '2'], 'PD': ['1', '2'], 'PSG': ['1', '2'], 'RCC': ['1', '2'], 'SGB': ['1', '2'], 'health': ['1', '2']}
Groups id (no):	 ['Blank', 'QC', 'Std']

In [4]:
# Remove
# groups_id = ["OSA"]

### Load dataset

In [5]:
# read raw data
df_join_raw = pd.read_csv("experiments/input/{}_raw.csv".format(exp), index_col=0)
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_2.1,AR_2.2,AR_2.3,BC_1.1,...,SGB_1.3,SGB_2.1,SGB_2.2,SGB_2.3,health_1.1,health_1.2,health_1.3,health_2.1,health_2.2,health_2.3
0,1.0,69.99951,Unknown,0.067434,0.524123,-0.866715,0.407143,-0.406209,0.009354,0.310919,...,-1.070179,-0.944405,-1.070179,0.243862,0.213709,-0.178399,-0.301910,-0.167625,-0.189232,-0.178399
1,1.0,70.04025,Unknown,2.617854,3.259370,4.805380,3.076543,2.158068,2.745557,2.617659,...,2.074975,2.584545,2.074975,2.450491,2.697953,2.316318,2.421034,2.327056,2.305521,2.316318
2,1.0,70.04151,Unknown,1.088222,1.732480,1.674824,1.235654,0.836471,1.315006,1.484309,...,1.811865,1.974349,1.811865,0.854473,1.301124,1.092894,1.155690,1.098620,1.087138,1.092894
3,1.0,70.04908,Unknown,1.880941,2.504997,2.535388,1.880900,1.544437,2.014078,2.423544,...,0.706776,1.856629,0.706776,1.714065,2.358324,2.080343,1.900361,2.088160,2.072484,2.080343
4,1.0,70.06267,Unknown,1.659528,2.097781,2.593391,1.309826,1.316238,1.668676,2.019882,...,1.153538,1.286182,1.153538,1.050297,2.077151,1.793208,1.525407,1.801015,1.785358,1.793208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1.0,732.79951,Unknown,0.892378,3.759797,0.585675,1.039707,0.346959,0.665817,3.175910,...,0.195989,2.321735,0.195989,0.663823,1.091110,0.643823,0.487232,0.656200,0.631372,0.643823
5440,1.0,748.76437,Unknown,0.916754,1.620635,0.718502,1.221477,0.400736,1.054753,3.072149,...,0.297500,0.758849,0.297500,0.759580,1.002615,0.575805,0.695502,0.587540,0.564006,0.575805
5441,1.0,794.79590,Unknown,1.151250,2.041729,2.984408,1.105385,0.734599,1.412716,3.116183,...,3.053481,0.755768,3.053481,0.888324,1.291584,0.955433,1.061403,0.964905,0.945910,0.955433
5442,1.0,800.81295,Unknown,1.478938,2.421294,3.121924,1.400182,1.092336,1.761611,3.365476,...,3.010984,2.673166,3.010984,1.239034,1.662417,1.343335,1.420552,1.352313,1.334307,1.343335
5443,1.0,860.74167,Unknown,0.344954,0.992325,0.136437,0.612615,-0.373978,0.452590,2.979570,...,-0.261434,0.158394,-0.261434,-0.002186,0.861377,0.267264,0.172128,0.283610,0.250828,0.267264

In [6]:
# get metadata
df_join_raw_metadata = df_join_raw.iloc[:, :2]
df_join_raw_metadata

      Average Rt  Average Mz
0            1.0    69.99951
1            1.0    70.04025
2            1.0    70.04151
3            1.0    70.04908
4            1.0    70.06267
...          ...         ...
5439         1.0   732.79951
5440         1.0   748.76437
5441         1.0   794.79590
5442         1.0   800.81295
5443         1.0   860.74167

[5444 rows x 2 columns]

In [7]:
# filter by samples
columns_sample = [column for column in df_join_raw.columns if column.split("_")[0] not in groups_id_no]
df_join_raw_intensity = df_join_raw.loc[:, columns_sample]
df_join_raw_intensity = df_join_raw_intensity.iloc[:, 3:]
df_join_raw_intensity

,AR_1.1,AR_1.2,AR_1.3,AR_2.1,AR_2.2,AR_2.3,BC_1.1,BC_1.2,BC_1.3,BC_2.1,...,SGB_1.3,SGB_2.1,SGB_2.2,SGB_2.3,health_1.1,health_1.2,health_1.3,health_2.1,health_2.2,health_2.3
0,0.067434,0.524123,-0.866715,0.407143,-0.406209,0.009354,0.310919,0.384794,0.934567,-0.608435,...,-1.070179,-0.944405,-1.070179,0.243862,0.213709,-0.178399,-0.301910,-0.167625,-0.189232,-0.178399
1,2.617854,3.259370,4.805380,3.076543,2.158068,2.745557,2.617659,2.637159,1.976523,2.768182,...,2.074975,2.584545,2.074975,2.450491,2.697953,2.316318,2.421034,2.327056,2.305521,2.316318
2,1.088222,1.732480,1.674824,1.235654,0.836471,1.315006,1.484309,1.545443,2.006744,0.707240,...,1.811865,1.974349,1.811865,0.854473,1.301124,1.092894,1.155690,1.098620,1.087138,1.092894
3,1.880941,2.504997,2.535388,1.880900,1.544437,2.014078,2.423544,2.542821,2.784935,0.742334,...,0.706776,1.856629,0.706776,1.714065,2.358324,2.080343,1.900361,2.088160,2.072484,2.080343
4,1.659528,2.097781,2.593391,1.309826,1.316238,1.668676,2.019882,2.131893,2.546386,0.675713,...,1.153538,1.286182,1.153538,1.050297,2.077151,1.793208,1.525407,1.801015,1.785358,1.793208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,0.892378,3.759797,0.585675,1.039707,0.346959,0.665817,3.175910,2.323982,0.982068,3.403323,...,0.195989,2.321735,0.195989,0.663823,1.091110,0.643823,0.487232,0.656200,0.631372,0.643823
5440,0.916754,1.620635,0.718502,1.221477,0.400736,1.054753,3.072149,2.666972,0.952674,0.381335,...,0.297500,0.758849,0.297500,0.759580,1.002615,0.575805,0.695502,0.587540,0.564006,0.575805
5441,1.151250,2.041729,2.984408,1.105385,0.734599,1.412716,3.116183,0.845104,1.012288,3.827945,...,3.053481,0.755768,3.053481,0.888324,1.291584,0.955433,1.061403,0.964905,0.945910,0.955433
5442,1.478938,2.421294,3.121924,1.400182,1.092336,1.761611,3.365476,2.851395,1.291999,3.981077,...,3.010984,2.673166,3.010984,1.239034,1.662417,1.343335,1.420552,1.352313,1.334307,1.343335
5443,0.344954,0.992325,0.136437,0.612615,-0.373978,0.452590,2.979570,1.787069,0.703283,3.206725,...,-0.261434,0.158394,-0.261434,-0.002186,0.861377,0.267264,0.172128,0.283610,0.250828,0.267264

In [8]:
df_join_raw_intensity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5444 entries, 0 to 5443
Columns: 108 entries, AR_1.1 to health_2.3
dtypes: float64(108)
memory usage: 4.5 MB

In [9]:
check_dataset(df_join_raw_intensity)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 24312
Count zero:	 1
Count positive:	 563639
Count greater than 1:	 478820
Count less than -1:	 3371

### Generate graphs

In [10]:
# Transformation (log10)

if apply_transformation:
	df_join_raw_log = log10_global(df_join_raw_intensity)
else:
	df_join_raw_log = df_join_raw_intensity.copy()
df_join_raw_log.head()

,AR_1.1,AR_1.2,AR_1.3,AR_2.1,AR_2.2,AR_2.3,BC_1.1,BC_1.2,BC_1.3,BC_2.1,...,SGB_1.3,SGB_2.1,SGB_2.2,SGB_2.3,health_1.1,health_1.2,health_1.3,health_2.1,health_2.2,health_2.3
0,0.067434,0.524123,-0.866715,0.407143,-0.406209,0.009354,0.310919,0.384794,0.934567,-0.608435,...,-1.070179,-0.944405,-1.070179,0.243862,0.213709,-0.178399,-0.301910,-0.167625,-0.189232,-0.178399
1,2.617854,3.259370,4.805380,3.076543,2.158068,2.745557,2.617659,2.637159,1.976523,2.768182,...,2.074975,2.584545,2.074975,2.450491,2.697953,2.316318,2.421034,2.327056,2.305521,2.316318
2,1.088222,1.732480,1.674824,1.235654,0.836471,1.315006,1.484309,1.545443,2.006744,0.707240,...,1.811865,1.974349,1.811865,0.854473,1.301124,1.092894,1.155690,1.098620,1.087138,1.092894
3,1.880941,2.504997,2.535388,1.880900,1.544437,2.014078,2.423544,2.542821,2.784935,0.742334,...,0.706776,1.856629,0.706776,1.714065,2.358324,2.080343,1.900361,2.088160,2.072484,2.080343
4,1.659528,2.097781,2.593391,1.309826,1.316238,1.668676,2.019882,2.131893,2.546386,0.675713,...,1.153538,1.286182,1.153538,1.050297,2.077151,1.793208,1.525407,1.801015,1.785358,1.793208

In [11]:
check_dataset(df_join_raw_log)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 24312
Count zero:	 1
Count positive:	 563639
Count greater than 1:	 478820
Count less than -1:	 3371

In [12]:
# split graph in groups and subgroups

""" def split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id, by_group=False):
	list_df_groups_subgroups = []
	for group in groups_id:
		df_aux = df_join_raw_log.filter(like=group)
		list_aux = []
		
		if by_group:
			list_aux.append(df_aux)
		else:
			for subgroup in subgroups_id[group]:
				list_aux.append(df_aux.filter(like="{}_{}.".format(group, subgroup)))
		list_df_groups_subgroups.append(list_aux)
	return list_df_groups_subgroups """

dict_df_groups_subgroups = split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id)
dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

     AR_1.1    AR_1.2    AR_1.3
0  0.067434  0.524123 -0.866715
1  2.617854  3.259370  4.805380
2  1.088222  1.732480  1.674824
3  1.880941  2.504997  2.535388
4  1.659528  2.097781  2.593391

In [13]:
check_dataset(dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 686
Count zero:	 0
Count positive:	 15646
Count greater than 1:	 13389
Count less than -1:	 146

In [14]:
# No apply transpose for kneighbors_graph
# dict_groups_subgroups_t = dict_df_groups_subgroups.copy()

# Aplly Transpose
dict_groups_subgroups_t = transpose_global(dict_df_groups_subgroups)

dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,0.067434,2.617854,1.088222,1.880941,1.659528,1.767491,2.008215,2.092772,2.072683,2.185935,...,2.207700,1.753761,0.217247,1.533782,1.191297,0.892378,0.916754,1.151250,1.478938,0.344954
1,0.524123,3.259370,1.732480,2.504997,2.097781,2.185932,2.417997,2.472316,2.501865,2.492657,...,2.999874,2.300622,0.948713,2.215614,1.527121,3.759797,1.620635,2.041729,2.421294,0.992325
2,-0.866715,4.805380,1.674824,2.535388,2.593391,2.632587,2.750429,2.788159,2.777456,2.834100,...,3.664453,3.152539,2.012696,2.671736,2.787052,0.585675,0.718502,2.984408,3.121924,0.136437

In [15]:
check_dataset(dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 686
Count zero:	 0
Count positive:	 15646
Count greater than 1:	 13389
Count less than -1:	 146

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import LedoitWolf
from sklearn.neighbors import kneighbors_graph

def correlation_ledoitwolf_global(exp, dict_groups_subgroups_t):
	dict_groups_subgroups_t_corr = {}
	for group_id, dict_groups in dict_groups_subgroups_t.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			print(group_id, subgroup_id, df_subgroup.shape)
			
			""" import numpy as np
			cov = np.cov(df_subgroup.values, rowvar=False)
			cond = np.linalg.cond(cov)
			print("Condition number:", cond, cond > 1e8) # ill-conditioned if > 1e8 (True, instable) """

			scaler = StandardScaler()
			df_subgroup_scaled = scaler.fit_transform(df_subgroup)
			lw = LedoitWolf()
			lw.fit(df_subgroup_scaled)

			# Matriz de covarianza regularizada
			cov = lw.covariance_
			std = np.sqrt(np.diag(cov))
			corr = cov / np.outer(std, std)
			matrix = pd.DataFrame(corr)
		
			dict_aux[subgroup_id] = matrix
			
			matrix.to_csv("experiments/output/{}/correlations/{}_{}.csv".format(exp, group_id, subgroup_id), index=True)
		dict_groups_subgroups_t_corr[group_id] = dict_aux
	return dict_groups_subgroups_t_corr

def correlation_kneighbors_graph_global(exp, dict_groups_subgroups_t):
	dict_groups_subgroups_t_corr = {}
	for group_id, dict_groups in dict_groups_subgroups_t.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			print(group_id, subgroup_id, df_subgroup.shape)
			
			""" import numpy as np
			cov = np.cov(df_subgroup.values, rowvar=False)
			cond = np.linalg.cond(cov)
			print("Condition number:", cond, cond > 1e8) # ill-conditioned if > 1e8 (True, instable) """
			
			k = 10
			scaler = StandardScaler()
			df_subgroup_scaled = scaler.fit_transform(df_subgroup)
			A = kneighbors_graph(
				df_subgroup_scaled, # X, X_scaled
				n_neighbors=k,
				metric="euclidean", # "cosine",
				mode="distance",
				include_self=True
			)
			matrix = pd.DataFrame(A.toarray())
		
			dict_aux[subgroup_id] = matrix
			
			matrix.to_csv("experiments/output/{}/correlations/{}_{}.csv".format(exp, group_id, subgroup_id), index=True)
		dict_groups_subgroups_t_corr[group_id] = dict_aux
	return dict_groups_subgroups_t_corr

In [17]:
# Correlation matrix (partial correlation)

# Option 1
# dict_groups_subgroups_t_corr = correlation_global(exp, dict_groups_subgroups_t)

# Option 2
dict_groups_subgroups_t_corr = correlation_ledoitwolf_global(exp, dict_groups_subgroups_t)

# Option 3
# dict_groups_subgroups_t_corr = correlation_kneighbors_graph_global(exp, dict_groups_subgroups_t)

dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

AR 1 (3, 5444)
AR 2 (3, 5444)
BC 1 (3, 5444)
BC 2 (3, 5444)
BPH 1 (3, 5444)
BPH 2 (3, 5444)
CKD14 1 (3, 5444)
CKD14 2 (3, 5444)
CKD5 1 (3, 5444)
CKD5 2 (3, 5444)
CRS 1 (3, 5444)
CRS 2 (3, 5444)
ED 1 (3, 5444)
ED 2 (3, 5444)
HC 1 (3, 5444)
HC 2 (3, 5444)
LP 1 (3, 5444)
LP 2 (3, 5444)
LPRD 1 (3, 5444)
LPRD 2 (3, 5444)
LSNB 1 (3, 5444)
LSNB 2 (3, 5444)
OSA 1 (3, 5444)
OSA 2 (3, 5444)
PCa 1 (3, 5444)
PCa 2 (3, 5444)
PD 1 (3, 5444)
PD 2 (3, 5444)
PSG 1 (3, 5444)
PSG 2 (3, 5444)
RCC 1 (3, 5444)
RCC 2 (3, 5444)
SGB 1 (3, 5444)
SGB 2 (3, 5444)
health 1 (3, 5444)
health 2 (3, 5444)

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,1.000000,-0.581910,-0.081671,-0.167403,-0.488842,-0.480137,-0.437025,-0.441106,-0.399423,-0.486483,...,-0.442403,-0.533492,-0.524522,-0.405987,-0.616070,0.575920,0.623235,-0.478874,-0.422993,0.631774
1,-0.581910,1.000000,0.476864,0.537968,0.699493,0.697054,0.682853,0.684338,0.667944,0.698847,...,0.684804,0.709319,0.707739,0.670700,0.710778,-0.225843,-0.307141,0.696687,0.677544,-0.323237
2,-0.081671,0.476864,1.000000,0.708247,0.572343,0.579346,0.610385,0.607687,0.633125,0.574267,...,0.606820,0.531818,0.540636,0.629418,0.428181,0.352602,0.273869,0.580339,0.619307,0.257216
3,-0.167403,0.537968,0.708247,1.000000,0.619985,0.625770,0.650857,0.648717,0.668498,0.621579,...,0.648028,0.585805,0.593334,0.665675,0.494519,0.274417,0.191574,0.626587,0.657867,0.174232
4,-0.488842,0.699493,0.572343,0.619985,1.000000,0.713461,0.710306,0.710781,0.704376,0.713553,...,0.710924,0.710684,0.711758,0.705604,0.684330,-0.087652,-0.173830,0.713431,0.708412,-0.191174

In [18]:
# Check correlation matrices

dict_groups_subgroups_t_corr

{'AR': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.581910 -0.081671 -0.167403 -0.488842 -0.480137 -0.437025
  1    -0.581910  1.000000  0.476864  0.537968  0.699493  0.697054  0.682853
  2    -0.081671  0.476864  1.000000  0.708247  0.572343  0.579346  0.610385
  3    -0.167403  0.537968  0.708247  1.000000  0.619985  0.625770  0.650857
  4    -0.488842  0.699493  0.572343  0.619985  1.000000  0.713461  0.710306
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.575920 -0.225843  0.352602  0.274417 -0.087652 -0.075872 -0.019697
  5440  0.623235 -0.307141  0.273869  0.191574 -0.173830 -0.162305 -0.107016
  5441 -0.478874  0.696687  0.580339  0.626587  0.713431  0.713558  0.711471
  5442 -0.422993  0.677544  0.619307  0.657867  0.708412  0.709736  0.713343
  5443  0.631774 -0.323237  0.257216  0.174232 -0.191174 -0.179724 -0.124720

            7         8         9     ...      5434      5435      5436  \
  0    -0.441106 -0.399423 -0.486483  ... -0.442403 -0.533492 -0.524522
  1     0.684338  0.667944  0.698847  ...  0.684804  0.709319  0.707739
  2     0.607687  0.633125  0.574267  ...  0.606820  0.531818  0.540636
  3     0.648717  0.668498  0.621579  ...  0.648028  0.585805  0.593334
  4     0.710781  0.704376  0.713553  ...  0.710924  0.710684  0.711758
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.024872  0.026724 -0.084445  ... -0.026522 -0.150812 -0.137720
  5440 -0.112133 -0.060918 -0.170694  ... -0.113763 -0.235198 -0.222537
  5441  0.711848  0.706418  0.713485  ...  0.711961  0.709339  0.710667
  5442  0.713197  0.712977  0.708793  ...  0.713142  0.697885  0.700548
  5443 -0.129815 -0.078773 -0.188059  ... -0.131437 -0.252062 -0.239512

            5437      5438      5439      5440      5441      5442      5443
  0    -0.405987 -0.616070  0.575920  0.623235 -0.478874 -0.422993  0.631774
  1     0.670700  0.710778 -0.225843 -0.307141  0.696687  0.677544 -0.323237
  2     0.629418  0.428181  0.352602  0.273869  0.580339  0.619307  0.257216
  3     0.665675  0.494519  0.274417  0.191574  0.626587  0.657867  0.174232
  4     0.705604  0.684330 -0.087652 -0.173830  0.713431  0.708412 -0.191174
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.018776 -0.284670  1.000000  0.708175 -0.074177 -0.002115  0.705751
  5440 -0.068836 -0.362758  0.708175  1.000000 -0.160645 -0.089600  0.713334
  5441  0.707496  0.680364 -0.074177 -0.160645  1.000000  0.709911 -0.178074
  5442  0.713254  0.655158 -0.002115 -0.089600  0.709911  1.000000 -0.107370
  5443 -0.086671 -0.378092  0.705751  0.713334 -0.178074 -0.107370  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000  0.684059  0.543626  0.486892 -0.002073 -0.069874 -0.120560
  1     0.684059  1.000000  0.600454  0.553672  0.099407  0.031820 -0.019351
  2     0.543626  0.600454  1.000000  0.686285  0.425804  0.370319  0.326117
  3     0.486892  0.553672  0.686285  1.000000  0.489626  0.439378  0.398685
  4    -0.002073  0.099407  0.425804  0.489626  1.000000  0.688209  0.681310
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.690361  0.676964  0.517729  0.457373 -0.042466 -0.109945 -0.160132
  5440  0.656952  0.681529  0.649925  0.615907  0.214001  0.148486  0.098134
  5441  0.384855  0.464986  0.657666  0.678977  0.573401  0.532731  0.498665
  5442  0.325473  0.411469  0.632992  0.662451  0.609183  0.574153  0.544077
  5443  0.647385  0.676053  0.659204  0.628473  0.241211  0.176496  0.126567

            7         8         9     ...      5434      5435      5436  \
  0    -0.194310 -0.260265  0.691542  ...  0.099061  0.491936  0.395704
  1    -0.094837 -0.163451  0.684052  ...  0.198400  0.557920  0.474629
  2     0.257467  0.191412  0.543598  ...  0.500900  0.687127  0.661610
  3     0.334496  0.271736  0.486859  ...  0.555768  0.691505  0.681348
  4     0.664261  0.641474 -0.002119  ...  0.684110  0.484558  0.565952
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.232747 -0.297247  0.690364  ...  0.058912  0.462704  0.361898
  5440  0.022680 -0.047155  0.656938  ...  0.307850  0.619120  0.553032
  5441  0.443274  0.387472  0.384817  ...  0.623761  0.677586  0.691417
  5442  0.494129  0.442807  0.325432  ...  0.650492  0.660367  0.686637
  5443  0.051455 -0.018371  0.647368  ...  0.333381  0.631418  0.569849

            5437      5438      5439      5440      5441      5442      5443
  0     0.406371  0.672441  0.690361  0.656952  0.384855  0.325473  0.647385
  1     0.484066  0.688846  0.676964  0.681529  0.464986  0.411469  0.676053
  2     0.665301  0.628376  0.517729  0.649925  0.657666  0.632992  0.659204
  3     0.683465  0.588066  0.457373  0.615907  0.678977  0.662451  0.628473
  4     0.558327  0.159393 -0.042466  0.214001  0.573401  0.609183  0.241211
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.372990  0.661864  1.000000  0.643215  0.350635  0.289274  0.632075
  5440  0.560794  0.689216  0.643215  1.000000  0.545042  0.499750  0.690941
  5441  0.691044  0.508330  0.350635  0.545042  1.000000  0.688076  0.562301
  5442  0.684958  0.458898  0.289274  0.499750  0.688076  1.000000  0.519229
  5443  0.577165  0.686257  0.632075  0.690941  0.562301  0.519229  1.000000

  [5444 rows x 5444 columns]},
 'BC': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.687494  0.693764  0.676860  0.690656  0.681982 -0.665251
  1    -0.687494  1.000000 -0.687623 -0.650323 -0.675612 -0.658738  0.685645
  2     0.693764 -0.687623  1.000000  0.676648  0.690564  0.681804 -0.665524
  3     0.676860 -0.650323  0.676648  1.000000  0.688222  0.693299 -0.605852
  4     0.690656 -0.675612  0.690564  0.688222  1.000000  0.690966 -0.643654
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.665439  0.633102 -0.665165 -0.692275 -0.681012 -0.690146  0.582414
  5440 -0.691945  0.678956 -0.691875 -0.686101 -0.693593 -0.689408  0.649261
  5441 -0.372110  0.290199 -0.371295 -0.491511 -0.425814 -0.473246  0.190677
  5442 -0.687753  0.669310 -0.687625 -0.690990 -0.693289 -0.692797  0.633627
  5443 -0.626929  0.581407 -0.626515 -0.676839 -0.652215 -0.670805  0.516862

            7         8         9     ...      5434      5435      5436  \
  0     0.684402  0.682516  0.680078  ... -0.678159 -0.688664  0.692653
  1    -0.662978 -0.659656 -0.655536  ...  0.652401  0.671175 -0.681124
  2     0.684243  0.682343  0.679887  ... -0.677955 -0.688547  0.692597
  3     0.692649  0.693185  0.693593  ... -0.693738 -0.690308  0.684391
  4     0.692077  0.691224  0.689998  ... -0.688957 -0.693519  0.693262
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.688585 -0.689840 -0.691094  ...  0.691854  0.684295 -0.675478
  5440 -0.690828 -0.689731 -0.688219  ...  0.686970  0.692935 -0.693678
  5441 -0.462959 -0.471088 -0.480500  ...  0.487232  0.440243 -0.404654
  5442 -0.693393 -0.692946 -0.692198  ...  0.691504  0.693727 -0.691808
  5443 -0.667114 -0.670048 -0.673284  ...  0.675488  0.658279 -0.642740

            5437      5438      5439      5440      5441      5442      5443
  0    -0.301100 -0.690343 -0.665439 -0.691945 -0.372110 -0.687753 -0.626929
  1     0.214533  0.674871  0.633102  0.678956  0.290199  0.669310  0.581407
  2    -0.300231 -0.690246 -0.665165 -0.691875 -0.371295 -0.687625 -0.626515
  3    -0.430895 -0.688621 -0.692275 -0.686101 -0.491511 -0.690990 -0.676839
  4    -0.358857 -0.693757 -0.681012 -0.693593 -0.425814 -0.693289 -0.652215
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.465580  0.681621  1.000000  0.677894  0.522521  0.685448  0.685361
  5440  0.345544  0.693513  0.677894  1.000000  0.413509  0.692545  0.646787
  5441  0.689007  0.428359  0.522521  0.413509  1.000000  0.445803  0.587012
  5442  0.380596  0.693401  0.685448  0.692545  0.445803  1.000000  0.660525
  5443  0.539754  0.653309  0.685361  0.646787  0.587012  0.660525  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000  0.621639  0.673180  0.673161  0.673180  0.673181  0.673181
  1     0.621639  1.000000  0.621251  0.619642  0.621125  0.621645  0.621514
  2     0.673180  0.621251  1.000000  0.673168  0.673181  0.673180  0.673181
  3     0.673161  0.619642  0.673168  1.000000  0.673170  0.673161  0.673164
  4     0.673180  0.621125  0.673181  0.673170  1.000000  0.673180  0.673180
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.670990 -0.598787 -0.671070 -0.671386 -0.671096 -0.670988 -0.671016
  5440  0.450478  0.607957  0.449726  0.446633  0.449483  0.450489  0.450236
  5441 -0.343696 -0.095251 -0.344564 -0.348119 -0.344845 -0.343682 -0.343976
  5442 -0.348433 -0.100715 -0.349297 -0.352834 -0.349576 -0.348420 -0.348712
  5443 -0.317246 -0.065105 -0.318137 -0.321784 -0.318424 -0.317232 -0.317533

            7         8         9     ...      5434      5435      5436  \
  0     0.673181  0.673180  0.673180  ... -0.345182 -0.301094 -0.670864
  1     0.621307  0.621247  0.621164  ... -0.096963 -0.046984 -0.598081
  2     0.673181  0.673181  0.673181  ... -0.346049 -0.301997 -0.670947
  3     0.673168  0.673168  0.673170  ... -0.349598 -0.305696 -0.671271
  4     0.673181  0.673181  0.673181  ... -0.346329 -0.302289 -0.670973
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.671059 -0.671071 -0.671088  ...  0.390655  0.348657  0.673179
  5440  0.449835  0.449719  0.449559  ...  0.198486  0.245932 -0.407454
  5441 -0.344439 -0.344573 -0.344757  ...  0.673179  0.671431  0.390501
  5442 -0.349173 -0.349306 -0.349489  ...  0.673170  0.671011  0.394987
  5443 -0.318008 -0.318145 -0.318334  ...  0.672416  0.672936  0.365378

            5437      5438      5439      5440      5441      5442      5443
  0    -0.207638 -0.323234 -0.670990  0.450478 -0.343696 -0.348433 -0.317246
  1    -0.437481 -0.071877 -0.598787  0.607957 -0.095251 -0.100715 -0.065105
  2    -0.206676 -0.324119 -0.671070  0.449726 -0.344564 -0.349297 -0.318137
  3    -0.202727 -0.327746 -0.671386  0.446633 -0.348119 -0.352834 -0.321784
  4    -0.206366 -0.324405 -0.671096  0.449483 -0.344845 -0.349576 -0.318424
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.155333  0.369791  1.000000 -0.408679  0.389245  0.393738  0.364083
  5440 -0.614799  0.222503 -0.408679  1.000000  0.200138  0.194858  0.228916
  5441 -0.444599  0.672769  0.389245  0.200138  1.000000  0.673159  0.672496
  5442 -0.440437  0.672553  0.393738  0.194858  0.673159  1.000000  0.672225
  5443 -0.466939  0.673147  0.364083  0.228916  0.672496  0.672225  1.000000

  [5444 rows x 5444 columns]},
 'BPH': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.434504  0.668223  0.668189  0.668241  0.668240  0.668240
  1    -0.434504  1.000000 -0.438203 -0.440772 -0.434620 -0.434121 -0.435191
  2     0.668223 -0.438203  1.000000  0.668232  0.668224  0.668219  0.668229
  3     0.668189 -0.440772  0.668232  1.000000  0.668191  0.668183  0.668200
  4     0.668241 -0.434620  0.668224  0.668191  1.000000  0.668240  0.668240
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.665480 -0.386607  0.665019  0.664675  0.665466  0.665525  0.665397
  5440  0.666742 -0.399546  0.666397  0.666135  0.666732  0.666776  0.666681
  5441  0.666807 -0.400330  0.666469  0.666212  0.666797  0.666840  0.666747
  5442  0.666872 -0.401137  0.666542  0.666290  0.666862  0.666904  0.666813
  5443  0.667568 -0.411286  0.667331  0.667144  0.667561  0.667590  0.667526

            7         8         9     ...      5434      5435      5436  \
  0     0.668241  0.668241  0.668241  ... -0.667979  0.665834  0.667343
  1    -0.434631 -0.434528 -0.434815  ...  0.448541 -0.389894 -0.407612
  2     0.668224  0.668223  0.668226  ... -0.668098  0.665403  0.667072
  3     0.668191  0.668190  0.668194  ... -0.668160  0.665080  0.666862
  4     0.668241  0.668241  0.668241  ... -0.667983  0.665821  0.667335
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.665465  0.665477  0.665442  ... -0.663521  0.668228  0.667730
  5440  0.666731  0.666740  0.666714  ... -0.665229  0.668134  0.668164
  5441  0.666796  0.666805  0.666780  ... -0.665321  0.668115  0.668178
  5442  0.666861  0.666870  0.666846  ... -0.665415  0.668095  0.668191
  5443  0.667560  0.667566  0.667549  ... -0.666467  0.667706  0.668224

            5437      5438      5439      5440      5441      5442      5443
  0    -0.127463 -0.181974  0.665480  0.666742  0.666807  0.666872  0.667568
  1    -0.415493  0.606829 -0.386607 -0.399546 -0.400330 -0.401137 -0.411286
  2    -0.122665 -0.186669  0.665019  0.666397  0.666469  0.666542  0.667331
  3    -0.119311 -0.189940  0.664675  0.666135  0.666212  0.666290  0.667144
  4    -0.127313 -0.182121  0.665466  0.666732  0.666797  0.666862  0.667561
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.186503 -0.122835  1.000000  0.668049  0.668025  0.667999  0.667532
  5440 -0.171085 -0.138526  0.668049  1.000000  0.668240  0.668238  0.668077
  5441 -0.170139 -0.139484  0.668025  0.668240  1.000000  0.668240  0.668098
  5442 -0.169164 -0.140469  0.667999  0.668238  0.668240  1.000000  0.668118
  5443 -0.156768 -0.152940  0.667532  0.668077  0.668098  0.668118  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000  0.594238  0.674127  0.674118  0.674092  0.674068  0.674090
  1     0.594238  1.000000  0.593672  0.595913  0.590909  0.589953  0.590815
  2     0.674127  0.593672  1.000000  0.674111  0.674103  0.674083  0.674101
  3     0.674118  0.595913  0.674111  1.000000  0.674045  0.674011  0.674042
  4     0.674092  0.590909  0.674103  0.674045  1.000000  0.674125  0.674128
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.133709 -0.194136  0.134880  0.130213  0.140544  0.142481  0.140735
  5440  0.082689 -0.243030  0.083875  0.079150  0.089613  0.091576  0.089806
  5441  0.578981  0.347318  0.579592  0.577147  0.582526  0.583520  0.582624
  5442  0.574989  0.340679  0.575612  0.573120  0.578603  0.579617  0.578703
  5443  0.100904 -0.225791  0.102085  0.097378  0.107801  0.109756  0.107994

            7         8         9     ...      5434      5435      5436  \
  0     0.674103  0.674109  0.674113  ...  0.184230  0.174084  0.674127
  1     0.591489  0.591825  0.592090  ... -0.143809 -0.154073  0.593653
  2     0.674112  0.674117  0.674120  ...  0.185379  0.175238  0.674128
  3     0.674063  0.674072  0.674079  ...  0.180798  0.170638  0.674111
  4     0.674127  0.674125  0.674123  ...  0.190935  0.180819  0.674103
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.139364  0.138678  0.138135  ...  0.672123  0.672852  0.134920
  5440  0.088417  0.087722  0.087172  ...  0.666167  0.667698  0.083915
  5441  0.581918  0.581564  0.581283  ...  0.490379  0.483098  0.579613
  5442  0.577983  0.577622  0.577335  ...  0.495644  0.488450  0.575633
  5443  0.106610  0.105918  0.105370  ...  0.668736  0.669983  0.102126

            5437      5438      5439      5440      5441      5442      5443
  0    -0.542410  0.193843  0.133709  0.082689  0.578981  0.574989  0.100904
  1    -0.667151 -0.134009 -0.194136 -0.243030  0.347318  0.340679 -0.225791
  2    -0.541700  0.194988  0.134880  0.083875  0.579592  0.575612  0.102085
  3    -0.544520  0.190426  0.130213  0.079150  0.577147  0.573120  0.097378
  4    -0.538236  0.200519  0.140544  0.089613  0.582526  0.578603  0.107801
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.284763  0.671277  1.000000  0.672146  0.453272  0.458957  0.673305
  5440  0.330744  0.664558  0.672146  1.000000  0.413706  0.419774  0.673877
  5441 -0.260817  0.497197  0.453272  0.413706  1.000000  0.674084  0.428068
  5442 -0.253681  0.502377  0.458957  0.419774  0.674084  1.000000  0.434003
  5443  0.314601  0.667398  0.673305  0.673877  0.428068  0.434003  1.000000

  [5444 rows x 5444 columns]},
 'CKD14': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.129428  0.675622  0.672784  0.672788  0.671847  0.670549
  1    -0.129428  1.000000 -0.123045 -0.067836 -0.067870 -0.058411 -0.047091
  2     0.675622 -0.123045  1.000000  0.673351  0.673354  0.672505  0.671315
  3     0.672784 -0.067836  0.673351  1.000000  0.675653  0.675587  0.675332
  4     0.672788 -0.067870  0.673354  0.675653  1.000000  0.675586  0.675331
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.673045 -0.187138  0.672444  0.664728  0.664734  0.662968  0.660684
  5440  0.673817 -0.080225  0.674265  0.675538  0.675539  0.675297  0.674833
  5441 -0.369273  0.626073 -0.363815 -0.315622 -0.315652 -0.307221 -0.297065
  5442 -0.377090  0.622487 -0.371681 -0.323883 -0.323912 -0.315543 -0.305458
  5443 -0.236345  0.666520 -0.230247 -0.177077 -0.177110 -0.167924 -0.156902

            7         8         9     ...      5434      5435      5436  \
  0     0.672356  0.672113  0.671751  ... -0.412371 -0.391094  0.675652
  1    -0.063367 -0.060956 -0.057515  ...  0.604299  0.615671 -0.128354
  2     0.672966  0.672746  0.672417  ... -0.407205 -0.385777  0.675631
  3     0.675638  0.675618  0.675573  ... -0.361353 -0.338717  0.672884
  4     0.675638  0.675617  0.675573  ... -0.361382 -0.338747  0.672887
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.663909  0.663456  0.662793  ... -0.457759 -0.437946  0.672948
  5440  0.675440  0.675375  0.675267  ... -0.371822 -0.349443  0.673897
  5441 -0.311644 -0.309494 -0.306420  ...  0.673586  0.675137 -0.368357
  5442 -0.319934 -0.317800 -0.314747  ...  0.674254  0.675439 -0.376182
  5443 -0.172739 -0.170397 -0.167052  ...  0.645652  0.652954 -0.235320

            5437      5438      5439      5440      5441      5442      5443
  0     0.667075 -0.299300  0.673045  0.673817 -0.369273 -0.377090 -0.236345
  1    -0.022448  0.651861 -0.187138 -0.080225  0.626073  0.622487  0.666520
  2     0.668076 -0.293461  0.672444  0.674265 -0.363815 -0.371681 -0.230247
  3     0.674122 -0.242271  0.664728  0.675538 -0.315622 -0.323883 -0.177077
  4     0.674119 -0.242302  0.664734  0.675539 -0.315652 -0.323912 -0.177110
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.655079 -0.351316  1.000000  0.666847 -0.417514 -0.424846 -0.290993
  5440  0.673168 -0.253863  0.666847  1.000000 -0.326588 -0.334765 -0.189074
  5441 -0.274708  0.670850 -0.417514 -0.326588  1.000000  0.675588  0.659239
  5442 -0.283248  0.669669 -0.424846 -0.334765  0.675588  1.000000  0.657122
  5443 -0.132800  0.672172 -0.290993 -0.189074  0.659239  0.657122  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000 -0.662760  0.669536  0.646994  0.656836  0.650166  0.649036
  1    -0.662760  1.000000 -0.663441 -0.664918 -0.668627 -0.666299 -0.665823
  2     0.669536 -0.663441  1.000000  0.648243  0.657772  0.651324  0.650227
  3     0.646994 -0.664918  0.648243  1.000000  0.668136  0.669432  0.669505
  4     0.656836 -0.668627  0.657772  0.668136  1.000000  0.668846  0.668615
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.525508  0.461216 -0.522445 -0.401005 -0.435040 -0.411168 -0.407478

In [19]:
check_dataset(dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][1]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 11196088
Count zero:	 1152
Count positive:	 18439896
Count greater than 1:	 0
Count less than -1:	 0

In [ ]:
def build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=0.3):
	dict_groups_subgroups_t_corr_g = {}
	for group_id, dict_groups in dict_groups_subgroups_t_corr.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			# Percentil Correlaciones conservadas 	Densidad
			# 50	    50 %	                    Muy densa
            # 75	    25 %	                    Densa
            # 90	    10 %	                    Moderadamente dispersa
            # 95	    5 %	                        Dispersa
            # 99	    1 %	                        Muy dispersa
			threshold = np.percentile(np.abs(df_subgroup), 90)
			
			df_weighted_edges = (df_subgroup.where(np.triu(np.ones(df_subgroup.shape), k=1).astype(bool)).stack())
			df_weighted_edges = df_weighted_edges.dropna().to_frame()
			df_weighted_edges.reset_index(inplace=True)
			df_weighted_edges.columns = ["source", "target", "weight"]
			df_weighted_edges = df_weighted_edges[df_weighted_edges["weight"].abs() >= threshold]
			df_weighted_edges["subgroup"] = [subgroup_id] * len(df_weighted_edges)
			dict_aux[subgroup_id] = df_weighted_edges
			
			df_weighted_edges.to_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight"])
			# print(groups_id[i], subgroups_id[groups_id[i]][j], G.number_of_nodes(), G.number_of_edges())
			# nx.write_gexf(G, "experiments/output/{}/preprocessing/graphs/graphs_{}_{}.gexf".format(exp, groups_id[i], subgroups_id[groups_id[i]][j]))
		dict_groups_subgroups_t_corr_g[group_id] = dict_aux
	return dict_groups_subgroups_t_corr_g

In [21]:
# Build graph (corpus graphs)

# dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

    source  target    weight subgroup
15       0      16  0.710738        1
35       0      36  0.710639        1
44       0      45  0.711307        1
48       0      49  0.713266        1
74       0      75  0.709949        1

In [22]:
def create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups, df_join_raw_metadata):	
	for group_id in tqdm(groups_id):
		for subgroup_id in tqdm(subgroups_id[group_id]):
			df_weighted_edges = pd.read_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id))
			# print(df_weighted_edges)
			G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight", "subgroup"])
			dict_id_idx = dict(zip(list(G.nodes()), range(G.number_of_nodes())))
			G = nx.relabel_nodes(G, dict_id_idx)

			df_nodes = dict_df_groups_subgroups[group_id][subgroup_id].loc[list(dict_id_idx.keys())] # A_1.1, A_1.2, A_1.3
			# from IPython.display import display
			# display(df_nodes)

			# nodes, with node features
			metadata = df_join_raw_metadata.loc[df_nodes.index] # Average Rt, Average Mz
			# intensity = df_join_raw_log.loc[df_nodes.index] # A_1.1, A_1.2, A_1.3, A_2.1, ...

			""" e = 1e-8
			mz = metadata.iloc[:, 1].values
			rt = metadata.iloc[:, 0].values
			intensity_mean = df_nodes.mean(axis=1).values
			intensity_std = df_nodes.std(axis=1).values
			intensity_cv = intensity_std / intensity_mean
			presence_ratio = (df_nodes > 0).mean(axis=1)

			mz_log = np.log10(mz + e)
			# intensity_mean_log = np.log10(intensity_mean + e)
			
			# mz_z = (mz_log - mz_log.mean()) / mz_log.std() # z-score
			rt_z = (rt - rt.mean()) / rt.std() # z-score
			# intensity_mean_z = (intensity_mean_log - intensity_mean_log.mean()) / intensity_mean_log.std() # z-score

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": mz_log,
				"rt": rt_z,
				"intensity_mean": intensity_mean,
				"intensity_std": intensity_std,
				"intensity_cv": intensity_cv,
				"presence_ratio": presence_ratio
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			# df_node_features.insert(0, "idx", list(dict_id_idx.values()))
			# df_node_features.insert(1, "id", list(dict_id_idx.keys()))
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features) """

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": metadata.iloc[:, 1].values,
				"rt": metadata.iloc[:, 0].values,
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features)

			# edges
			edges = list(G.edges())
			df_edges = pd.DataFrame(edges, columns=["source", "target"])
			df_edges["weight"] = [G.get_edge_data(*edge)["weight"] for edge in edges]
			df_edges["subgroup"] = [G.get_edge_data(*edge)["subgroup"] for edge in edges]
			df_edges.to_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)

In [23]:
# create dataset - nodes/edge data for PyTorch Geometric/DGL framework

# IMPORTANT
dict_df_groups_subgroups_ = split_groups_subgroups(df_join_raw_intensity, groups_id, subgroups_id) # Important (intesities without Log)

for data_variation in data_variations:
	if data_variation == "none":
		create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, df_join_raw_metadata)
	else:
		# dynamic graph to static graph
		create_graph_data_directed_variation(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, data_variation)

100%|██████████| 2/2 [00:13<00:00,  6.66s/it]
100%|██████████| 2/2 [00:14<00:00,  7.34s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.45s/it]]
100%|██████████| 2/2 [00:13<00:00,  6.59s/it]]
100%|██████████| 2/2 [00:16<00:00,  8.31s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.48s/it]]
100%|██████████| 2/2 [00:16<00:00,  8.31s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.44s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.34s/it]]
100%|██████████| 2/2 [00:16<00:00,  8.22s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.32s/it]t]
100%|██████████| 2/2 [00:16<00:00,  8.30s/it]t]
100%|██████████| 2/2 [00:13<00:00,  6.52s/it]t]
100%|██████████| 2/2 [00:13<00:00,  6.56s/it]t]
100%|██████████| 2/2 [00:17<00:00,  8.52s/it]t]
100%|██████████| 2/2 [00:12<00:00,  6.47s/it]t]
100%|██████████| 2/2 [00:16<00:00,  8.42s/it]t]
100%|██████████| 2/2 [00:12<00:00,  6.47s/it]t]
100%|██████████| 18/18 [04:17<00:00, 14.30s/it]

In [24]:
# details
list_details = []
	
for group_id in groups_id:
	subgroups_id_ = []
	for data_variation in data_variations:
		if data_variation == "none":
			subgroups_id_ += subgroups_id[group_id]
		else:
			subgroups_id_ += [data_variation]
	# print(subgroups)
	
	for subgroup_id_ in subgroups_id_:
		try:
			df_edges = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id_))

			G = nx.from_pandas_edgelist(df_edges.iloc[:, [0, 1]])
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), nx.density(G), np.nan, nx.is_connected(G)])
		except:
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), np.nan, np.nan, np.nan])

df_details = pd.DataFrame(list_details, columns=["Group", "Subgroup", "Num. nodes", "Num. edges", "Density", "Diameter", "Is connected"])
df_details.to_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp), index=False)

df_details = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp))
df_details

     Group  Subgroup  Num. nodes  Num. edges   Density  Diameter  Is connected
0       AR         1        5444     1479135  0.099835       NaN          True
1       AR         2        5444     1479135  0.099835       NaN          True
2       BC         1        5444     1479135  0.099835       NaN          True
3       BC         2        5444     1479135  0.099835       NaN          True
4      BPH         1        5444     1479135  0.099835       NaN          True
5      BPH         2        5444     1479135  0.099835       NaN          True
6    CKD14         1        5444     1479135  0.099835       NaN          True
7    CKD14         2        5444     1479135  0.099835       NaN          True
8     CKD5         1        5444     1479135  0.099835       NaN          True
9     CKD5         2        5444     1479135  0.099835       NaN          True
10     CRS         1        5444     1479135  0.099835       NaN         False
11     CRS         2        5444     1479135  0.099835       NaN          True
12      ED         1        5444     1479135  0.099835       NaN          True
13      ED         2        5444     1479135  0.099835       NaN          True
14      HC         1        5444     1479135  0.099835       NaN          True
15      HC         2        5444     1479135  0.099835       NaN          True
16      LP         1        5444     1479135  0.099835       NaN          True
17      LP         2        5444     1479135  0.099835       NaN          True
18    LPRD         1        5444     1479135  0.099835       NaN          True
19    LPRD         2        5444     1479135  0.099835       NaN          True
20    LSNB         1        5444     1479135  0.099835       NaN          True
21    LSNB         2        5444     1479135  0.099835       NaN          True
22     OSA         1        5444     1479135  0.099835       NaN          True
23     OSA         2        5444     1479135  0.099835       NaN          True
24     PCa         1        5444     1479135  0.099835       NaN          True
25     PCa         2        5444     1479135  0.099835       NaN          True
26      PD         1        5444     1479135  0.099835       NaN          True
27      PD         2        5444     1479135  0.099835       NaN          True
28     PSG         1        5444     1479135  0.099835       NaN          True
29     PSG         2        5444     1479135  0.099835       NaN          True
30     RCC         1        5444     1479135  0.099835       NaN          True
31     RCC         2        5444     1479135  0.099835       NaN          True
32     SGB         1        5444     1479135  0.099835       NaN          True
33     SGB         2        5444     1479135  0.099835       NaN          True
34  health         1        5444     1479135  0.099835       NaN          True
35  health         2        5321     1479135  0.104504       NaN         False