### Imports

In [1]:
import json
import numpy as np
import pandas as pd
import pingouin as pg
import seaborn as sn

print(pg.__version__) # 0.5.3
print(pd.__version__) # 2.0.3
print(np.__version__) # 1.24.3
print(sn.__version__) # 0.13.0

from utils_MS import *

# %load_ext autotime

0.5.3
2.2.2
1.26.4
0.13.2

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.6.1.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
# def run(exp):

### Parameters

In [3]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"]

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

data_variations = params["data_variations"]
print("Data variations:", data_variations)

has_transformation = params["has_transformation"]
print("Has transformation:", has_transformation)

threshold_corr = params["threshold_corr"]
print("Threshold corr:\t", threshold_corr)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

groups_id_no = params["groups_id_no"]
print("Groups id (no):\t", groups_id_no)

Exp:		 exp8
Data variations: ['none']
Has transformation: False
Threshold corr:	 0.5
Groups id:	 ['SecoAmazonas', 'FrescoSanMartin', 'FrescoCusco', 'SecoSanMartin', 'SecoCusco', 'FrescoAmazonas']
Subgroups id:	 {'SecoAmazonas': ['1', '2'], 'FrescoSanMartin': ['1', '2'], 'FrescoCusco': ['1', '2'], 'SecoSanMartin': ['1', '2'], 'SecoCusco': ['1', '2'], 'FrescoAmazonas': ['1', '2']}
Groups id (no):	 ['Blank', 'QC', 'Std']

### Load dataset

In [4]:
# read raw data
df_join_raw = pd.read_csv("experiments/input/{}_raw.csv".format(exp), index_col=0)
df_join_raw

,Average Rt,Average Mz,Metabolite name,SecoAmazonas_1.1,SecoAmazonas_1.2,SecoAmazonas_1.3,FrescoSanMartin_1.1,FrescoSanMartin_1.2,FrescoSanMartin_1.3,FrescoSanMartin_2.1,...,SecoCusco_1.3,SecoCusco_2.1,SecoCusco_2.2,SecoCusco_2.3,FrescoAmazonas_1.1,FrescoAmazonas_1.2,FrescoAmazonas_1.3,FrescoAmazonas_2.1,FrescoAmazonas_2.2,FrescoAmazonas_2.3
0,0.089,165.99460,NaN,1.213131e+06,1.177177e+06,1.566258e+05,1.731480e+06,1.699705e+06,6.280596e+06,1.696391e+06,...,3.338787e+05,1.133971e+06,1.808500e+05,3.342117e+05,4.322203e+06,1.821127e+06,1.770069e+06,1.743055e+06,1.463076e+06,6.428159e+06
1,0.090,158.01272,"[Similar to: 1-benzylhexahydropyrimidine-2,4,6...",1.431372e+04,2.609972e+04,5.571270e+03,4.865791e+04,3.923473e+04,8.001311e+03,3.985529e+04,...,4.652185e+03,3.434351e+04,2.178133e+04,3.596103e+03,5.631005e+04,4.148497e+04,9.098716e+03,2.515887e+04,5.974290e+04,5.789815e+03
2,0.097,172.95681,NaN,3.406202e+06,8.569343e+06,2.299997e+06,1.344103e+07,1.831757e+06,1.657309e+06,1.042663e+07,...,2.008602e+06,6.643525e+06,6.447431e+06,2.520397e+06,1.275967e+07,1.578762e+06,4.518729e+06,9.966807e+06,4.552709e+05,1.402781e+07
3,0.191,167.01326,NaN,5.020429e+07,4.827342e+07,1.113485e+06,6.889062e+07,6.861163e+07,2.800838e+07,6.561428e+07,...,2.189862e+06,4.159900e+07,4.101282e+07,1.728290e+06,7.507800e+07,7.443810e+07,3.294308e+07,6.365119e+07,6.403714e+07,2.607451e+07
4,0.196,165.98329,NaN,2.429038e+06,2.564504e+06,1.071655e+06,1.040565e+07,5.333877e+05,1.667311e+06,2.812425e+06,...,1.433978e+06,9.607175e+05,5.082268e+06,2.935405e+06,4.686568e+06,3.386707e+06,7.763971e+05,1.503685e+06,7.711962e+06,2.505585e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,29.965,341.26686,Docosahexaenoic acid,8.376403e+06,8.179919e+06,1.137834e+07,1.124024e+07,1.109478e+07,1.698218e+07,7.006518e+06,...,9.237098e+06,7.589148e+06,6.798410e+06,8.014118e+06,1.125906e+07,7.940634e+06,2.003224e+06,7.171052e+06,8.523936e+06,1.454813e+07
555,29.966,178.15937,N-Propylamphetamine,3.290299e+07,3.307227e+07,6.826276e+07,4.771023e+07,4.564733e+07,7.901293e+07,4.210922e+07,...,5.918501e+07,2.785011e+07,2.457465e+07,1.308641e+07,4.774097e+07,6.472719e+07,1.092961e+08,3.954838e+07,3.810093e+07,8.150158e+07
556,29.969,707.49253,NaN,1.537170e+07,1.921792e+07,4.989073e+06,2.964074e+07,2.545159e+07,5.389525e+06,2.626919e+07,...,2.580318e+06,1.344052e+07,1.132973e+07,1.192044e+06,3.228213e+07,2.365662e+07,3.800210e+06,2.567993e+07,6.028380e+06,1.913270e+06
557,29.969,165.11386,2-piperazinopyrimidine,2.308164e+06,2.275392e+06,6.454852e+06,1.710127e+06,3.178837e+06,8.738433e+06,1.248976e+06,...,5.209212e+06,1.847576e+06,1.788281e+06,1.986319e+06,3.774866e+06,3.512772e+06,1.176852e+07,2.692574e+06,2.835947e+06,7.170966e+06
558,30.021,619.44022,NaN,1.588705e+07,5.097342e+06,2.257933e+06,1.661891e+07,1.856328e+07,2.097008e+06,3.403140e+06,...,8.666917e+05,1.088554e+07,1.017020e+07,3.848034e+05,1.703750e+07,4.058914e+06,1.151024e+06,3.385950e+06,3.480922e+06,7.470031e+05

In [5]:
# get metadata
df_join_raw_metadata = df_join_raw.iloc[:, :2]
df_join_raw_metadata

     Average Rt  Average Mz
0         0.089   165.99460
1         0.090   158.01272
2         0.097   172.95681
3         0.191   167.01326
4         0.196   165.98329
..          ...         ...
554      29.965   341.26686
555      29.966   178.15937
556      29.969   707.49253
557      29.969   165.11386
558      30.021   619.44022

[559 rows x 2 columns]

In [6]:
# filter by samples
columns_sample = [column for column in df_join_raw.columns if column.split("_")[0] not in groups_id_no]
df_join_raw_intensity = df_join_raw.loc[:, columns_sample]
df_join_raw_intensity = df_join_raw_intensity.iloc[:, 3:]
df_join_raw_intensity

,SecoAmazonas_1.1,SecoAmazonas_1.2,SecoAmazonas_1.3,FrescoSanMartin_1.1,FrescoSanMartin_1.2,FrescoSanMartin_1.3,FrescoSanMartin_2.1,FrescoSanMartin_2.2,FrescoSanMartin_2.3,FrescoCusco_1.1,...,SecoCusco_1.3,SecoCusco_2.1,SecoCusco_2.2,SecoCusco_2.3,FrescoAmazonas_1.1,FrescoAmazonas_1.2,FrescoAmazonas_1.3,FrescoAmazonas_2.1,FrescoAmazonas_2.2,FrescoAmazonas_2.3
0,1.213131e+06,1.177177e+06,1.566258e+05,1.731480e+06,1.699705e+06,6.280596e+06,1.696391e+06,1.472273e+06,6.836066e+06,1.086563e+06,...,3.338787e+05,1.133971e+06,1.808500e+05,3.342117e+05,4.322203e+06,1.821127e+06,1.770069e+06,1.743055e+06,1.463076e+06,6.428159e+06
1,1.431372e+04,2.609972e+04,5.571270e+03,4.865791e+04,3.923473e+04,8.001311e+03,3.985529e+04,3.492032e+04,6.318870e+03,3.495953e+04,...,4.652185e+03,3.434351e+04,2.178133e+04,3.596103e+03,5.631005e+04,4.148497e+04,9.098716e+03,2.515887e+04,5.974290e+04,5.789815e+03
2,3.406202e+06,8.569343e+06,2.299997e+06,1.344103e+07,1.831757e+06,1.657309e+06,1.042663e+07,1.012592e+07,8.155710e+06,1.101946e+07,...,2.008602e+06,6.643525e+06,6.447431e+06,2.520397e+06,1.275967e+07,1.578762e+06,4.518729e+06,9.966807e+06,4.552709e+05,1.402781e+07
3,5.020429e+07,4.827342e+07,1.113485e+06,6.889062e+07,6.861163e+07,2.800838e+07,6.561428e+07,6.422012e+07,2.519854e+07,6.552697e+07,...,2.189862e+06,4.159900e+07,4.101282e+07,1.728290e+06,7.507800e+07,7.443810e+07,3.294308e+07,6.365119e+07,6.403714e+07,2.607451e+07
4,2.429038e+06,2.564504e+06,1.071655e+06,1.040565e+07,5.333877e+05,1.667311e+06,2.812425e+06,1.715898e+06,1.772940e+06,1.913464e+06,...,1.433978e+06,9.607175e+05,5.082268e+06,2.935405e+06,4.686568e+06,3.386707e+06,7.763971e+05,1.503685e+06,7.711962e+06,2.505585e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,8.376403e+06,8.179919e+06,1.137834e+07,1.124024e+07,1.109478e+07,1.698218e+07,7.006518e+06,1.322471e+07,1.424028e+07,1.047806e+07,...,9.237098e+06,7.589148e+06,6.798410e+06,8.014118e+06,1.125906e+07,7.940634e+06,2.003224e+06,7.171052e+06,8.523936e+06,1.454813e+07
555,3.290299e+07,3.307227e+07,6.826276e+07,4.771023e+07,4.564733e+07,7.901293e+07,4.210922e+07,4.038062e+07,9.140048e+07,4.372639e+07,...,5.918501e+07,2.785011e+07,2.457465e+07,1.308641e+07,4.774097e+07,6.472719e+07,1.092961e+08,3.954838e+07,3.810093e+07,8.150158e+07
556,1.537170e+07,1.921792e+07,4.989073e+06,2.964074e+07,2.545159e+07,5.389525e+06,2.626919e+07,2.693046e+07,2.338017e+06,2.590761e+07,...,2.580318e+06,1.344052e+07,1.132973e+07,1.192044e+06,3.228213e+07,2.365662e+07,3.800210e+06,2.567993e+07,6.028380e+06,1.913270e+06
557,2.308164e+06,2.275392e+06,6.454852e+06,1.710127e+06,3.178837e+06,8.738433e+06,1.248976e+06,2.793988e+06,5.279317e+06,2.960870e+06,...,5.209212e+06,1.847576e+06,1.788281e+06,1.986319e+06,3.774866e+06,3.512772e+06,1.176852e+07,2.692574e+06,2.835947e+06,7.170966e+06
558,1.588705e+07,5.097342e+06,2.257933e+06,1.661891e+07,1.856328e+07,2.097008e+06,3.403140e+06,2.053906e+07,8.273387e+05,1.548264e+07,...,8.666917e+05,1.088554e+07,1.017020e+07,3.848034e+05,1.703750e+07,4.058914e+06,1.151024e+06,3.385950e+06,3.480922e+06,7.470031e+05

In [7]:
df_join_raw_intensity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 559 entries, 0 to 558
Data columns (total 36 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SecoAmazonas_1.1     559 non-null    float64
 1   SecoAmazonas_1.2     559 non-null    float64
 2   SecoAmazonas_1.3     559 non-null    float64
 3   FrescoSanMartin_1.1  559 non-null    float64
 4   FrescoSanMartin_1.2  559 non-null    float64
 5   FrescoSanMartin_1.3  559 non-null    float64
 6   FrescoSanMartin_2.1  559 non-null    float64
 7   FrescoSanMartin_2.2  559 non-null    float64
 8   FrescoSanMartin_2.3  559 non-null    float64
 9   FrescoCusco_1.1      559 non-null    float64
 10  FrescoCusco_1.2      559 non-null    float64
 11  FrescoCusco_1.3      559 non-null    float64
 12  FrescoCusco_2.1      559 non-null    float64
 13  FrescoCusco_2.2      559 non-null    float64
 14  FrescoCusco_2.3      559 non-null    float64
 15  SecoAmazonas_2.1     559 non-null    float64
 16  SecoAmazonas_2.2     559 non-null    float64
 17  SecoAmazonas_2.3     559 non-null    float64
 18  SecoSanMartin_1.1    559 non-null    float64
 19  SecoSanMartin_1.2    559 non-null    float64
 20  SecoSanMartin_1.3    559 non-null    float64
 21  SecoSanMartin_2.1    559 non-null    float64
 22  SecoSanMartin_2.2    559 non-null    float64
 23  SecoSanMartin_2.3    559 non-null    float64
 24  SecoCusco_1.1        559 non-null    float64
 25  SecoCusco_1.2        559 non-null    float64
 26  SecoCusco_1.3        559 non-null    float64
 27  SecoCusco_2.1        559 non-null    float64
 28  SecoCusco_2.2        559 non-null    float64
 29  SecoCusco_2.3        559 non-null    float64
 30  FrescoAmazonas_1.1   559 non-null    float64
 31  FrescoAmazonas_1.2   559 non-null    float64
 32  FrescoAmazonas_1.3   559 non-null    float64
 33  FrescoAmazonas_2.1   559 non-null    float64
 34  FrescoAmazonas_2.2   559 non-null    float64
 35  FrescoAmazonas_2.3   559 non-null    float64
dtypes: float64(36)
memory usage: 161.6 KB

In [8]:
check_dataset(df_join_raw_intensity)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 20124

### Generate graphs

In [9]:
""" from sklearn import preprocessing

X_scaled = preprocessing.RobustScaler().fit_transform(df_join_raw)

df_join_raw_log = pd.DataFrame(X_scaled, columns=df_join_raw.columns)
df_join_raw_log """

' from sklearn import preprocessing\n\nX_scaled = preprocessing.RobustScaler().fit_transform(df_join_raw)\n\ndf_join_raw_log = pd.DataFrame(X_scaled, columns=df_join_raw.columns)\ndf_join_raw_log '

In [10]:
# Transformation (log10)

if not has_transformation:
	df_join_raw_log = log10_global(df_join_raw_intensity)
else:
	df_join_raw_log = df_join_raw_intensity.copy()
df_join_raw_log.head()

,SecoAmazonas_1.1,SecoAmazonas_1.2,SecoAmazonas_1.3,FrescoSanMartin_1.1,FrescoSanMartin_1.2,FrescoSanMartin_1.3,FrescoSanMartin_2.1,FrescoSanMartin_2.2,FrescoSanMartin_2.3,FrescoCusco_1.1,...,SecoCusco_1.3,SecoCusco_2.1,SecoCusco_2.2,SecoCusco_2.3,FrescoAmazonas_1.1,FrescoAmazonas_1.2,FrescoAmazonas_1.3,FrescoAmazonas_2.1,FrescoAmazonas_2.2,FrescoAmazonas_2.3
0,6.083908,6.070842,5.194863,6.238417,6.230374,6.798001,6.229526,6.167988,6.834806,6.036055,...,5.523589,6.054602,5.257318,5.524022,6.635705,6.260340,6.247990,6.241311,6.165267,6.808087
1,4.155752,4.416636,3.745954,4.687153,4.593671,3.903161,4.600486,4.543078,3.800639,4.543566,...,3.667657,4.535845,4.338084,3.555832,4.750586,4.617891,3.958980,4.400691,4.776286,3.762665
2,6.532270,6.932948,6.361727,7.128433,6.262868,6.219404,7.018144,7.005435,6.911462,7.042160,...,6.302894,6.822399,6.809387,6.401469,7.105840,6.198317,6.655016,6.998556,5.658270,7.146990
3,7.700741,7.683708,6.046684,7.838160,7.836398,7.447288,7.816998,7.807671,7.401375,7.816420,...,6.340417,7.619083,7.612920,6.237617,7.875513,7.871795,7.517764,7.803807,7.806432,7.416216
4,6.385434,6.409003,6.030055,7.017269,5.727043,6.222017,6.449081,6.234491,6.248694,6.281820,...,6.156542,5.982596,6.706058,6.467668,6.670855,6.529778,5.890084,6.177157,6.887165,7.398909

In [11]:
check_dataset(df_join_raw_log)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 20124

In [12]:
# split graph in groups and subgroups

""" def split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id, by_group=False):
	list_df_groups_subgroups = []
	for group in groups_id:
		df_aux = df_join_raw_log.filter(like=group)
		list_aux = []
		
		if by_group:
			list_aux.append(df_aux)
		else:
			for subgroup in subgroups_id[group]:
				list_aux.append(df_aux.filter(like="{}_{}.".format(group, subgroup)))
		list_df_groups_subgroups.append(list_aux)
	return list_df_groups_subgroups """

dict_df_groups_subgroups = split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id)
dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

   SecoAmazonas_1.1  SecoAmazonas_1.2  SecoAmazonas_1.3
0          6.083908          6.070842          5.194863
1          4.155752          4.416636          3.745954
2          6.532270          6.932948          6.361727
3          7.700741          7.683708          6.046684
4          6.385434          6.409003          6.030055

In [13]:
check_dataset(dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 1677

In [14]:
# Transpose
dict_groups_subgroups_t = transpose_global(dict_df_groups_subgroups)
dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

,0,1,2,3,4,5,6,7,8,9,...,549,550,551,552,553,554,555,556,557,558
0,6.083908,4.155752,6.532270,7.700741,6.385434,8.610974,6.348509,6.538010,6.816724,6.385434,...,6.715411,6.184520,7.322656,6.782134,6.515814,6.923058,7.517235,7.186722,6.363267,7.201043
1,6.070842,4.416636,6.932948,7.683708,6.409003,8.578933,7.777185,5.717278,7.622484,6.409003,...,6.747370,6.169553,7.382571,6.785937,6.465011,6.912749,7.519464,7.283706,6.357056,6.707344
2,5.194863,3.745954,6.361727,6.046684,6.030055,8.524494,6.230455,6.368448,6.953095,6.588367,...,6.376713,6.262426,8.200814,7.791348,6.782885,7.056079,7.834184,6.698020,6.809886,6.353711

In [15]:
check_dataset(dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 1677

In [16]:
# Correlation matrix

dict_groups_subgroups_t_corr = correlation_global(exp, dict_groups_subgroups_t)
dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

SecoAmazonas 1 (3, 559)
SecoAmazonas 2 (3, 559)
FrescoSanMartin 1 (3, 559)
FrescoSanMartin 2 (3, 559)
FrescoCusco 1 (3, 559)
FrescoCusco 2 (3, 559)
SecoSanMartin 1 (3, 559)
SecoSanMartin 2 (3, 559)
SecoCusco 1 (3, 559)
SecoCusco 2 (3, 559)
FrescoAmazonas 1 (3, 559)
FrescoAmazonas 2 (3, 559)

,0,1,2,3,4,5,6,7,8,9,...,549,550,551,552,553,554,555,556,557,558
0,1.000000,-0.169731,-0.105750,-0.997286,-0.630522,-0.084862,-0.085864,0.068856,-0.071064,0.449032,...,-0.529632,0.345099,0.715816,0.983876,0.347278,0.586296,0.991899,-0.338023,0.906877,-0.022983
1,-0.169731,1.000000,-0.997914,-0.241824,-0.871929,0.967532,-0.996425,0.994838,-0.995061,-0.804336,...,-0.925815,0.983522,-0.566661,0.343252,0.983100,0.897855,0.293539,-0.984855,0.569207,0.981329
2,-0.105750,-0.997914,1.000000,-0.178672,-0.838497,0.981832,-0.999800,0.999314,-0.999394,-0.841020,...,-0.899480,0.969798,-0.618676,0.281895,0.969229,0.867555,0.231207,-0.971607,0.514935,0.991700
3,-0.997286,-0.241824,-0.178672,1.000000,-0.685954,-0.011276,-0.158980,0.142116,-0.144307,0.382032,...,-0.590643,0.413262,0.662464,0.994373,0.415375,0.644346,0.998559,-0.406394,0.935440,0.050681
4,-0.630522,-0.871929,-0.838497,-0.685954,1.000000,0.719864,-0.827443,0.817744,-0.819016,-0.410396,...,-0.992315,0.946081,-0.090654,0.759176,0.946831,0.998447,0.724009,-0.943615,0.898881,0.761475

In [17]:
# Check correlation matrices

dict_groups_subgroups_t_corr

{'SecoAmazonas': {'1':           0         1         2         3         4         5         6    \
  0    1.000000 -0.169731 -0.105750 -0.997286 -0.630522 -0.084862 -0.085864
  1   -0.169731  1.000000 -0.997914 -0.241824 -0.871929  0.967532 -0.996425
  2   -0.105750 -0.997914  1.000000 -0.178672 -0.838497  0.981832 -0.999800
  3   -0.997286 -0.241824 -0.178672  1.000000 -0.685954 -0.011276 -0.158980
  4   -0.630522 -0.871929 -0.838497 -0.685954  1.000000  0.719864 -0.827443
  ..        ...       ...       ...       ...       ...       ...       ...
  554  0.586296  0.897855  0.867555  0.644346  0.998447 -0.757420  0.857446
  555  0.991899  0.293539  0.231207  0.998559  0.724009 -0.042393  0.211725
  556 -0.338023 -0.984855 -0.971607 -0.406394 -0.943615  0.909057 -0.966686
  557  0.906877  0.569207  0.514935  0.935440  0.898881 -0.342917  0.497707
  558 -0.022983  0.981329  0.991700  0.050681  0.761475 -0.998080  0.994070

            7         8         9    ...       549       550       551  \
  0    0.068856 -0.071064  0.449032  ... -0.529632  0.345099  0.715816
  1    0.994838 -0.995061 -0.804336  ... -0.925815  0.983522 -0.566661
  2    0.999314 -0.999394 -0.841020  ... -0.899480  0.969798 -0.618676
  3    0.142116 -0.144307  0.382032  ... -0.590643  0.413262  0.662464
  4    0.817744 -0.819016 -0.410396  ... -0.992315  0.946081 -0.090654
  ..        ...       ...       ...  ...       ...       ...       ...
  554 -0.848544  0.849713  0.460568  ...  0.997668 -0.962660  0.146002
  555 -0.195023  0.197194 -0.331895  ...  0.633089 -0.461526 -0.621316
  556  0.962179 -0.962780 -0.689138  ... -0.977327  0.999972 -0.415224
  557 -0.482840  0.484777 -0.030693  ...  0.837751 -0.708470 -0.354901
  558 -0.995781  0.995575  0.903600  ...  0.835831 -0.930387  0.714557

            552       553       554       555       556       557       558
  0    0.983876  0.347278  0.586296  0.991899 -0.338023  0.906877 -0.022983
  1    0.343252  0.983100  0.897855  0.293539 -0.984855  0.569207  0.981329
  2    0.281895  0.969229  0.867555  0.231207 -0.971607  0.514935  0.991700
  3    0.994373  0.415375  0.644346  0.998559 -0.406394  0.935440  0.050681
  4    0.759176  0.946831  0.998447  0.724009 -0.943615  0.898881  0.761475
  ..        ...       ...       ...       ...       ...       ...       ...
  554 -0.721730 -0.963286  1.000000 -0.684450  0.960594 -0.873070 -0.796408
  555 -0.998625 -0.463585 -0.684450  1.000000  0.454834 -0.953059 -0.104195
  556  0.500898  0.999951  0.960594  0.454834  1.000000  0.703137  0.933120
  557 -0.967622 -0.710108 -0.873070 -0.953059  0.703137  1.000000 -0.400441
  558 -0.156192 -0.929533 -0.796408 -0.104195  0.933120 -0.400441  1.000000

  [559 rows x 559 columns],
  '2':           0         1         2         3         4         5         6    \
  0    1.000000  0.972487  0.423902 -0.222023 -0.999861  0.760305 -0.034442
  1    0.972487  1.000000 -0.623231 -0.011230  0.976230 -0.890708 -0.199326
  2    0.423902 -0.623231  1.000000 -0.788987  0.438920 -0.910612 -0.890571
  3   -0.222023 -0.011230 -0.788987  1.000000 -0.205761 -0.464549 -0.982110
  4   -0.999861  0.976230  0.438920 -0.205761  1.000000  0.771013 -0.017800
  ..        ...       ...       ...       ...       ...       ...       ...
  554 -0.983216  0.998667  0.582030 -0.040404 -0.986117  0.866055  0.148474
  555  0.905300 -0.781438  0.000961  0.615168  0.898104 -0.412387  0.455700
  556  0.400690 -0.603105 -0.999675 -0.804384  0.415886 -0.899788 -0.901870
  557  0.874606 -0.737596  0.068371  0.666916  0.866414 -0.350035  0.514670
  558 -0.410164  0.186418 -0.652147 -0.980315 -0.394925 -0.280563 -0.925598

            7         8         9    ...       549       550       551  \
  0   -0.981498 -0.032992 -0.987975  ...  0.970095  0.742573  0.897133
  1    0.999099 -0.200747  0.996811  ... -0.886859 -0.566115 -0.769539
  2    0.589477 -0.891230  0.558841  ... -0.191386  0.291833  0.019809
  3   -0.031222 -0.981836 -0.068596  ...  0.452052  0.817917  0.629918
  4   -0.984549 -0.016350 -0.990412  ...  0.965920  0.731321  0.889655
  ..        ...       ...       ...  ...       ...       ...       ...
  554 -0.999958  0.149909 -0.999601  ...  0.909528  0.607914  0.801478
  555  0.807218  0.454408  0.828737  ... -0.981331 -0.956749 -0.999822
  556  0.568706 -0.902495  0.537533  ... -0.166318  0.316106  0.045274
  557  0.765592  0.513425  0.789125  ... -0.966133 -0.974184 -0.998819
  558 -0.227950 -0.925047 -0.264220  ...  0.619267  0.915410  0.770862

            552       553       554       555       556       557       558
  0    0.938907 -0.998945 -0.983216  0.905300  0.400690  0.874606 -0.410164
  1   -0.832897  0.982161  0.998667 -0.781438 -0.603105 -0.737596  0.186418
  2   -0.086286  0.465055  0.582030  0.000961 -0.999675  0.068371 -0.652147
  3    0.544040 -0.177003 -0.040404  0.615168 -0.804384  0.666916 -0.980315
  4    0.933047 -0.999571 -0.986117  0.898104  0.415886  0.866414 -0.394925
  ..        ...       ...       ...       ...       ...       ...       ...
  554  0.860355 -0.990558  1.000000  0.812607  0.561125  0.771470 -0.236886
  555 -0.996187  0.884834  0.812607  1.000000  0.026437 -0.997725  0.758719
  556 -0.060876  0.442351  0.561125  0.026437  1.000000  0.093766 -0.671249
  557 -0.988040  0.851413  0.771470 -0.997725  0.093766  1.000000  0.800907
  558  0.698994 -0.367840 -0.236886  0.758719 -0.671249  0.800907  1.000000

  [559 rows x 559 columns]},
 'FrescoSanMartin': {'1':           0         1         2         3         4         5         6    \
  0    1.000000 -0.045636 -0.445909  0.952973 -0.466843  0.072257  0.959689
  1   -0.045636  1.000000 -0.914495 -0.259250 -0.904723 -0.993049 -0.236976
  2   -0.445909 -0.914495  1.000000  0.153681 -0.999723 -0.860519  0.176358
  3    0.952973 -0.259250  0.153681  1.000000  0.176885 -0.371122 -0.999736
  4   -0.466843 -0.904723 -0.999723  0.176885  1.000000 -0.848296  0.199467
  ..        ...       ...       ...       ...       ...       ...       ...
  554 -0.977667 -0.254556 -0.624059  0.868001 -0.642269 -0.138966  0.879188
  555 -0.836842 -0.585064 -0.863161  0.631582 -0.874801 -0.485546  0.649240
  556  0.104823 -0.988671 -0.843406 -0.401280 -0.830532 -0.999466 -0.380115
  557  0.365684  0.946458  0.996146 -0.066421  0.993807  0.901883 -0.089344
  558  0.921119  0.430911  0.759172 -0.759828  0.774275  0.321706 -0.774574

            7         8         9    ...       549       550       551  \
  0   -0.716421  0.904080  0.758152  ... -0.507965 -0.938184 -0.921847
  1   -0.729636 -0.385660 -0.616799  ... -0.883661  0.302961 -0.429220
  2   -0.943926  0.020613 -0.245594  ... -0.997507 -0.108526 -0.757951
  3    0.471298 -0.991078 -0.920114  ...  0.223032  0.998963  0.761045
  4   -0.951432  0.044129 -0.222720  ... -0.998891 -0.131883 -0.773088
  ..        ...       ...       ...  ...       ...       ...       ...
  554 -0.847042  0.794075  0.604181  ... -0.677647 -0.844489 -0.982707
  555 -0.981466  0.522614  0.277478  ... -0.896643 -0.595622 -0.983605
  556 -0.618727 -0.519778 -0.727957  ... -0.803385  0.442573 -0.288788
  557  0.911330  0.067157  0.329670  ...  0.987472  0.020916  0.697816
  558  0.931498 -0.666401 -0.444508  ...  0.803214  0.729435  0.999998

            552       553       554       555       556       557       558
  0   -0.696907 -0.963207 -0.977667 -0.836842  0.104823  0.365684  0.921119
  1   -0.748219 -0.312439 -0.254556 -0.585064 -0.988671  0.946458  0.430911
  2   -0.952673 -0.670065 -0.624059 -0.863161 -0.843406  0.996146  0.759172
  3    0.446793  0.836460  0.868001  0.631582 -0.401280 -0.066421 -0.759828
  4   -0.959561 -0.687343 -0.642269 -0.874801 -0.830532  0.993807  0.774275
  ..        ...       ...       ...       ...       ...       ...       ...
  554 -0.832060 -0.998178  1.000000 -0.933203 -0.106518  0.553120  0.982359
  555 -0.975807 -0.953184 -0.933203  1.000000 -0.456708  0.815547  0.983941
  556 -0.640159 -0.166314 -0.106518 -0.456708  1.000000  0.887279  0.290581
  557  0.922338  0.602376  0.553120  0.815547  0.887279  1.000000 -0.699157
  558  0.921111  0.991852  0.982359  0.983941  0.290581 -0.699157  1.000000

  [559 rows x 559 columns],
  '2':           0         1         2         3         4         5         6    \
  0    1.000000 -0.408680 -0.624217  0.199018 -0.878953 -0.633857  0.340632
  1   -0.408680  1.000000 -0.968136 -0.813085 -0.794474 -0.964956 -0.718887
  2   -0.624217 -0.968136  1.000000 -0.641392 -0.921243 -0.999923 -0.521902
  3    0.199018 -0.813085 -0.641392  1.000000 -0.292441 -0.631829 -0.989181
  4   -0.878953 -0.794474 -0.921243 -0.292441  1.000000 -0.925995 -0.148989
  ..        ...       ...       ...       ...       ...       ...       ...
  554  0.874212  0.800419  0.925030  0.301848  0.999951  0.929670  0.158724
  555 -0.968411 -0.168184 -0.409685  0.437104 -0.732265 -0.420965  0.564320
  556  0.714865 -0.346050 -0.100069 -0.827545  0.294849 -0.087723 -0.900950
  557  0.855902  0.821771  0.938283  0.336453  0.998925  0.942500  0.194665
  558  0.918823  0.735710  0.881880  0.203911  0.995823  0.887659  0.058086

            7         8         9    ...       549       550       551  \
  0    0.041299  0.418079 -0.976493  ...  0.845213  0.532594  0.100593
  1    0.928777 -0.658226 -0.595802  ...  0.833184  0.990124  0.949159
  2    0.806364 -0.448725 -0.777943  ...  0.945120  0.993682  0.840080
  3    0.970941 -0.973444 -0.016899  ...  0.355526  0.723444  0.955005
  4    0.512801 -0.065757 -0.961089  ...  0.997776  0.871766  0.562906
  ..        ...       ...       ...  ...       ...       ...       ...
  554 -0.521235  0.075585  0.958321  ... -0.998385 -0.876551 -0.571022
  555 -0.209154  0.631394 -0.891896  ...  0.685247  0.304718 -0.150680
  556  0.669143 -0.934087  0.547334  ... -0.230506  0.211103  0.623805
  557 -0.552045  0.111940  0.947252  ... -0.999793 -0.893539 -0.600613
  558 -0.432278 -0.025619  0.982296  ... -0.987524 -0.823396 -0.485094

            552       553       554       555       556       557       558
  0    0.341242  0.876172  0.874212 -0.968411  0.714865  0.855902  0.918823
  1    0.997353  0.797983  0.800419 -0.168184 -0.346050  0.821771  0.735710
  2    0.947366  0.923483  0.925030 -0.409685 -0.100069  0.938283  0.881880
  3    0.853259  0.297982  0.301848  0.437104 -0.827545  0.336453  0.203911
  4    0.748218  0.999983  0.999951 -0.732265  0.294849  0.998925  0.995823
  ..        ...       ...       ...       ...       ...       ...       ...
  554 -0.754718 -0.999992  1.000000  0.725520 -0.285420 -0.999333 -0.994876
  555  0.096069  0.728303  0.725520  1.000000  0.866652  0.699910  0.791384
  556  0.413348 -0.289302 -0.285420  0.866652  1.000000 -0.250239 -0.380858
  557 -0.778167 -0.999177 -0.999333  0.699910 -0.250239  1.000000 -0.990521
  558 -0.684520 -0.995277 -0.994876  0.791384 -0.380858 -0.990521  1.000000

  [559 rows x 559 columns]},
 'FrescoCusco': {'1':           0         1         2         3         4         5         6    \
  0    1.000000 -0.774998  0.960465 -0.334250 -0.966574 -0.878378 -0.084213
  1   -0.774998  1.000000  0.920298 -0.854659 -0.911120 -0.982799 -0.694984
  2    0.960465  0.920298  1.000000  0.583424  0.999739  0.976717  0.358295
  3   -0.334250 -0.854659  0.583424  1.000000 -0.564718 -0.744074 -0.967285
  4   -0.966574 -0.911120  0.999739 -0.564718  1.000000 -0.971562 -0.336874
  ..        ...       ...       ...       ...       ...       ...       ...
  554  0.918641  0.961630 -0.992317  0.679426  0.989231  0.995755  0.471052
  555 -0.882908 -0.387517  0.717281  0.147427 -0.733011 -0.551100  0.393525
  556  0.877557  0.377096 -0.709378 -0.158571  0.725294  0.541655 -0.403867
  557  0.453241  0.914585 -0.683484  0.991615  0.666631  0.824170  0.926391
  558  0.968867  0.907333 -0.999490  0.557186  0.999959  0.969367  0.328294

            7         8         9    ...       549       550       551  \
  0    0.101464  0.055684 -0.996318  ... -0.986745  0.471672 -0.846357
  1   -0.550068 -0.587828 -0.826323  ... -0.662170  0.922794 -0.319331
  2    0.179511  0.224485  0.980796  ...  0.902555 -0.698511  0.664616
  3   -0.903706 -0.922410 -0.413819  ... -0.176873  0.988715  0.219087
  4   -0.156991 -0.202166 -0.984996  ... -0.912155  0.681981 -0.681511
  ..        ...       ...       ...  ...       ...       ...       ...
  554  0.299846  0.343327  0.949130  ...  0.842348 -0.781681  0.567065
  555  0.556705  0.517981 -0.839404  ... -0.947403  0.002410 -0.997343
  556 -0.566038 -0.527594  0.833221  ...  0.943734  0.008867  0.998101
  557  0.840800  0.864767  0.527990  ...  0.302578 -0.999784 -0.091164
  558  0.147999  0.193247  0.986525  ...  0.915847 -0.675298  0.688141

            552       553       554       555       556       557       558
  0   -0.643764  0.925412  0.918641 -0.882908  0.877557  0.453241  0.968867
  1   -0.015323  0.956683  0.961630 -0.387517  0.377096  0.914585  0.907333
  2    0.405275 -0.994329 -0.992317  0.717281 -0.709378 -0.683484 -0.999490
  3    0.506033  0.666486  0.679426  0.147427 -0.158571  0.991615  0.557186
  4   -0.426053  0.991640  0.989231 -0.733011  0.725294  0.666631  0.999959
  ..        ...       ...       ...       ...       ...       ...       ...
  554  0.289053 -0.999847  1.000000  0.625561 -0.616723 -0.768547 -0.987859
  555 -0.927692  0.639114  0.625561  1.000000  0.999936 -0.018377  0.739170
  556  0.931844 -0.630399 -0.616723  0.999936  1.000000  0.029652 -0.731528
  557 -0.390331 -0.757237 -0.768547 -0.018377  0.029652  1.000000 -0.659821
  558  0.434267 -0.990425 -0.987859  0.739170 -0.731528 -0.659821  1.000000

  [559 rows x 559 columns],
  '2':           0         1         2         3         4         5         6    \
  0    1.000000  0.873710 -0.107359 -0.055755 -0.372758 -0.857507 -0.134078
  1    0.873710  1.000000 -0.389834 -0.436976 -0.125705  0.498949 -0.364909
  2   -0.107359 -0.389834  1.000000 -0.998660 -0.962584 -0.603561 -0.999638
  3   -0.055755 -0.436976 -0.998660  1.000000 -0.947268 -0.561483 -0.996905
  4   -0.372758 -0.125705 -0.962584 -0.947268  1.000000 -0.797037 -0.969529
  ..        ...       ...       ...       ...       ...       ...       ...
  554  0.983095 -0.769872  0.287584  0.237626  0.536359  0.937209  0.313257
  555  0.734480 -0.311605  0.753561  0.718526  0.903504  0.978958  0.770981
  556 -0.232743 -0.269738 -0.991904 -0.984002 -0.989203 -0.699923 -0.994963
  557 -0.999300  0.891303 -0.070077 -0.018352 -0.337771 -0.837653 -0.096899
  558  0.999967 -0.877615  0.099317  0.047681  0.365244  0.853319  0.126062

            7         8         9    ...       549       550       551  \
  0   -0.431640 -0.989375 -0.968375  ... -0.964068 -0.947213  0.528171
  1   -0.061668  0.793705  0.724711  ...  0.971543  0.671632 -0.048409
  2   -0.943173 -0.250763 -0.352022  ...  0.160618 -0.420445  0.900934
  3   -0.924709 -0.200322 -0.303104  ...  0.211490 -0.372919  0.877265
  4   -0.997931 -0.503705 -0.592488  ... -0.112856 -0.650581  0.984819
  ..        ...       ...       ...  ...       ...       ...       ...
  554  0.589507  0.999269  0.997687  ...  0.899129  0.989902 -0.674718
  555  0.929187  0.825339  0.880570  ...  0.527807  0.913282 -0.964182
  556 -0.977735 -0.371663 -0.468031  ...  0.033980 -0.532258  0.948747
  557 -0.397581 -0.983241 -0.958359  ... -0.973334 -0.934551  0.496024
  558  0.424333  0.988167  0.966326  ...  0.966184  0.944590 -0.521289

            552       553       554       555       556       557       558
  0    0.852686  0.995233  0.983095  0.734480 -0.232743 -0.999300  0.999967
  1   -0.490870 -0.822105 -0.769872 -0.311605 -0.269738  0.891303 -0.877615
  2    0.610947  0.203809  0.287584  0.753561 -0.991904 -0.070077  0.099317
  3    0.569152  0.152863  0.237626  0.718526 -0.984002 -0.018352  0.047681
  4    0.802617  0.461478  0.536359  0.903504 -0.989203 -0.337771  0.365244
  ..        ...       ...       ...       ...       ...       ...       ...
  554 -0.933926 -0.996265  1.000000 -0.846319  0.406879  0.975554 -0.981582
  555 -0.980813 -0.797162 -0.846319  1.000000  0.830939  0.708569 -0.728969
  556  0.706533  0.326480  0.406879  0.830939  1.000000 -0.196185  0.224872
  557  0.832539  0.990886  0.975554  0.708569 -0.196185  1.000000  0.999569
  558 -0.848435 -0.994412 -0.981582 -0.728969  0.224872  0.999569  1.000000

  [559 rows x 559 columns]},
 'SecoSanMartin': {'1':           0         1         2         3         4         5         6    \
  0    1.000000  0.783683  0.424494  0.936881  0.815362  0.976302  0.845954
  1    0.783683  1.000000 -0.895087 -0.517030 -0.279363 -0.630683 -0.331722
  2    0.424494 -0.895087  1.000000 -0.081118  0.178085 -0.218486  0.123724
  3    0.936881 -0.517030 -0.081118  1.000000 -0.966326 -0.990347 -0.979010
  4    0.815362 -0.279363  0.178085 -0.966326  1.000000 -0.921332 -0.998488
  ..        ...       ...       ...       ...       ...       ...       ...
  554 -0.719109  0.995197  0.934439  0.430749  0.184021  0.551681  0.237775
  555 -0.519982  0.938082  0.994128  0.188499 -0.070555  0.322803 -0.015614
  556  0.416848  0.237943  0.646065 -0.708359 -0.866136 -0.603685 -0.837351
  557 -0.323883 -0.333857 -0.719139  0.634241  0.811827  0.520956  0.778502
  558  0.791315 -0.240358  0.217679 -0.955146 -0.999184 -0.904880 -0.995453

            7         8         9    ...       549       550       551  \
  0   -0.905985  0.920683 -0.930114  ... -0.146403 -0.576857 -0.578547
  1    0.447062 -0.479077  0.500780  ... -0.499735  0.959465  0.960047
  2    0.001308 -0.037423  0.062289  ... -0.833528  0.984469  0.984103
  3    0.996810 -0.999042  0.999822  ...  0.483043  0.254838  0.256839
  4    0.983781 -0.976661  0.971012  ...  0.692085 -0.002567 -0.000497
  ..        ...       ...       ...  ...       ...       ...       ...
  554 -0.357345  0.390844 -0.413637  ...  0.582131 -0.982447 -0.982831
  555 -0.109514  0.145342 -0.169927  ...  0.768847 -0.997686 -0.997543
  556  0.762437 -0.738569  0.721557  ...  0.960210 -0.502031 -0.500239
  557 -0.693925  0.667467 -0.648722  ... -0.983320  0.585981  0.584302
  558  0.975735 -0.967190  0.960566  ...  0.720671 -0.042950 -0.040881

            552       553       554       555       556       557       558
  0   -0.627898 -0.716964 -0.719109 -0.519982  0.416848 -0.323883  0.791315
  1    0.975520  0.994890  0.995197  0.938082  0.237943 -0.333857 -0.240358
  2    0.971232  0.935532  0.934439  0.994128  0.646065 -0.719139  0.217679
  3    0.316136  0.427966  0.430749  0.188499 -0.708359  0.634241 -0.955146
  4    0.061368  0.180991  0.184021 -0.070555 -0.866136  0.811827 -0.999184
  ..        ...       ...       ...       ...       ...       ...       ...
  554 -0.992363 -0.999995  1.000000 -0.967489 -0.331886  0.424534  0.144176
  555 -0.991298 -0.968264 -0.967489  1.000000 -0.559673  0.639722 -0.110782
  556 -0.445714 -0.334791 -0.331886 -0.559673  1.000000  0.994990 -0.885614
  557  0.532978  0.427322  0.424534  0.639722  0.994990  1.000000  0.834745
  558  0.021009  0.141126  0.144176 -0.110782 -0.885614  0.834745  1.000000

  [559 rows x 559 columns],
  '2':           0         1         2         3         4         5         6    \
  0    1.000000 -0.950208 -0.227586 -0.128062 -0.996827 -0.451895  0.998825
  1   -0.950208  1.000000 -0.519693 -0.430736 -0.971998 -0.707378  0.964194
  2   -0.227586 -0.519693  1.000000 -0.994885 -0.304379 -0.971506  0.274514
  3   -0.128062 -0.430736 -0.994885  1.000000 -0.206604 -0.942596  0.175979
  4   -0.996827 -0.971998 -0.304379 -0.206604  1.000000 -0.521473  0.999513
  ..        ...       ...       ...       ...       ...       ...       ...
  554  0.718086  0.465460 -0.514264 -0.598265  0.660406 -0.296341 -0.683511
  555  0.896572  0.989944  0.635324  0.554068  0.928983  0.800253 -0.916984
  556  0.661969  0.395442 -0.579206 -0.658587  0.600203 -0.369494 -0.624864
  557  0.993598  0.979328  0.336135  0.239281  0.999438  0.549779 -0.997906

In [18]:
check_dataset(dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][1]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 155986
Count zero:	 0
Count positive:	 156495

In [19]:
# Build graph (corpus graphs)

dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

    source  target    weight subgroup
2        0       3 -0.997286        1
3        0       4 -0.630522        1
9        0      10 -0.989137        1
10       0      11 -0.875317        1
11       0      12 -0.889671        1

In [20]:
def create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups, df_join_raw_metadata):	
	for group_id in tqdm(groups_id):
		for subgroup_id in tqdm(subgroups_id[group_id]):
			df_weighted_edges = pd.read_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id))
			# print(df_weighted_edges)
			G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight", "subgroup"])
			dict_id_idx = dict(zip(list(G.nodes()), range(G.number_of_nodes())))
			G = nx.relabel_nodes(G, dict_id_idx)

			df_nodes = dict_df_groups_subgroups[group_id][subgroup_id].loc[list(dict_id_idx.keys())] # A_1.1, A_1.2, A_1.3
			# from IPython.display import display
			# display(df_nodes)

			# nodes, with node features
			metadata = df_join_raw_metadata.loc[df_nodes.index] # Average Rt, Average Mz
			# intensity = df_join_raw_log.loc[df_nodes.index] # A_1.1, A_1.2, A_1.3, A_2.1, ...

			""" e = 1e-8
			mz = metadata.iloc[:, 1].values
			rt = metadata.iloc[:, 0].values
			intensity_mean = df_nodes.mean(axis=1).values
			intensity_std = df_nodes.std(axis=1).values
			intensity_cv = intensity_std / intensity_mean
			presence_ratio = (df_nodes > 0).mean(axis=1)

			mz_log = np.log10(mz + e)
			# intensity_mean_log = np.log10(intensity_mean + e)
			
			# mz_z = (mz_log - mz_log.mean()) / mz_log.std() # z-score
			rt_z = (rt - rt.mean()) / rt.std() # z-score
			# intensity_mean_z = (intensity_mean_log - intensity_mean_log.mean()) / intensity_mean_log.std() # z-score

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": mz_log,
				"rt": rt_z,
				"intensity_mean": intensity_mean,
				"intensity_std": intensity_std,
				"intensity_cv": intensity_cv,
				"presence_ratio": presence_ratio
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			# df_node_features.insert(0, "idx", list(dict_id_idx.values()))
			# df_node_features.insert(1, "id", list(dict_id_idx.keys()))
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features) """

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": metadata.iloc[:, 1].values,
				"rt": metadata.iloc[:, 0].values,
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features)

			# edges
			edges = list(G.edges())
			df_edges = pd.DataFrame(edges, columns=["source", "target"])
			df_edges["weight"] = [G.get_edge_data(*edge)["weight"] for edge in edges]
			df_edges["subgroup"] = [G.get_edge_data(*edge)["subgroup"] for edge in edges]
			df_edges.to_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)

In [21]:
# create dataset - nodes/edge data for PyTorch Geometric/DGL framework

# IMPORTANT
dict_df_groups_subgroups_ = split_groups_subgroups(df_join_raw_intensity, groups_id, subgroups_id) # Important (intesities without Log)

for data_variation in data_variations:
	if data_variation == "none":
		create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, df_join_raw_metadata)
	else:
		# dynamic graph to static graph
		create_graph_data_directed_variation(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, data_variation)

100%|██████████| 2/2 [00:00<00:00,  2.30it/s]
100%|██████████| 2/2 [00:00<00:00,  2.30it/s]
100%|██████████| 2/2 [00:00<00:00,  2.31it/s]
100%|██████████| 2/2 [00:00<00:00,  2.30it/s]
100%|██████████| 2/2 [00:00<00:00,  2.33it/s]
100%|██████████| 2/2 [00:01<00:00,  1.48it/s]
100%|██████████| 6/6 [00:05<00:00,  1.05it/s]

In [22]:
# details
list_details = []
	
for group_id in groups_id:
	subgroups_id_ = []
	for data_variation in data_variations:
		if data_variation == "none":
			subgroups_id_ += subgroups_id[group_id]
		else:
			subgroups_id_ += [data_variation]
	# print(subgroups)
	
	for subgroup_id_ in subgroups_id_:
		df_edges = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id_))

		G = nx.from_pandas_edgelist(df_edges.iloc[:, [0, 1]])
		list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), nx.density(G), np.nan, nx.is_connected(G)])

df_details = pd.DataFrame(list_details, columns=["Group", "Subgroup", "Num. nodes", "Num. edges", "Density", "Diameter", "Is connected"])
df_details.to_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp), index=False)

df_details = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp))
df_details

,Group,Subgroup,Num. nodes,Num. edges,Density,Diameter,Is connected
0,SecoAmazonas,1,559,103333,0.662557,NaN,True
1,SecoAmazonas,2,559,104793,0.671918,NaN,True
2,FrescoSanMartin,1,559,104932,0.672809,NaN,True
3,FrescoSanMartin,2,559,105894,0.678977,NaN,True
4,FrescoCusco,1,559,103348,0.662653,NaN,True
5,FrescoCusco,2,559,104638,0.670924,NaN,True
6,SecoSanMartin,1,559,102897,0.659761,NaN,True
7,SecoSanMartin,2,559,102453,0.656914,NaN,True
8,SecoCusco,1,559,102044,0.654292,NaN,True
9,SecoCusco,2,559,102392,0.656523,NaN,True
10,FrescoAmazonas,1,559,105331,0.675368,NaN,True
11,FrescoAmazonas,2,559,105722,0.677875,NaN,True