### Imports

In [ ]:
import json
import numpy as np
import pandas as pd
import pingouin as pg
import seaborn as sn

print(pg.__version__) # 0.5.3
print(pd.__version__) # 2.0.3
print(np.__version__) # 1.24.3
print(sn.__version__) # 0.13.0

from utils_MS import *

# %load_ext autotime

In [ ]:
# def run(exp):

### Parameters

In [ ]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"]

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

data_variations = params["data_variations"]
print("Data variations:", data_variations)

apply_transformation = params["apply_transformation"]
print("Apply transformation:", apply_transformation)

threshold_corr = params["threshold_corr"]
print("Threshold corr:\t", threshold_corr)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

groups_id_no = params["groups_id_no"]
print("Groups id (no):\t", groups_id_no)

In [ ]:
# Remove
# groups_id = ["LSNB", "BC", "RCC", "BPH", "PD"] # "OSA" Memory issue
# groups_id = ["AR", "BC"]

### Load dataset

In [ ]:
# read raw data
df_join_raw = pd.read_csv("experiments/input/{}_raw.csv".format(exp), index_col=0)
df_join_raw

In [ ]:
# get metadata
df_join_raw_metadata = df_join_raw.iloc[:, :2]
df_join_raw_metadata

In [ ]:
# filter by samples
columns_sample = [column for column in df_join_raw.columns if column.split("_")[0] not in groups_id_no]
df_join_raw_intensity = df_join_raw.loc[:, columns_sample]
df_join_raw_intensity = df_join_raw_intensity.iloc[:, 3:]
df_join_raw_intensity

In [ ]:
df_join_raw_intensity.info()

In [ ]:
check_dataset(df_join_raw_intensity)

### Generate graphs

In [ ]:
# Transformation (log10)

if apply_transformation:
	df_join_raw_log = log10_global(df_join_raw_intensity)
else:
	df_join_raw_log = df_join_raw_intensity.copy()
df_join_raw_log.head()

In [ ]:
check_dataset(df_join_raw_log)

In [ ]:
# split graph in groups and subgroups

""" def split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id, by_group=False):
	list_df_groups_subgroups = []
	for group in groups_id:
		df_aux = df_join_raw_log.filter(like=group)
		list_aux = []
		
		if by_group:
			list_aux.append(df_aux)
		else:
			for subgroup in subgroups_id[group]:
				list_aux.append(df_aux.filter(like="{}_{}.".format(group, subgroup)))
		list_df_groups_subgroups.append(list_aux)
	return list_df_groups_subgroups """

dict_df_groups_subgroups = split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id)
dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

In [ ]:
check_dataset(dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]])

In [ ]:
# No apply transpose for kneighbors_graph
# dict_groups_subgroups_t = dict_df_groups_subgroups.copy()

# Aplly Transpose
dict_groups_subgroups_t = transpose_global(dict_df_groups_subgroups)

dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

In [ ]:
check_dataset(dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]])

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import LedoitWolf
from sklearn.neighbors import kneighbors_graph

def correlation_ledoitwolf_global(exp, dict_groups_subgroups_t):
	dict_groups_subgroups_t_corr = {}
	for group_id, dict_groups in dict_groups_subgroups_t.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			print(group_id, subgroup_id, df_subgroup.shape)
			
			""" import numpy as np
			cov = np.cov(df_subgroup.values, rowvar=False)
			cond = np.linalg.cond(cov)
			print("Condition number:", cond, cond > 1e8) # ill-conditioned if > 1e8 (True, instable) """

			scaler = StandardScaler()
			df_subgroup_scaled = scaler.fit_transform(df_subgroup)
			lw = LedoitWolf()
			lw.fit(df_subgroup_scaled)

			# Matriz de covarianza regularizada
			cov = lw.covariance_
			std = np.sqrt(np.diag(cov))
			corr = cov / np.outer(std, std)
			matrix = pd.DataFrame(corr)
		
			dict_aux[subgroup_id] = matrix
			
			matrix.to_csv("experiments/output/{}/correlations/{}_{}.csv".format(exp, group_id, subgroup_id), index=True)
		dict_groups_subgroups_t_corr[group_id] = dict_aux
	return dict_groups_subgroups_t_corr

def correlation_kneighbors_graph_global(exp, dict_groups_subgroups_t):
	dict_groups_subgroups_t_corr = {}
	for group_id, dict_groups in dict_groups_subgroups_t.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			print(group_id, subgroup_id, df_subgroup.shape)
			
			""" import numpy as np
			cov = np.cov(df_subgroup.values, rowvar=False)
			cond = np.linalg.cond(cov)
			print("Condition number:", cond, cond > 1e8) # ill-conditioned if > 1e8 (True, instable) """
			
			k = 10
			scaler = StandardScaler()
			df_subgroup_scaled = scaler.fit_transform(df_subgroup)
			A = kneighbors_graph(
				df_subgroup_scaled, # X, X_scaled
				n_neighbors=k,
				metric="euclidean", # "cosine",
				mode="distance",
				include_self=True
			)
			matrix = pd.DataFrame(A.toarray())
		
			dict_aux[subgroup_id] = matrix
			
			matrix.to_csv("experiments/output/{}/correlations/{}_{}.csv".format(exp, group_id, subgroup_id), index=True)
		dict_groups_subgroups_t_corr[group_id] = dict_aux
	return dict_groups_subgroups_t_corr

In [17]:
# Correlation matrix (partial correlation)

# Option 1
dict_groups_subgroups_t_corr = correlation_global(exp, dict_groups_subgroups_t)

# Option 2
# dict_groups_subgroups_t_corr = correlation_ledoitwolf_global(exp, dict_groups_subgroups_t)

# Option 3
# dict_groups_subgroups_t_corr = correlation_kneighbors_graph_global(exp, dict_groups_subgroups_t)

dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

SecoAmazonas 2 (10, 1570)
SecoSanMartin 1 (10, 1570)
SecoSanMartin 2 (10, 1570)
SecoCusco 1 (10, 1570)
SecoCusco 2 (10, 1570)
FrescoAmazonas 1 (10, 1570)
FrescoAmazonas 2 (10, 1570)
FrescoSanMartin 1 (10, 1570)
FrescoSanMartin 2 (10, 1570)
FrescoCusco 1 (10, 1570)
FrescoCusco 2 (10, 1570)

,1,2,3,4,5,6,7,8,9,10,...,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570
1,1.000000,0.704602,-0.320167,-0.038865,0.239593,-0.567968,-0.244545,0.056858,-0.852965,-0.481738,...,-0.040473,0.451591,-0.045258,0.431802,0.166078,0.554277,-0.739204,0.268055,0.528724,0.061952
2,0.704602,1.000000,0.618675,0.014232,0.010438,0.426338,0.297242,0.518824,0.749953,0.395977,...,-0.123948,-0.215758,0.006370,-0.235680,-0.101648,-0.451692,0.550266,-0.425167,-0.298686,-0.032119
3,-0.320167,0.618675,1.000000,-0.291348,-0.581622,0.117181,0.337412,-0.379784,-0.279204,0.193679,...,0.025531,-0.307756,-0.294997,0.225106,0.146733,0.510637,-0.083404,0.406566,-0.152496,-0.439058
4,-0.038865,0.014232,-0.291348,1.000000,0.019735,0.606028,0.136255,-0.078050,0.245164,0.295819,...,-0.147141,-0.618918,-0.872099,-0.454202,0.139570,-0.289255,0.118428,-0.687335,0.048391,-0.955020
5,0.239593,0.010438,-0.581622,0.019735,1.000000,0.162060,0.872320,0.055605,0.138852,0.224878,...,-0.229675,-0.546217,0.200795,0.471925,-0.159981,0.496507,0.511176,0.525700,-0.855780,-0.199119

In [18]:
# Check correlation matrices

dict_groups_subgroups_t_corr

{'SecoAmazonas': {'1':           1         2         3         4         5         6         7     \
  1     1.000000  0.704602 -0.320167 -0.038865  0.239593 -0.567968 -0.244545
  2     0.704602  1.000000  0.618675  0.014232  0.010438  0.426338  0.297242
  3    -0.320167  0.618675  1.000000 -0.291348 -0.581622  0.117181  0.337412
  4    -0.038865  0.014232 -0.291348  1.000000  0.019735  0.606028  0.136255
  5     0.239593  0.010438 -0.581622  0.019735  1.000000  0.162060  0.872320
  ...        ...       ...       ...       ...       ...       ...       ...
  1566  0.554277 -0.451692  0.510637 -0.289255  0.496507  0.538973 -0.391855
  1567 -0.739204  0.550266 -0.083404  0.118428  0.511176 -0.310337 -0.497577
  1568  0.268055 -0.425167  0.406566 -0.687335  0.525700  0.497261 -0.265816
  1569  0.528724 -0.298686 -0.152496  0.048391 -0.855780  0.206766  0.809450
  1570  0.061952 -0.032119 -0.439058 -0.955020 -0.199119  0.668476  0.303385

            8         9         10    ...      1561      1562      1563  \
  1     0.056858 -0.852965 -0.481738  ... -0.040473  0.451591 -0.045258
  2     0.518824  0.749953  0.395977  ... -0.123948 -0.215758  0.006370
  3    -0.379784 -0.279204  0.193679  ...  0.025531 -0.307756 -0.294997
  4    -0.078050  0.245164  0.295819  ... -0.147141 -0.618918 -0.872099
  5     0.055605  0.138852  0.224878  ... -0.229675 -0.546217  0.200795
  ...        ...       ...       ...  ...       ...       ...       ...
  1566 -0.103229  0.601078  0.312835  ...  0.304698 -0.093079 -0.407717
  1567  0.012781 -0.628324 -0.486933  ...  0.177028  0.580951 -0.054586
  1568 -0.017569  0.449433  0.225463  ... -0.115990 -0.334026 -0.640468
  1569  0.143406  0.369987  0.169936  ... -0.246150 -0.580690  0.316394
  1570 -0.071501  0.334624  0.489369  ... -0.071824 -0.672233 -0.863296

            1564      1565      1566      1567      1568      1569      1570
  1     0.431802  0.166078  0.554277 -0.739204  0.268055  0.528724  0.061952
  2    -0.235680 -0.101648 -0.451692  0.550266 -0.425167 -0.298686 -0.032119
  3     0.225106  0.146733  0.510637 -0.083404  0.406566 -0.152496 -0.439058
  4    -0.454202  0.139570 -0.289255  0.118428 -0.687335  0.048391 -0.955020
  5     0.471925 -0.159981  0.496507  0.511176  0.525700 -0.855780 -0.199119
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.913822  0.184672  1.000000  0.097518 -0.666815  0.135673 -0.231192
  1567  0.086908  0.232552  0.097518  1.000000  0.219730  0.663897  0.251307
  1568 -0.688193 -0.017232 -0.666815  0.219730  1.000000  0.308020 -0.547092
  1569  0.242205 -0.267177  0.135673  0.663897  0.308020  1.000000 -0.122314
  1570 -0.421487  0.216369 -0.231192  0.251307 -0.547092 -0.122314  1.000000

  [1570 rows x 1570 columns],
  '2':           1         2         3         4         5         6         7     \
  1     1.000000 -0.539400  0.335917 -0.366810 -0.804846 -0.200015 -0.489636
  2    -0.539400  1.000000  0.223260 -0.168483 -0.624433  0.046685 -0.257997
  3     0.335917  0.223260  1.000000 -0.692099  0.191496  0.086495 -0.114047
  4    -0.366810 -0.168483 -0.692099  1.000000 -0.447447 -0.060331 -0.340297
  5    -0.804846 -0.624433  0.191496 -0.447447  1.000000  0.281746 -0.389480
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.562745 -0.157314  0.252079 -0.088161 -0.257350 -0.130966 -0.577910
  1567 -0.061058  0.221169 -0.114581 -0.109185  0.249207 -0.212901  0.447986
  1568 -0.683351 -0.091919  0.183198 -0.251562 -0.231005 -0.642589 -0.683214
  1569  0.492135  0.629123 -0.265712  0.011065  0.703453 -0.416195  0.027377
  1570  0.658510  0.308145 -0.680625 -0.279836  0.591200 -0.252693  0.106385

            8         9         10    ...      1561      1562      1563  \
  1    -0.757106 -0.610076 -0.383336  ...  0.773601  0.820932  0.002599
  2    -0.335560 -0.186541 -0.287272  ...  0.428605  0.570341  0.193561
  3     0.244891  0.173938  0.267676  ... -0.155441 -0.572261  0.317371
  4    -0.354012 -0.344889 -0.283008  ...  0.253512  0.011629  0.303913
  5    -0.496908 -0.194971 -0.619893  ...  0.707231  0.829617  0.381748
  ...        ...       ...       ...  ...       ...       ...       ...
  1566 -0.619120 -0.371443 -0.007151  ...  0.409575  0.278952 -0.048884
  1567  0.249375 -0.424658  0.191127  ...  0.059510 -0.118229 -0.760675
  1568 -0.896981 -0.663340 -0.012879  ...  0.388311  0.290727 -0.035552
  1569 -0.078595 -0.144409  0.218268  ... -0.694552 -0.772404 -0.172009
  1570  0.184342  0.072666  0.176936  ... -0.710083 -0.874653  0.106323

            1564      1565      1566      1567      1568      1569      1570
  1    -0.852947 -0.254790 -0.562745 -0.061058 -0.683351  0.492135  0.658510
  2    -0.358617 -0.756235 -0.157314  0.221169 -0.091919  0.629123  0.308145
  3     0.367023 -0.202462  0.252079 -0.114581  0.183198 -0.265712 -0.680625
  4    -0.283242 -0.453882 -0.088161 -0.109185 -0.251562  0.011065 -0.279836
  5    -0.677766 -0.572739 -0.257350  0.249207 -0.231005  0.703453  0.591200
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.735231  0.048640  1.000000 -0.143888 -0.695185 -0.136230  0.368291
  1567  0.153636  0.351979 -0.143888  1.000000 -0.015616 -0.084530  0.096030
  1568 -0.789941  0.175823 -0.695185 -0.015616  1.000000 -0.205148  0.197194
  1569  0.163335  0.417799 -0.136230 -0.084530 -0.205148  1.000000 -0.708600
  1570  0.512065 -0.059034  0.368291  0.096030  0.197194 -0.708600  1.000000

  [1570 rows x 1570 columns]},
 'SecoSanMartin': {'1':           1         2         3         4         5         6         7     \
  1     1.000000 -0.088965  0.061511 -0.087101  0.088085 -0.459633  0.512308
  2    -0.088965  1.000000 -0.530625  0.127019  0.711160  0.522115 -0.564097
  3     0.061511 -0.530625  1.000000 -0.550955 -0.014362  0.128001 -0.373342
  4    -0.087101  0.127019 -0.550955  1.000000 -0.592634 -0.277881  0.199567
  5     0.088085  0.711160 -0.014362 -0.592634  1.000000 -0.460166  0.582189
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.149998 -0.561276 -0.660997 -0.332128  0.251973  0.479129 -0.555339
  1567 -0.725963 -0.186894  0.236535  0.327508  0.436474 -0.392356  0.122904
  1568  0.078632 -0.553108  0.120799  0.400225  0.453870  0.667304 -0.466819
  1569 -0.347021 -0.056932  0.651152  0.331717  0.384114  0.245708  0.041699
  1570 -0.632417 -0.326590  0.400997  0.476867  0.557029  0.196005  0.103349

            8         9         10    ...      1561      1562      1563  \
  1    -0.585884 -0.527273 -0.573444  ...  0.104354  0.144005  0.684978
  2     0.012377  0.047485  0.268377  ...  0.637371  0.811905 -0.067221
  3    -0.397284 -0.271789  0.064914  ...  0.589766  0.853185 -0.567552
  4    -0.544144 -0.415466 -0.359891  ...  0.002946  0.281740 -0.453307
  5    -0.210453 -0.004216 -0.359033  ... -0.496571 -0.315351 -0.177204
  ...        ...       ...       ...  ...       ...       ...       ...
  1566 -0.008724  0.030939 -0.193525  ...  0.758276  0.511252 -0.098227
  1567 -0.173799 -0.335977 -0.230124  ...  0.289476  0.028201  0.501494
  1568  0.705198  0.715928  0.104387  ...  0.303809  0.056919  0.254345
  1569  0.345226  0.247113 -0.159994  ... -0.175070 -0.426566  0.657217
  1570  0.119595  0.064307 -0.334513  ...  0.163392 -0.070619  0.843731

            1564      1565      1566      1567      1568      1569      1570
  1    -0.463744 -0.477350 -0.149998 -0.725963  0.078632 -0.347021 -0.632417
  2    -0.428976 -0.389355 -0.561276 -0.186894 -0.553108 -0.056932 -0.326590
  3    -0.384584  0.252871 -0.660997  0.236535  0.120799  0.651152  0.400997
  4    -0.450225  0.611754 -0.332128  0.327508  0.400225  0.331717  0.476867
  5    -0.045875  0.526442  0.251973  0.436474  0.453870  0.384114  0.557029
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.272826 -0.299929  1.000000  0.003453 -0.345997  0.005565 -0.180840
  1567  0.005514 -0.591530  0.003453  1.000000 -0.173126 -0.422950 -0.576729
  1568 -0.036009 -0.684873 -0.345997 -0.173126  1.000000 -0.557619 -0.511838
  1569 -0.066806 -0.576722  0.005565 -0.422950 -0.557619  1.000000 -0.774479
  1570 -0.172279 -0.854014 -0.180840 -0.576729 -0.511838 -0.774479  1.000000

  [1570 rows x 1570 columns],
  '2':           1         2         3         4         5         6         7     \
  1     1.000000  0.037088  0.184252  0.272984  0.193693 -0.718434  0.166829
  2     0.037088  1.000000  0.389905 -0.140891 -0.619233  0.301013  0.330096
  3     0.184252  0.389905  1.000000 -0.550069  0.441641 -0.047134 -0.188158
  4     0.272984 -0.140891 -0.550069  1.000000 -0.093005  0.363068  0.252456
  5     0.193693 -0.619233  0.441641 -0.093005  1.000000  0.360311 -0.256231
  ...        ...       ...       ...       ...       ...       ...       ...
  1566  0.084791  0.812535 -0.444014 -0.072516  0.164913 -0.149159 -0.586078
  1567  0.252265  0.043330 -0.096269 -0.010929  0.049506 -0.260007 -0.058817
  1568 -0.179410 -0.491152  0.391051 -0.129721 -0.588625  0.397571  0.090954
  1569 -0.479892 -0.417870  0.380523  0.040400 -0.106488 -0.343716  0.647680
  1570  0.508129  0.023888 -0.294887 -0.480250 -0.086338  0.493027 -0.278935

            8         9         10    ...      1561      1562      1563  \
  1    -0.355345 -0.629906 -0.298292  ... -0.150790  0.515067 -0.016532
  2    -0.137501  0.173633  0.027930  ...  0.835751  0.422822  0.889761
  3     0.420630  0.250511 -0.425646  ... -0.599389 -0.465194 -0.355819
  4    -0.061452  0.477462  0.145310  ...  0.095532 -0.088535  0.178898
  5    -0.176504  0.142719  0.317131  ...  0.860450  0.067214  0.271782
  ...        ...       ...       ...  ...       ...       ...       ...
  1566  0.094161 -0.172193  0.052371  ... -0.581964 -0.613593 -0.950070
  1567  0.472856 -0.467063 -0.332477  ... -0.106104 -0.338451 -0.158919
  1568 -0.734361  0.099323  0.582565  ...  0.494718  0.203764  0.302700
  1569  0.125724 -0.231885 -0.345932  ...  0.322119  0.891799  0.488020
  1570 -0.341166  0.331275  0.530963  ...  0.021455 -0.711332 -0.063829

            1564      1565      1566      1567      1568      1569      1570
  1    -0.004385 -0.062913  0.084791  0.252265 -0.179410 -0.479892  0.508129
  2     0.031532  0.489688  0.812535  0.043330 -0.491152 -0.417870  0.023888
  3    -0.336326 -0.311392 -0.444014 -0.096269  0.391051  0.380523 -0.294887
  4    -0.338741  0.355102 -0.072516 -0.010929 -0.129721  0.040400 -0.480250
  5     0.637060  0.132183  0.164913  0.049506 -0.588625 -0.106488 -0.086338
  ...        ...       ...       ...       ...       ...       ...       ...
  1566  0.165121 -0.620790  1.000000 -0.209508  0.149657  0.550159 -0.248945
  1567 -0.273224  0.010983 -0.209508  1.000000  0.271299  0.002040 -0.109236
  1568  0.072521 -0.040044  0.149657  0.271299  1.000000  0.041022 -0.302612
  1569  0.127078  0.708754  0.550159  0.002040  0.041022  1.000000  0.777858
  1570 -0.405907 -0.277593 -0.248945 -0.109236 -0.302612  0.777858  1.000000

  [1570 rows x 1570 columns]},
 'SecoCusco': {'1':           1         2         3         4         5         6         7     \
  1     1.000000  0.733959 -0.454996  0.379144 -0.237139  0.163640  0.081948
  2     0.733959  1.000000 -0.004039 -0.241589  0.340532 -0.337654  0.284796
  3    -0.454996 -0.004039  1.000000 -0.388466  0.569360 -0.145749 -0.161521
  4     0.379144 -0.241589 -0.388466  1.000000  0.829471 -0.397114 -0.461663
  5    -0.237139  0.340532  0.569360  0.829471  1.000000  0.258666  0.415023
  ...        ...       ...       ...       ...       ...       ...       ...
  1566  0.078803 -0.374205 -0.532869 -0.099628  0.332914  0.350849 -0.337710
  1567 -0.327505  0.246769 -0.057527  0.241581 -0.030689  0.144513  0.262089
  1568  0.881299 -0.528466  0.383264 -0.593244  0.324352 -0.316977 -0.191840
  1569  0.430044  0.134664  0.520931 -0.386080 -0.076492  0.006051 -0.274521
  1570  0.027580 -0.367264 -0.637886 -0.227071  0.181120 -0.040684  0.036040

            8         9         10    ...      1561      1562      1563  \
  1     0.239709 -0.643265 -0.795936  ...  0.333537  0.557175 -0.000847
  2    -0.601289  0.411045  0.804053  ... -0.191940 -0.321082  0.337485
  3    -0.669825 -0.639312 -0.041226  ...  0.307034  0.518926  0.813991
  4    -0.553417 -0.233352  0.650122  ...  0.226057 -0.214269  0.509081
  5     0.599461  0.225800 -0.555736  ... -0.270304 -0.086602 -0.692211
  ...        ...       ...       ...  ...       ...       ...       ...
  1566 -0.524219  0.106117  0.085799  ... -0.498605  0.417573  0.617794
  1567  0.317476  0.029473 -0.373626  ...  0.573480  0.455079 -0.031670
  1568 -0.209586  0.302796  0.785185  ... -0.203735 -0.719259 -0.041587
  1569  0.310167  0.165619  0.320550  ... -0.185013 -0.669284 -0.509561
  1570 -0.779183 -0.292400  0.178830  ... -0.090480  0.107007  0.631561

            1564      1565      1566      1567      1568      1569      1570
  1    -0.010180  0.665307  0.078803 -0.327505  0.881299  0.430044  0.027580
  2    -0.313845 -0.409671 -0.374205  0.246769 -0.528466  0.134664 -0.367264
  3    -0.765678  0.096139 -0.532869 -0.057527  0.383264  0.520931 -0.637886
  4    -0.318836 -0.795080 -0.099628  0.241581 -0.593244 -0.386080 -0.227071
  5     0.452947  0.658261  0.332914 -0.030689  0.324352 -0.076492  0.181120
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.858205  0.168606  1.000000  0.231394  0.123675  0.376058 -0.649484
  1567  0.221608  0.167776  0.231394  1.000000  0.516148  0.394659  0.325252
  1568  0.081796 -0.829534  0.123675  0.516148  1.000000 -0.642471  0.015201
  1569  0.443804 -0.521118  0.376058  0.394659 -0.642471  1.000000  0.297230
  1570 -0.846594  0.105828 -0.649484  0.325252  0.015201  0.297230  1.000000

  [1570 rows x 1570 columns],
  '2':           1         2         3         4         5         6         7     \
  1     1.000000 -0.293985 -0.250620 -0.418649 -0.742968 -0.386630 -0.376571
  2    -0.293985  1.000000  0.263366 -0.144619 -0.513579 -0.020346  0.016164
  3    -0.250620  0.263366  1.000000 -0.804776 -0.217977  0.637895 -0.375929
  4    -0.418649 -0.144619 -0.804776  1.000000 -0.233876  0.491385 -0.391015
  5    -0.742968 -0.513579 -0.217977 -0.233876  1.000000 -0.052698 -0.045008
  ...        ...       ...       ...       ...       ...       ...       ...
  1566  0.124410 -0.408621 -0.154293 -0.186062 -0.309553  0.683722 -0.005054
  1567  0.335003 -0.087555 -0.560916 -0.644224  0.157591  0.820018  0.080128
  1568  0.067171  0.708774 -0.522983 -0.115114  0.090322  0.328453 -0.365362
  1569  0.312271 -0.508570  0.316699 -0.154029  0.431778  0.093967  0.061970
  1570  0.264069 -0.195454  0.830605  0.659242  0.353660 -0.597506  0.287025

            8         9         10    ...      1561      1562      1563  \
  1    -0.260878 -0.503972 -0.244742  ... -0.109853 -0.244619  0.180540
  2    -0.153182 -0.150429 -0.041096  ...  0.765369  0.550260  0.306560
  3    -0.687527  0.516570  0.670766  ... -0.304468 -0.413467  0.676621
  4    -0.901474  0.181038  0.448614  ...  0.198778 -0.023246  0.821201
  5    -0.148942 -0.027427 -0.045174  ... -0.113053  0.009463  0.354480
  ...        ...       ...       ...  ...       ...       ...       ...
  1566 -0.307885  0.457929  0.368503  ...  0.212039  0.311993  0.519569
  1567 -0.730538  0.702166  0.589017  ...  0.325341  0.367098  0.813684
  1568 -0.235314  0.356124  0.453460  ... -0.730998 -0.527202  0.139930
  1569 -0.200687 -0.137766 -0.014617  ...  0.908997  0.585641  0.131094
  1570  0.759831 -0.562507 -0.547107  ...  0.379903  0.175426 -0.780495

            1564      1565      1566      1567      1568      1569      1570
  1    -0.228453 -0.498501  0.124410  0.335003  0.067171  0.312271  0.264069
  2    -0.544535  0.171550 -0.408621 -0.087555  0.708774 -0.508570 -0.195454
  3    -0.342056  0.140505 -0.154293 -0.560916 -0.522983  0.316699  0.830605
  4    -0.577759  0.313947 -0.186062 -0.644224 -0.115114 -0.154029  0.659242
  5    -0.449780 -0.326654 -0.309553  0.157591  0.090322  0.431778  0.353660
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.788876  0.357455  1.000000 -0.393613 -0.002480 -0.127434  0.309377
  1567 -0.552045  0.833150 -0.393613  1.000000 -0.042449 -0.383630  0.546030
  1568  0.031048 -0.242695 -0.002480 -0.042449  1.000000  0.657499  0.620162
  1569 -0.239656  0.619089 -0.127434 -0.383630  0.657499  1.000000 -0.418295
  1570  0.561455 -0.195279  0.309377  0.546030  0.620162 -0.418295  1.000000

  [1570 rows x 1570 columns]},
 'FrescoAmazonas': {'1':           1         2         3         4         5         6         7     \
  1     1.000000  0.274228  0.570820 -0.166523  0.356521  0.089789  0.398340
  2     0.274228  1.000000 -0.879479  0.391545 -0.792569 -0.125502 -0.245968
  3     0.570820 -0.879479  1.000000  0.425152 -0.765718 -0.104064 -0.140778
  4    -0.166523  0.391545  0.425152  1.000000  0.307951  0.062732 -0.319145
  5     0.356521 -0.792569 -0.765718  0.307951  1.000000 -0.192095 -0.194946
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.077337 -0.467569 -0.322503 -0.464977 -0.498876  0.289464 -0.196660
  1567 -0.752217 -0.081861  0.252796 -0.378215  0.023439  0.226488  0.092749
  1568 -0.163138 -0.116965  0.045257 -0.281604 -0.272605 -0.525442 -0.362537
  1569 -0.259043 -0.011442  0.036979 -0.460901  0.116090  0.618580  0.177729
  1570 -0.192033  0.317663  0.353397 -0.618184 -0.110614  0.243294  0.022093

            8         9         10    ...      1561      1562      1563  \
  1     0.277588 -0.462441 -0.424441  ...  0.453473 -0.202201 -0.149410
  2    -0.038003 -0.129349  0.236900  ...  0.064706 -0.063177  0.152969
  3     0.085020  0.024643  0.469207  ... -0.086923 -0.121798 -0.045364
  4    -0.442269  0.418915  0.263681  ... -0.422848  0.234939  0.229715
  5    -0.241417  0.265762  0.208990  ... -0.134573 -0.261686  0.306326
  ...        ...       ...       ...  ...       ...       ...       ...
  1566 -0.229761  0.425037  0.223324  ...  0.044635 -0.179687  0.382985
  1567  0.090991 -0.033938 -0.056096  ...  0.447842 -0.276539  0.049246
  1568 -0.419564  0.084342  0.184585  ... -0.401503  0.412521  0.140402
  1569  0.126570  0.121141 -0.101017  ...  0.243263 -0.100764  0.154943
  1570 -0.260728  0.750251  0.138364  ... -0.120893 -0.187158  0.206679

            1564      1565      1566      1567      1568      1569      1570
  1    -0.537540  0.563879 -0.077337 -0.752217 -0.163138 -0.259043 -0.192033
  2    -0.048428 -0.664795 -0.467569 -0.081861 -0.116965 -0.011442  0.317663
  3     0.186406 -0.712179 -0.322503  0.252796  0.045257  0.036979  0.353397
  4    -0.423992 -0.167019 -0.464977 -0.378215 -0.281604 -0.460901 -0.618184
  5    -0.122483 -0.558409 -0.498876  0.023439 -0.272605  0.116090 -0.110614
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.576937 -0.507096  1.000000 -0.591828 -0.166791 -0.660296 -0.504704
  1567 -0.735057  0.032386 -0.591828  1.000000 -0.264382 -0.398152 -0.457573
  1568 -0.606949 -0.398310 -0.166791 -0.264382  1.000000  0.364559 -0.428698
  1569 -0.321357  0.021208 -0.660296 -0.398152  0.364559  1.000000 -0.205982
  1570 -0.685992 -0.048522 -0.504704 -0.457573 -0.428698 -0.205982  1.000000

  [1570 rows x 1570 columns],
  '2':           1         2         3         4         5         6         7     \
  1     1.000000 -0.499238 -0.205160 -0.444487 -0.007830 -0.392653 -0.222157
  2    -0.499238  1.000000 -0.803366 -0.777593 -0.681200 -0.871127 -0.677896
  3    -0.205160 -0.803366  1.000000 -0.869101 -0.897374 -0.892094 -0.891078
  4    -0.444487 -0.777593 -0.869101  1.000000 -0.766639 -0.905412 -0.771369
  5    -0.007830 -0.681200 -0.897374 -0.766639  1.000000 -0.833599 -0.723828
  ...        ...       ...       ...       ...       ...       ...       ...
  1566 -0.322424 -0.249041 -0.599676 -0.588744 -0.555909 -0.488050 -0.455976

In [19]:
check_dataset(dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][1]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 1418848
Count zero:	 232
Count positive:	 1045820
Count greater than 1:	 0
Count less than -1:	 0

In [20]:
def build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=0.3):
	dict_groups_subgroups_t_corr_g = {}
	for group_id, dict_groups in dict_groups_subgroups_t_corr.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			# Percentil Correlaciones conservadas 	Densidad
			# 50	    50 %	                    Muy densa
            # 75	    25 %	                    Densa
            # 90	    10 %	                    Moderadamente dispersa
            # 95	    5 %	                        Dispersa
            # 99	    1 %	                        Muy dispersa
			threshold = np.percentile(np.abs(df_subgroup), 90) # Change
			
			df_weighted_edges = (df_subgroup.where(np.triu(np.ones(df_subgroup.shape), k=1).astype(bool)).stack())
			df_weighted_edges = df_weighted_edges.dropna().to_frame()
			df_weighted_edges.reset_index(inplace=True)
			df_weighted_edges.columns = ["source", "target", "weight"]
			df_weighted_edges = df_weighted_edges[df_weighted_edges["weight"].abs() >= threshold]
			df_weighted_edges["subgroup"] = [subgroup_id] * len(df_weighted_edges)
			dict_aux[subgroup_id] = df_weighted_edges
			
			df_weighted_edges.to_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight"])
			# print(groups_id[i], subgroups_id[groups_id[i]][j], G.number_of_nodes(), G.number_of_edges())
			# nx.write_gexf(G, "experiments/output/{}/preprocessing/graphs/graphs_{}_{}.gexf".format(exp, groups_id[i], subgroups_id[groups_id[i]][j]))
		dict_groups_subgroups_t_corr_g[group_id] = dict_aux
	return dict_groups_subgroups_t_corr_g

In [21]:
# Build graph (corpus graphs)

# Option 1
dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)

# Option 2
# dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)

dict_groups_subgroups_t_corr_g[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

    source  target    weight subgroup
0        1       2  0.704602        1
7        1       9 -0.852965        1
9        1      11 -0.712461        1
12       1      14 -0.846706        1
14       1      16 -0.696926        1

In [22]:
def create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups, df_join_raw_metadata):	
	for group_id in tqdm(groups_id):
		for subgroup_id in tqdm(subgroups_id[group_id]):
			df_weighted_edges = pd.read_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id))
			# print(df_weighted_edges)
			G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight", "subgroup"])
			dict_id_idx = dict(zip(list(G.nodes()), range(G.number_of_nodes())))
			G = nx.relabel_nodes(G, dict_id_idx)

			df_nodes = dict_df_groups_subgroups[group_id][subgroup_id].loc[list(dict_id_idx.keys())] # A_1.1, A_1.2, A_1.3
			# from IPython.display import display
			# display(df_nodes)

			# nodes, with node features
			metadata = df_join_raw_metadata.loc[df_nodes.index] # Average Rt, Average Mz
			# intensity = df_join_raw_log.loc[df_nodes.index] # A_1.1, A_1.2, A_1.3, A_2.1, ...

			""" e = 1e-8
			mz = metadata.iloc[:, 1].values
			rt = metadata.iloc[:, 0].values
			intensity_mean = df_nodes.mean(axis=1).values
			intensity_std = df_nodes.std(axis=1).values
			intensity_cv = intensity_std / intensity_mean
			presence_ratio = (df_nodes > 0).mean(axis=1)

			mz_log = np.log10(mz + e)
			# intensity_mean_log = np.log10(intensity_mean + e)
			
			# mz_z = (mz_log - mz_log.mean()) / mz_log.std() # z-score
			rt_z = (rt - rt.mean()) / rt.std() # z-score
			# intensity_mean_z = (intensity_mean_log - intensity_mean_log.mean()) / intensity_mean_log.std() # z-score

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": mz_log,
				"rt": rt_z,
				"intensity_mean": intensity_mean,
				"intensity_std": intensity_std,
				"intensity_cv": intensity_cv,
				"presence_ratio": presence_ratio
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			# df_node_features.insert(0, "idx", list(dict_id_idx.values()))
			# df_node_features.insert(1, "id", list(dict_id_idx.keys()))
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features) """

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": metadata.iloc[:, 1].values,
				"rt": metadata.iloc[:, 0].values,
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features)

			# edges
			edges = list(G.edges())
			df_edges = pd.DataFrame(edges, columns=["source", "target"])
			df_edges["weight"] = [G.get_edge_data(*edge)["weight"] for edge in edges]
			df_edges["subgroup"] = [G.get_edge_data(*edge)["subgroup"] for edge in edges]
			df_edges.to_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)

In [23]:
# create dataset - nodes/edge data for PyTorch Geometric/DGL framework

# IMPORTANT
dict_df_groups_subgroups_ = split_groups_subgroups(df_join_raw_intensity, groups_id, subgroups_id) # Important (intesities without Log)

for data_variation in data_variations:
	if data_variation == "none":
		create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, df_join_raw_metadata)
	else:
		# dynamic graph to static graph
		create_graph_data_directed_variation(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, data_variation)

100%|██████████| 2/2 [00:01<00:00,  1.51it/s]
100%|██████████| 2/2 [00:01<00:00,  1.65it/s]
100%|██████████| 2/2 [00:01<00:00,  1.42it/s]
100%|██████████| 2/2 [00:01<00:00,  1.54it/s]
100%|██████████| 2/2 [00:01<00:00,  1.71it/s]
100%|██████████| 2/2 [00:01<00:00,  1.49it/s]
100%|██████████| 6/6 [00:07<00:00,  1.30s/it]

In [24]:
# details
list_details = []
	
for group_id in groups_id:
	subgroups_id_ = []
	for data_variation in data_variations:
		if data_variation == "none":
			subgroups_id_ += subgroups_id[group_id]
		else:
			subgroups_id_ += [data_variation]
	# print(subgroups)
	
	for subgroup_id_ in subgroups_id_:
		try:
			df_edges = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id_))

			G = nx.from_pandas_edgelist(df_edges.iloc[:, [0, 1]])
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), nx.density(G), np.nan, nx.is_connected(G)])
		except:
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), np.nan, np.nan, np.nan])

df_details = pd.DataFrame(list_details, columns=["Group", "Subgroup", "Num. nodes", "Num. edges", "Density", "Diameter", "Is connected"])
df_details.to_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp), index=False)

df_details = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp))
df_details

,Group,Subgroup,Num. nodes,Num. edges,Density,Diameter,Is connected
0,SecoAmazonas,1,1570,151874,0.123308,NaN,True
1,SecoAmazonas,2,1570,143750,0.116712,NaN,True
2,SecoSanMartin,1,1570,127429,0.103461,NaN,True
3,SecoSanMartin,2,1570,142730,0.115884,NaN,True
4,SecoCusco,1,1570,152317,0.123668,NaN,True
5,SecoCusco,2,1570,162661,0.132066,NaN,True
6,FrescoAmazonas,1,1570,137091,0.111305,NaN,True
7,FrescoAmazonas,2,1570,150536,0.122222,NaN,True
8,FrescoSanMartin,1,1570,127448,0.103476,NaN,True
9,FrescoSanMartin,2,1570,132933,0.107930,NaN,True
10,FrescoCusco,1,1570,144710,0.117491,NaN,True
11,FrescoCusco,2,1570,153174,0.124363,NaN,True