### Imports

In [1]:
import json
import numpy as np
import pandas as pd
import pingouin as pg
import seaborn as sn

print(pg.__version__) # 0.5.3
print(pd.__version__) # 2.0.3
print(np.__version__) # 1.24.3
print(sn.__version__) # 0.13.0

from utils_MS import *

# %load_ext autotime

0.5.3
2.2.2
1.26.4
0.13.2

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.6.1.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
# def run(exp):

### Parameters

In [3]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"]

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

data_variations = params["data_variations"]
print("Data variations:", data_variations)

has_transformation = params["has_transformation"]
print("Has transformation:", has_transformation)

threshold_corr = params["threshold_corr"]
print("Threshold corr:\t", threshold_corr)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

groups_id_no = params["groups_id_no"]
print("Groups id (no):\t", groups_id_no)

Exp:		 exp11
Data variations: ['none']
Has transformation: True
Threshold corr:	 0.5
Groups id:	 ['AR', 'CRS', 'OSA', 'LPRD', 'SGB', 'LSNB', 'RCC', 'BC', 'BPH', 'PCa', 'PD']
Subgroups id:	 {'AR': ['1', '2'], 'CRS': ['1', '2'], 'OSA': ['1', '2'], 'LPRD': ['1', '2'], 'SGB': ['1', '2'], 'LSNB': ['1', '2'], 'RCC': ['1', '2'], 'BC': ['1', '2'], 'BPH': ['1', '2'], 'PCa': ['1', '2'], 'PD': ['1', '2']}
Groups id (no):	 ['Blank', 'QC', 'Std']

In [4]:
# Remove
# groups_id = ["OSA"]

### Load dataset

In [5]:
# read raw data
df_join_raw = pd.read_csv("experiments/input/{}_raw.csv".format(exp), index_col=0)
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
0,1,69.99951,Unknown,3.761231,0.006085,0.013273,3.028029e-02,0.039917,0.050244,0.061227,...,9.724785,0.141547,0.982856,2.836874,2.701034,0.902734,2.906096,1.066105,0.080514,0.084062
1,1,70.04025,Unknown,330.902463,3.345954,7.288531,1.660198e+01,21.875098,27.522634,33.526638,...,1120.030889,929.073344,402.726307,1160.112216,1104.663489,369.947418,1188.392767,436.767183,27220.117777,114.051237
2,1,70.04151,Unknown,3.810483,0.323929,0.609776,1.190282e+00,1.489258,1.794734,2.106832,...,47.784825,87.042228,13.025668,30.770177,29.569910,12.157380,31.378343,13.913295,3.330658,71.881975
3,1,70.04908,Unknown,371.971786,0.779920,1.640930,3.603131e+00,4.689429,5.839962,7.051638,...,245.177154,51.237744,73.230163,201.238003,192.039249,67.524286,205.915956,79.133432,4.764968,4.997353
4,1,70.06267,Unknown,14.383680,0.705716,1.341343,1.985821e+00,2.645148,3.321009,4.013655,...,398.483185,24.863943,23.424482,56.887913,54.609726,21.803690,58.041683,25.084185,13.415288,598.177399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1,732.79951,Unknown,163.972116,0.257935,0.408037,6.627199e-01,0.779651,17223.840695,0.892606,...,9.504735,7.849464,3.397348,6.601916,6.400000,3.210185,6.703166,3.585089,1.286116,1.508308
5440,1,748.76437,Unknown,5.318633,0.037041,0.088542,2.225000e-01,0.302977,0.391787,0.488619,...,14.683176,12.248418,7.863031,25.008636,23.659197,7.150230,25.699223,8.610731,1.600811,1.899722
5441,1,794.79590,Unknown,44.796079,0.062477,0.158303,4.230776e-01,0.588125,0.773695,0.979264,...,10.908876,9.339637,16.326008,57.273009,53.944851,14.716346,58.983427,18.026856,2.112711,2.430245
5442,1,800.81295,Unknown,32.469829,0.091943,0.246786,7.009871e-01,0.994535,1.330761,1.709149,...,21.954321,19.337485,35.798102,132.791415,124.703890,32.144006,136.955665,39.678934,5.750558,6.534013
5443,1,860.74167,Unknown,87.570938,0.016108,0.035769,1.076763e+06,0.083146,0.110301,0.139566,...,3.511721,2.885426,1.856864,5.696263,5.411031,1.694923,5.841845,2.025629,0.453388,0.526466

In [6]:
# get metadata
df_join_raw_metadata = df_join_raw.iloc[:, :2]
df_join_raw_metadata

      Average Rt  Average Mz
0              1    69.99951
1              1    70.04025
2              1    70.04151
3              1    70.04908
4              1    70.06267
...          ...         ...
5439           1   732.79951
5440           1   748.76437
5441           1   794.79590
5442           1   800.81295
5443           1   860.74167

[5444 rows x 2 columns]

In [7]:
# filter by samples
columns_sample = [column for column in df_join_raw.columns if column.split("_")[0] not in groups_id_no]
df_join_raw_intensity = df_join_raw.loc[:, columns_sample]
df_join_raw_intensity = df_join_raw_intensity.iloc[:, 3:]
df_join_raw_intensity

,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,AR_1.8,AR_1.9,AR_1.10,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
0,3.761231,0.006085,0.013273,3.028029e-02,0.039917,0.050244,0.061227,0.072840,0.125291,0.170628,...,9.724785,0.141547,0.982856,2.836874,2.701034,0.902734,2.906096,1.066105,0.080514,0.084062
1,330.902463,3.345954,7.288531,1.660198e+01,21.875098,27.522634,33.526638,39.873100,68.517262,93.256691,...,1120.030889,929.073344,402.726307,1160.112216,1104.663489,369.947418,1188.392767,436.767183,27220.117777,114.051237
2,3.810483,0.323929,0.609776,1.190282e+00,1.489258,1.794734,2.106832,2.425549,3.765650,4.837489,...,47.784825,87.042228,13.025668,30.770177,29.569910,12.157380,31.378343,13.913295,3.330658,71.881975
3,371.971786,0.779920,1.640930,3.603131e+00,4.689429,5.839962,7.051638,8.322044,13.959504,18.740449,...,245.177154,51.237744,73.230163,201.238003,192.039249,67.524286,205.915956,79.133432,4.764968,4.997353
4,14.383680,0.705716,1.341343,1.985821e+00,2.645148,3.321009,4.013655,4.723131,7.726094,10.145653,...,398.483185,24.863943,23.424482,56.887913,54.609726,21.803690,58.041683,25.084185,13.415288,598.177399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,163.972116,0.257935,0.408037,6.627199e-01,0.779651,17223.840695,0.892606,1.002628,1.321296,1.629596,...,9.504735,7.849464,3.397348,6.601916,6.400000,3.210185,6.703166,3.585089,1.286116,1.508308
5440,5.318633,0.037041,0.088542,2.225000e-01,0.302977,0.391787,0.488619,0.593280,1.087502,1.535642,...,14.683176,12.248418,7.863031,25.008636,23.659197,7.150230,25.699223,8.610731,1.600811,1.899722
5441,44.796079,0.062477,0.158303,4.230776e-01,0.588125,0.773695,0.979264,1.204537,2.299270,2.962102,...,10.908876,9.339637,16.326008,57.273009,53.944851,14.716346,58.983427,18.026856,2.112711,2.430245
5442,32.469829,0.091943,0.246786,7.009871e-01,0.994535,1.330761,1.709149,2.129512,4.230971,6.255039,...,21.954321,19.337485,35.798102,132.791415,124.703890,32.144006,136.955665,39.678934,5.750558,6.534013
5443,87.570938,0.016108,0.035769,1.076763e+06,0.083146,0.110301,0.139566,0.170840,0.314833,0.441631,...,3.511721,2.885426,1.856864,5.696263,5.411031,1.694923,5.841845,2.025629,0.453388,0.526466

In [8]:
df_join_raw_intensity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5444 entries, 0 to 5443
Columns: 308 entries, AR_1.1 to PD_2.14
dtypes: float64(308)
memory usage: 12.8 MB

In [9]:
check_dataset(df_join_raw_intensity)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 1676752
Count greater than 1:	 1614821
Count less than -1:	 0

### Generate graphs

In [10]:
# Transformation (log10)

if not has_transformation:
	df_join_raw_log = log10_global(df_join_raw_intensity)
else:
	df_join_raw_log = df_join_raw_intensity.copy()
df_join_raw_log.head()

,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,AR_1.8,AR_1.9,AR_1.10,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
0,3.761231,0.006085,0.013273,0.030280,0.039917,0.050244,0.061227,0.072840,0.125291,0.170628,...,9.724785,0.141547,0.982856,2.836874,2.701034,0.902734,2.906096,1.066105,0.080514,0.084062
1,330.902463,3.345954,7.288531,16.601984,21.875098,27.522634,33.526638,39.873100,68.517262,93.256691,...,1120.030889,929.073344,402.726307,1160.112216,1104.663489,369.947418,1188.392767,436.767183,27220.117777,114.051237
2,3.810483,0.323929,0.609776,1.190282,1.489258,1.794734,2.106832,2.425549,3.765650,4.837489,...,47.784825,87.042228,13.025668,30.770177,29.569910,12.157380,31.378343,13.913295,3.330658,71.881975
3,371.971786,0.779920,1.640930,3.603131,4.689429,5.839962,7.051638,8.322044,13.959504,18.740449,...,245.177154,51.237744,73.230163,201.238003,192.039249,67.524286,205.915956,79.133432,4.764968,4.997353
4,14.383680,0.705716,1.341343,1.985821,2.645148,3.321009,4.013655,4.723131,7.726094,10.145653,...,398.483185,24.863943,23.424482,56.887913,54.609726,21.803690,58.041683,25.084185,13.415288,598.177399

In [11]:
check_dataset(df_join_raw_log)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 1676752
Count greater than 1:	 1614821
Count less than -1:	 0

In [12]:
# split graph in groups and subgroups

""" def split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id, by_group=False):
	list_df_groups_subgroups = []
	for group in groups_id:
		df_aux = df_join_raw_log.filter(like=group)
		list_aux = []
		
		if by_group:
			list_aux.append(df_aux)
		else:
			for subgroup in subgroups_id[group]:
				list_aux.append(df_aux.filter(like="{}_{}.".format(group, subgroup)))
		list_df_groups_subgroups.append(list_aux)
	return list_df_groups_subgroups """

dict_df_groups_subgroups = split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id)
dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,AR_1.8,AR_1.9,AR_1.10,AR_1.11,AR_1.12,AR_1.13,AR_1.14
0,3.761231,0.006085,0.013273,0.030280,0.039917,0.050244,0.061227,0.072840,0.125291,0.170628,0.186844,0.203610,0.238759,0.257140
1,330.902463,3.345954,7.288531,16.601984,21.875098,27.522634,33.526638,39.873100,68.517262,93.256691,102.103352,111.247433,130.412734,140.433267
2,3.810483,0.323929,0.609776,1.190282,1.489258,1.794734,2.106832,2.425549,3.765650,4.837489,5.207149,5.582902,6.352578,6.746368
3,371.971786,0.779920,1.640930,3.603131,4.689429,5.839962,7.051638,8.322044,13.959504,18.740449,20.435723,22.180943,25.818440,27.710860
4,14.383680,0.705716,1.341343,1.985821,2.645148,3.321009,4.013655,4.723131,7.726094,10.145653,10.983228,11.835865,13.585950,14.483382

In [13]:
check_dataset(dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 76216
Count greater than 1:	 67552
Count less than -1:	 0

In [14]:
# Transpose
dict_groups_subgroups_t = transpose_global(dict_df_groups_subgroups)
dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,3.761231,330.902463,3.810483,371.971786,14.383680,18.712422,417.147841,436.415332,447.095192,546.474624,...,44.344524,97.694474,0.490535,17.259174,74.363530,163.972116,5.318633,44.796079,32.469829,8.757094e+01
1,0.006085,3.345954,0.323929,0.779920,0.705716,1.268849,2.415183,2.922806,2.590657,3.762704,...,1.133287,0.837684,0.009950,0.498310,0.545720,0.257935,0.037041,0.062477,0.091943,1.610831e-02
2,0.013273,7.288531,0.609776,1.640930,1.341343,2.303828,4.318272,5.183582,4.703271,6.515834,...,2.634693,1.662149,0.023167,1.027306,0.918777,0.408037,0.088542,0.158303,0.246786,3.576926e-02
3,0.030280,16.601984,1.190282,3.603131,1.985821,4.328725,7.982704,9.500140,8.835680,11.644745,...,6.429097,3.430283,0.056623,2.207598,1.593786,0.662720,0.222500,0.423078,0.700987,1.076763e+06
4,0.039917,21.875098,1.489258,4.689429,2.645148,5.347244,9.807538,11.638044,10.914152,14.145230,...,8.668621,4.372804,0.076389,2.852594,1.916814,0.779651,0.302977,0.588125,0.994535,8.314574e-02

In [15]:
check_dataset(dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 0
Count zero:	 0
Count positive:	 76216
Count greater than 1:	 67552
Count less than -1:	 0

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import LedoitWolf

def correlation_ledoitwolf_global(exp, dict_groups_subgroups_t):
	dict_groups_subgroups_t_corr = {}
	for group_id, dict_groups in dict_groups_subgroups_t.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			print(group_id, subgroup_id, df_subgroup.shape)
			
			""" import numpy as np
			cov = np.cov(df_subgroup.values, rowvar=False)
			cond = np.linalg.cond(cov)
			print("Condition number:", cond, cond > 1e8) # ill-conditioned if > 1e8 (True, instable) """

			scaler = StandardScaler()
			df_subgroup_scaled = scaler.fit_transform(df_subgroup)
			lw = LedoitWolf()
			lw.fit(df_subgroup_scaled)

			# Matriz de covarianza regularizada
			cov = lw.covariance_
			std = np.sqrt(np.diag(cov))
			corr = cov / np.outer(std, std)
			matrix = pd.DataFrame(corr)
		
			dict_aux[subgroup_id] = matrix
			
			matrix.to_csv("experiments/output/{}/correlations/{}_{}.csv".format(exp, group_id, subgroup_id), index=True)
		dict_groups_subgroups_t_corr[group_id] = dict_aux
	return dict_groups_subgroups_t_corr

In [ ]:
# Correlation matrix (partial correlation)

# dict_groups_subgroups_t_corr = correlation_global(exp, dict_groups_subgroups_t)
dict_groups_subgroups_t_corr = exp, dict_groups_subgroups_t)
dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

AR 1 (14, 5444)
AR 2 (14, 5444)
CRS 1 (14, 5444)
CRS 2 (14, 5444)
OSA 1 (14, 5444)
OSA 2 (14, 5444)
LPRD 1 (14, 5444)
LPRD 2 (14, 5444)
SGB 1 (14, 5444)
SGB 2 (14, 5444)
LSNB 1 (14, 5444)
LSNB 2 (14, 5444)
RCC 1 (14, 5444)
RCC 2 (14, 5444)
BC 1 (14, 5444)
BC 2 (14, 5444)
BPH 1 (14, 5444)
BPH 2 (14, 5444)
PCa 1 (14, 5444)
PCa 2 (14, 5444)
PD 1 (14, 5444)
PD 2 (14, 5444)

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,1.000000,0.382173,0.066751,0.432721,0.205697,0.173611,0.432547,0.432345,0.432405,-0.027422,...,0.125416,-0.021136,0.176524,-0.017027,0.432668,-0.040082,0.373306,0.432048,0.405906,-0.043522
1,0.382173,1.000000,0.259127,0.383676,0.360139,0.338495,0.387631,0.390108,0.389542,-0.013739,...,0.304971,0.044935,0.341162,0.072364,0.384305,-0.067033,0.432270,0.392880,0.428542,-0.092573
2,0.066751,0.259127,1.000000,0.069968,0.407523,0.418085,0.078800,0.084392,0.083059,0.027286,...,0.427014,0.131039,0.416097,0.175116,0.071691,-0.067630,0.272721,0.090286,0.209085,-0.121315
3,0.432721,0.383676,0.069968,1.000000,0.208543,0.176595,0.432629,0.432471,0.432520,-0.027034,...,0.128487,-0.020105,0.179452,-0.015775,0.432698,-0.040477,0.374915,0.432213,0.406990,-0.044408
4,0.205697,0.360139,0.407523,0.208543,1.000000,0.430165,0.216239,0.221134,0.219989,0.012852,...,0.423412,0.110318,0.430940,0.152349,0.209886,-0.078206,0.369530,0.226514,0.323945,-0.127753

In [18]:
# Check correlation matrices

dict_groups_subgroups_t_corr

{'AR': {'1':           0         1         2         3         4         5         6     \
  0     1.000000  0.382173  0.066751  0.432721  0.205697  0.173611  0.432547
  1     0.382173  1.000000  0.259127  0.383676  0.360139  0.338495  0.387631
  2     0.066751  0.259127  1.000000  0.069968  0.407523  0.418085  0.078800
  3     0.432721  0.383676  0.069968  1.000000  0.208543  0.176595  0.432629
  4     0.205697  0.360139  0.407523  0.208543  1.000000  0.430165  0.216239
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.040082 -0.067033 -0.067630 -0.040477 -0.078206 -0.068315 -0.041095
  5440  0.373306  0.432270  0.272721  0.374915  0.369530  0.348624  0.379118
  5441  0.432048  0.392880  0.090286  0.432213  0.226514  0.195170  0.432507
  5442  0.405906  0.428542  0.209085  0.406990  0.323945  0.298115  0.409736
  5443 -0.043522 -0.092573 -0.121315 -0.044408 -0.127753 -0.123218 -0.046797

            7         8         9     ...      5434      5435      5436  \
  0     0.432345  0.432405 -0.027422  ...  0.125416 -0.021136  0.176524
  1     0.390108  0.389542 -0.013739  ...  0.304971  0.044935  0.341162
  2     0.084392  0.083059  0.027286  ...  0.427014  0.131039  0.416097
  3     0.432471  0.432520 -0.027034  ...  0.128487 -0.020105  0.179452
  4     0.221134  0.219989  0.012852  ...  0.423412  0.110318  0.430940
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.041819 -0.041769 -0.038827  ... -0.077944  0.028411 -0.079681
  5440  0.381791  0.381190 -0.015779  ...  0.317640  0.049921  0.352088
  5441  0.432618  0.432608 -0.025635  ...  0.148349 -0.014189  0.198312
  5442  0.411479  0.411102 -0.023547  ...  0.260880  0.026255  0.302233
  5443 -0.048295 -0.047949 -0.033741  ... -0.122440 -0.033347 -0.122499

            5437      5438      5439      5440      5441      5442      5443
  0    -0.017027  0.432668 -0.040082  0.373306  0.432048  0.405906 -0.043522
  1     0.072364  0.384305 -0.067033  0.432270  0.392880  0.428542 -0.092573
  2     0.175116  0.071691 -0.067630  0.272721  0.090286  0.209085 -0.121315
  3    -0.015775  0.432698 -0.040477  0.374915  0.432213  0.406990 -0.044408
  4     0.152349  0.209886 -0.078206  0.369530  0.226514  0.323945 -0.127753
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.038413 -0.039650  1.000000 -0.070133 -0.044222 -0.063037 -0.038448
  5440  0.081611  0.375495 -0.070133  1.000000  0.384951  0.425923 -0.095347
  5441 -0.005738  0.432220 -0.044222  0.384951  1.000000  0.413665 -0.049866
  5442  0.051794  0.407279 -0.063037  0.425923  0.413665  1.000000 -0.079672
  5443 -0.033294 -0.044919 -0.038448 -0.095347 -0.049866 -0.079672  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000 -0.059499  0.166845  0.043961 -0.093718 -0.086375 -0.086639
  1    -0.059499  1.000000  0.110230 -0.025142 -0.055641 -0.051331 -0.051521
  2     0.166845  0.110230  1.000000 -0.081277 -0.119765 -0.099971 -0.095865
  3     0.043961 -0.025142 -0.081277  1.000000  0.319256  0.311164  0.311005
  4    -0.093718 -0.055641 -0.119765  0.319256  1.000000  0.456959  0.456880
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.433689 -0.065449  0.211330  0.104962  0.004225  0.010952  0.012956
  5440  0.449725 -0.056535  0.186043  0.059455 -0.064140 -0.057206 -0.057879
  5441  0.372043 -0.004567  0.190662  0.155014  0.100022  0.108835  0.112275
  5442  0.345583 -0.072544  0.151001  0.206132  0.172824  0.180458  0.184098
  5443  0.434040 -0.051710  0.193862  0.056167 -0.066993 -0.060639 -0.061117

            7         8         9     ...      5434      5435      5436  \
  0    -0.102310 -0.105557  0.031800  ...  0.344628  0.411164  0.013068
  1    -0.060836 -0.062761 -0.070000  ... -0.009617 -0.078837  0.006736
  2    -0.097408 -0.093978 -0.069933  ...  0.120000  0.177297 -0.123519
  3     0.297620  0.305221  0.317684  ...  0.213582  0.156886  0.019598
  4     0.439116  0.427757  0.418664  ...  0.164960  0.079629  0.109933
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.003166 -0.008177  0.112951  ...  0.387485  0.448442 -0.052788
  5440 -0.073206 -0.076691  0.053738  ...  0.336019  0.414601 -0.029985
  5441  0.089147  0.080600  0.235150  ...  0.446713  0.441061  0.033820
  5442  0.162273  0.153081  0.287182  ...  0.448544  0.442206  0.027926
  5443 -0.074975 -0.078020  0.068516  ...  0.332384  0.406064 -0.037233

            5437      5438      5439      5440      5441      5442      5443
  0    -0.104910  0.436833  0.433689  0.449725  0.372043  0.345583  0.434040
  1     0.070036 -0.058554 -0.065449 -0.056535 -0.004567 -0.072544 -0.051710
  2    -0.010196  0.206249  0.211330  0.186043  0.190662  0.151001  0.193862
  3     0.015729  0.100444  0.104962  0.059455  0.155014  0.206132  0.056167
  4     0.096077 -0.006201  0.004225 -0.064140  0.100022  0.172824 -0.066993
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.096598  0.457331  1.000000  0.439360  0.414746  0.406873  0.424451
  5440 -0.127003  0.439725  0.439360  1.000000  0.372304  0.348260  0.451042
  5441 -0.017315  0.425595  0.414746  0.372304  1.000000  0.447007  0.377202
  5442 -0.011064  0.411570  0.406873  0.348260  0.447007  1.000000  0.345412
  5443 -0.125133  0.431467  0.424451  0.451042  0.377202  0.345412  1.000000

  [5444 rows x 5444 columns]},
 'CRS': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.074345  0.404392  0.403694  0.155703  0.404100  0.404207
  1    -0.074345  1.000000 -0.068682 -0.082154 -0.091662 -0.079828 -0.078757
  2     0.404392 -0.068682  1.000000  0.403066  0.152349  0.403622  0.403787
  3     0.403694 -0.082154  0.403066  1.000000  0.162413  0.404441  0.404385
  4     0.155703 -0.091662  0.152349  0.162413  1.000000  0.160520  0.159787
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.232755 -0.063959 -0.236500 -0.216878 -0.040669 -0.221372 -0.222915
  5440 -0.150829  0.108776 -0.152637 -0.143453 -0.030219 -0.146296 -0.146957
  5441 -0.219389 -0.104646 -0.221939 -0.211053 -0.047782 -0.212882 -0.213820
  5442 -0.260535 -0.076065 -0.263966 -0.246645 -0.052662 -0.250339 -0.251737
  5443 -0.190795 -0.049986 -0.194145 -0.175738 -0.031112 -0.180100 -0.181528

            7         8         9     ...      5434      5435      5436  \
  0     0.404177  0.404003  0.404212  ... -0.250014 -0.255903 -0.181705
  1    -0.079066 -0.080456 -0.078402  ...  0.002418 -0.065595 -0.102188
  2     0.403740  0.403492  0.403827  ... -0.253083 -0.259425 -0.183765
  3     0.404403  0.404468  0.404365  ... -0.235558 -0.241042 -0.176109
  4     0.159995  0.160972  0.159066  ... -0.056640 -0.042632 -0.038883
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.222450 -0.220460 -0.222596  ...  0.363667  0.382029  0.167792
  5440 -0.146771 -0.145333 -0.147085  ...  0.093126 -0.001099 -0.040130
  5441 -0.213540 -0.211584 -0.213894  ...  0.135292  0.331208  0.391686
  5442 -0.251317 -0.249088 -0.251579  ...  0.296845  0.401964  0.297261
  5443 -0.181095 -0.179542 -0.181122  ...  0.373339  0.340460  0.076034

            5437      5438      5439      5440      5441      5442      5443
  0    -0.252562 -0.234794 -0.232755 -0.150829 -0.219389 -0.260535 -0.190795
  1     0.002134 -0.108913 -0.063959  0.108776 -0.104646 -0.076065 -0.049986
  2    -0.254954 -0.237950 -0.236500 -0.152637 -0.221939 -0.263966 -0.194145
  3    -0.244208 -0.223599 -0.216878 -0.143453 -0.211053 -0.246645 -0.175738
  4    -0.064851 -0.047511 -0.040669 -0.030219 -0.047782 -0.052662 -0.031112
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.223695  0.315936  1.000000 -0.011477  0.250359  0.370027  0.391972
  5440  0.153990 -0.049189 -0.011477  1.000000 -0.049301 -0.010526 -0.032456
  5441  0.068135  0.392743  0.250359 -0.049301  1.000000  0.353769  0.169102
  5442  0.176471  0.386617  0.370027 -0.010526  0.353769  1.000000  0.320243
  5443  0.230134  0.248175  0.391972 -0.032456  0.169102  0.320243  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000  0.028869 -0.065568 -0.216901 -0.220752 -0.217290 -0.218776
  1     0.028869  1.000000 -0.102394  0.033976  0.037762  0.034885  0.035513
  2    -0.065568 -0.102394  1.000000  0.025511  0.025338  0.025299  0.025852
  3    -0.216901  0.033976  0.025511  1.000000  0.396767  0.396915  0.396895
  4    -0.220752  0.037762  0.025338  0.396767  1.000000  0.396806  0.396862
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.063625 -0.084716  0.141103  0.164231  0.163437  0.164165  0.163916
  5440 -0.057615 -0.070229  0.101318  0.116862  0.116803  0.116526  0.116990
  5441 -0.087728 -0.053515  0.110032  0.221777  0.221171  0.221723  0.221507
  5442 -0.076629 -0.059098  0.121050  0.194853  0.194759  0.194914  0.194774
  5443 -0.080492 -0.096591  0.128018  0.179303  0.179165  0.179414  0.179213

            7         8         9     ...      5434      5435      5436  \
  0    -0.218514 -0.217637 -0.217442  ... -0.103718 -0.080211 -0.228845
  1     0.035433  0.035069  0.035000  ... -0.028071 -0.065468  0.032915
  2     0.025748  0.025428  0.025355  ...  0.108490  0.137805  0.030728
  3     0.396900  0.396912  0.396914  ...  0.220007  0.188775  0.396133
  4     0.396855  0.396823  0.396815  ...  0.220198  0.188807  0.396396
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.163960  0.164119  0.164148  ...  0.373685  0.392722  0.161951
  5440  0.116911  0.116648  0.116589  ...  0.359729  0.343995  0.121364
  5441  0.221547  0.221687  0.221712  ...  0.385894  0.387941  0.219413
  5442  0.194802  0.194900  0.194916  ...  0.380556  0.391653  0.192757
  5443  0.179253  0.179385  0.179409  ...  0.357231  0.380695  0.176798

            5437      5438      5439      5440      5441      5442      5443
  0    -0.138665 -0.077939 -0.063625 -0.057615 -0.087728 -0.076629 -0.080492
  1     0.070575 -0.072198 -0.084716 -0.070229 -0.053515 -0.059098 -0.096591
  2     0.040968  0.101113  0.141103  0.101318  0.110032  0.121050  0.128018
  3     0.315987  0.156460  0.164231  0.116862  0.221777  0.194853  0.179303
  4     0.317044  0.157476  0.163437  0.116803  0.221171  0.194759  0.179165
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.240253  0.361218  1.000000  0.345665  0.380823  0.383377  0.376892
  5440  0.186179  0.375481  0.345665  1.000000  0.346417  0.348256  0.334243
  5441  0.290121  0.364211  0.380823  0.346417  1.000000  0.394240  0.365871
  5442  0.284647  0.363457  0.383377  0.348256  0.394240  1.000000  0.372021
  5443  0.280607  0.355430  0.376892  0.334243  0.365871  0.372021  1.000000

  [5444 rows x 5444 columns]},
 'OSA': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.022149 -0.185884 -0.177055 -0.176883 -0.176207 -0.177611
  1    -0.022149  1.000000 -0.062895 -0.092154 -0.092759 -0.093322 -0.091020
  2    -0.185884 -0.062895  1.000000  0.458732  0.458773  0.458373  0.458958
  3    -0.177055 -0.092154  0.458732  1.000000  0.460731  0.460730  0.460743
  4    -0.176883 -0.092759  0.458773  0.460731  1.000000  0.460701  0.460718
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.059764  0.112997  0.086262  0.074692  0.073625  0.072697  0.075922
  5440 -0.125251  0.237461  0.137387  0.119906  0.119002  0.118188  0.121471
  5441 -0.067786  0.313305  0.068460  0.053664  0.052358  0.052667  0.054503
  5442 -0.070819  0.268280  0.101072  0.088781  0.087487  0.087836  0.089477
  5443 -0.063078  0.271926  0.080350  0.068232  0.067009  0.067475  0.068929

            7         8         9     ...      5434      5435      5436  \
  0    -0.176955 -0.176330 -0.176268  ... -0.076762 -0.091712 -0.184949
  1    -0.092082 -0.093691 -0.093864  ...  0.318977  0.277087 -0.072667
  2     0.458731  0.458475  0.458447  ...  0.082139  0.134223  0.460436
  3     0.460753  0.460745  0.460744  ...  0.065272  0.120547  0.459372
  4     0.460734  0.460723  0.460721  ...  0.063959  0.119194  0.459509
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.074558  0.073790  0.073716  ...  0.340352  0.349117  0.079113
  5440  0.119829  0.118763  0.118656  ...  0.402940  0.420102  0.128422
  5441  0.053616  0.052786  0.052699  ...  0.453579  0.447132  0.059718
  5442  0.088727  0.088026  0.087953  ...  0.443674  0.439438  0.093148
  5443  0.068198  0.067522  0.067451  ...  0.439180  0.434695  0.072871

            5437      5438      5439      5440      5441      5442      5443
  0    -0.059175 -0.093205 -0.059764 -0.125251 -0.067786 -0.070819 -0.063078
  1    -0.037303  0.279844  0.112997  0.237461  0.313305  0.268280  0.271926
  2    -0.087284  0.112698  0.086262  0.137387  0.068460  0.101072  0.080350
  3    -0.097962  0.096975  0.074692  0.119906  0.053664  0.088781  0.068232
  4    -0.094825  0.095680  0.073625  0.119002  0.052358  0.087487  0.067009
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.090574  0.360579  1.000000  0.346604  0.354864  0.384138  0.387043
  5440 -0.117267  0.436972  0.346604  1.000000  0.393962  0.379237  0.387625
  5441 -0.103291  0.441589  0.354864  0.393962  1.000000  0.453016  0.447927
  5442 -0.107850  0.432060  0.384138  0.379237  0.453016  1.000000  0.449442
  5443 -0.093465  0.432564  0.387043  0.387625  0.447927  0.449442  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000 -0.219922  0.158579  0.376055  0.375878  0.375993  0.376000
  1    -0.219922  1.000000 -0.074511 -0.221027 -0.221639 -0.219844 -0.223281
  2     0.158579 -0.074511  1.000000  0.158696  0.158003  0.158531  0.157769
  3     0.376055 -0.221027  0.158696  1.000000  0.375874  0.375978  0.376015
  4     0.375878 -0.221639  0.158003  0.375874  1.000000  0.376024  0.375975
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.052008 -0.094958 -0.071147 -0.051221 -0.053188 -0.053075 -0.050968
  5440 -0.084633 -0.057936 -0.040251 -0.084383 -0.083712 -0.084120 -0.083394
  5441 -0.006121 -0.054154 -0.066349 -0.005554 -0.009745 -0.008606 -0.006950
  5442  0.087711 -0.072741 -0.063720  0.088372  0.084516  0.085672  0.086927
  5443  0.375289 -0.232190  0.154323  0.375381  0.375234  0.375183  0.375534

            7         8         9     ...      5434      5435      5436  \
  0     0.375813  0.376047  0.376053  ... -0.069218 -0.010688  0.375838
  1    -0.222075 -0.218776 -0.219320  ... -0.099650 -0.107714 -0.225883
  2     0.157696  0.158825  0.158700  ... -0.064557 -0.074757  0.156203
  3     0.375826  0.376027  0.376038  ... -0.068247 -0.010073  0.375894
  4     0.375860  0.375923  0.375927  ... -0.074665 -0.013926  0.375737
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.054029 -0.052645 -0.052335  ...  0.241752  0.361516 -0.049652
  5440 -0.085349 -0.084461 -0.084316  ...  0.174835  0.248040 -0.082342
  5441 -0.008753 -0.007149 -0.006964  ...  0.189996  0.206430 -0.006823
  5442  0.085682  0.086969  0.087110  ...  0.155180  0.281318  0.086615
  5443  0.375196  0.375158  0.375220  ... -0.057792 -0.003393  0.375821

            5437      5438      5439      5440      5441      5442      5443
  0    -0.158751 -0.072631 -0.052008 -0.084633 -0.006121  0.087711  0.375289
  1     0.114625 -0.063561 -0.094958 -0.057936 -0.054154 -0.072741 -0.232190
  2    -0.071653 -0.041531 -0.071147 -0.040251 -0.066349 -0.063720  0.154323
  3    -0.158676 -0.072409 -0.051221 -0.084383 -0.005554  0.088372  0.375381
  4    -0.157224 -0.071516 -0.053188 -0.083712 -0.009745  0.084516  0.375234
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.103050  0.283524  1.000000  0.285708  0.186038  0.250894 -0.042610
  5440  0.046423  0.375232  0.285708  1.000000 -0.049950  0.071438 -0.076424
  5441  0.044046 -0.052942  0.186038 -0.049950  1.000000  0.284632 -0.004533
  5442 -0.051191  0.069815  0.250894  0.071438  0.284632  1.000000  0.087960
  5443 -0.149419 -0.064648 -0.042610 -0.076424 -0.004533  0.087960  1.000000

  [5444 rows x 5444 columns]},
 'LPRD': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.170350  0.344378  0.342521  0.343407  0.342730  0.343131
  1    -0.170350  1.000000 -0.169095 -0.173424 -0.172673 -0.173300 -0.173082
  2     0.344378 -0.169095  1.000000  0.341307  0.342469  0.341575  0.342096
  3     0.342521 -0.173424  0.341307  1.000000  0.344396  0.344522  0.344476
  4     0.343407 -0.172673  0.342469  0.344396  1.000000  0.344449  0.344514
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.034052 -0.032112  0.036403  0.019808  0.022489  0.020941  0.021940
  5440  0.060749 -0.093801  0.065784  0.047180  0.051538  0.048441  0.049952
  5441 -0.127453  0.020639 -0.131391 -0.115842 -0.119493 -0.116740 -0.118128
  5442 -0.047762 -0.010553 -0.049463 -0.047608 -0.048752 -0.047639 -0.048039
  5443  0.051830 -0.061373  0.054346  0.039526  0.041975  0.040736  0.041466

            7         8         9     ...      5434      5435      5436  \
  0     0.343060  0.342768  0.342690  ... -0.080229  0.064552 -0.143406
  1    -0.173140 -0.173307 -0.173308  ... -0.001869 -0.057247  0.040547
  2     0.342004  0.341627  0.341527  ... -0.083702  0.066164 -0.147634
  3     0.344489  0.344522  0.344527  ... -0.071517  0.052648 -0.128413
  4     0.344506  0.344458  0.344441  ... -0.074514  0.054967 -0.132596
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.021658  0.020496  0.020194  ...  0.122964  0.332890 -0.034540
  5440  0.049651  0.048580  0.048244  ... -0.041678  0.014027 -0.061952
  5441 -0.117867 -0.116856 -0.116853  ...  0.328505  0.071256  0.323941
  5442 -0.048012 -0.047977 -0.048119  ...  0.289181  0.255130  0.183739
  5443  0.041216  0.040225  0.039950  ...  0.100139  0.314385 -0.043038

            5437      5438      5439      5440      5441      5442      5443
  0     0.059189  0.044682  0.034052  0.060749 -0.127453 -0.047762  0.051830
  1    -0.060684 -0.043666 -0.032112 -0.093801  0.020639 -0.010553 -0.061373
  2     0.059001  0.046189  0.036403  0.065784 -0.131391 -0.049463  0.054346
  3     0.052546  0.033329  0.019808  0.047180 -0.115842 -0.047608  0.039526
  4     0.053445  0.035332  0.022489  0.051538 -0.119493 -0.048752  0.041975
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.255273  0.341494  1.000000 -0.025749  0.079392  0.265513  0.319103
  5440  0.005115 -0.030328 -0.025749  1.000000 -0.082848 -0.096233  0.051616
  5441  0.146312  0.083563  0.079392 -0.082848  1.000000  0.270426  0.062442
  5442  0.264389  0.269334  0.265513 -0.096233  0.270426  1.000000  0.232418
  5443  0.216236  0.324190  0.319103  0.051616  0.062442  0.232418  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000 -0.045003 -0.136218  0.471181  0.471141  0.471095  0.471292
  1    -0.045003  1.000000 -0.093085 -0.058004 -0.059025 -0.059511 -0.056440
  2    -0.136218 -0.093085  1.000000 -0.132883 -0.132814 -0.132575 -0.133275
  3     0.471181 -0.058004 -0.132883  1.000000  0.471585  0.471605  0.471601
  4     0.471141 -0.059025 -0.132814  0.471585  1.000000  0.471572  0.471568
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.112581  0.202230 -0.053065  0.104597  0.103168  0.104251  0.105997

In [19]:
check_dataset(dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][1]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 15921570
Count zero:	 0
Count positive:	 13715566
Count greater than 1:	 927
Count less than -1:	 0

In [27]:
def build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=0.3):
    dict_groups_subgroups_t_corr_g = {}
    for group_id, dict_groups in dict_groups_subgroups_t_corr.items():
        dict_aux = {}
        for subgroup_id, df_subgroup in dict_groups.items():
            # Percentil Correlaciones conservadas Densidad esperadas
            # 90	10 %	Alta
			# 95	5 %		Media
			# 97.5	2.5 %	Baja
			# 99	1 %		Muy baja
            threshold = np.percentile(np.abs(df_subgroup), 90)
            
            df_weighted_edges = (df_subgroup.where(np.triu(np.ones(df_subgroup.shape), k=1).astype(bool)).stack())
            df_weighted_edges = df_weighted_edges.dropna().to_frame()
            df_weighted_edges.reset_index(inplace=True)
            df_weighted_edges.columns = ["source", "target", "weight"]
            df_weighted_edges = df_weighted_edges[df_weighted_edges["weight"].abs() >= threshold]
            df_weighted_edges["subgroup"] = [subgroup_id] * len(df_weighted_edges)
            dict_aux[subgroup_id] = df_weighted_edges
            
            df_weighted_edges.to_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
            # G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight"])
            # print(groups_id[i], subgroups_id[groups_id[i]][j], G.number_of_nodes(), G.number_of_edges())
            # nx.write_gexf(G, "experiments/output/{}/preprocessing/graphs/graphs_{}_{}.gexf".format(exp, groups_id[i], subgroups_id[groups_id[i]][j]))
        dict_groups_subgroups_t_corr_g[group_id] = dict_aux
    return dict_groups_subgroups_t_corr_g

In [28]:
# Build graph (corpus graphs)

# dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

   source  target    weight subgroup
0       0       1  0.382173        1
2       0       3  0.432721        1
5       0       6  0.432547        1
6       0       7  0.432345        1
7       0       8  0.432405        1

In [29]:
def create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups, df_join_raw_metadata):	
	for group_id in tqdm(groups_id):
		for subgroup_id in tqdm(subgroups_id[group_id]):
			df_weighted_edges = pd.read_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id))
			# print(df_weighted_edges)
			G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight", "subgroup"])
			dict_id_idx = dict(zip(list(G.nodes()), range(G.number_of_nodes())))
			G = nx.relabel_nodes(G, dict_id_idx)

			df_nodes = dict_df_groups_subgroups[group_id][subgroup_id].loc[list(dict_id_idx.keys())] # A_1.1, A_1.2, A_1.3
			# from IPython.display import display
			# display(df_nodes)

			# nodes, with node features
			metadata = df_join_raw_metadata.loc[df_nodes.index] # Average Rt, Average Mz
			# intensity = df_join_raw_log.loc[df_nodes.index] # A_1.1, A_1.2, A_1.3, A_2.1, ...

			""" e = 1e-8
			mz = metadata.iloc[:, 1].values
			rt = metadata.iloc[:, 0].values
			intensity_mean = df_nodes.mean(axis=1).values
			intensity_std = df_nodes.std(axis=1).values
			intensity_cv = intensity_std / intensity_mean
			presence_ratio = (df_nodes > 0).mean(axis=1)

			mz_log = np.log10(mz + e)
			# intensity_mean_log = np.log10(intensity_mean + e)
			
			# mz_z = (mz_log - mz_log.mean()) / mz_log.std() # z-score
			rt_z = (rt - rt.mean()) / rt.std() # z-score
			# intensity_mean_z = (intensity_mean_log - intensity_mean_log.mean()) / intensity_mean_log.std() # z-score

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": mz_log,
				"rt": rt_z,
				"intensity_mean": intensity_mean,
				"intensity_std": intensity_std,
				"intensity_cv": intensity_cv,
				"presence_ratio": presence_ratio
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			# df_node_features.insert(0, "idx", list(dict_id_idx.values()))
			# df_node_features.insert(1, "id", list(dict_id_idx.keys()))
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features) """

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": metadata.iloc[:, 1].values,
				"rt": metadata.iloc[:, 0].values,
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features)

			# edges
			edges = list(G.edges())
			df_edges = pd.DataFrame(edges, columns=["source", "target"])
			df_edges["weight"] = [G.get_edge_data(*edge)["weight"] for edge in edges]
			df_edges["subgroup"] = [G.get_edge_data(*edge)["subgroup"] for edge in edges]
			df_edges.to_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)

In [30]:
# create dataset - nodes/edge data for PyTorch Geometric/DGL framework

# IMPORTANT
dict_df_groups_subgroups_ = split_groups_subgroups(df_join_raw_intensity, groups_id, subgroups_id) # Important (intesities without Log)

for data_variation in data_variations:
	if data_variation == "none":
		create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, df_join_raw_metadata)
	else:
		# dynamic graph to static graph
		create_graph_data_directed_variation(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, data_variation)

100%|██████████| 2/2 [00:13<00:00,  6.97s/it]
100%|██████████| 2/2 [00:13<00:00,  6.51s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.38s/it]]
100%|██████████| 2/2 [00:16<00:00,  8.21s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.47s/it]]
100%|██████████| 2/2 [00:16<00:00,  8.24s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.43s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.45s/it]]
100%|██████████| 2/2 [00:16<00:00,  8.39s/it]]
100%|██████████| 2/2 [00:12<00:00,  6.44s/it]]
100%|██████████| 2/2 [00:16<00:00,  8.40s/it]t]
100%|██████████| 11/11 [02:37<00:00, 14.34s/it]

In [31]:
# details
list_details = []
	
for group_id in groups_id:
	subgroups_id_ = []
	for data_variation in data_variations:
		if data_variation == "none":
			subgroups_id_ += subgroups_id[group_id]
		else:
			subgroups_id_ += [data_variation]
	# print(subgroups)
	
	for subgroup_id_ in subgroups_id_:
		try:
			df_edges = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id_))

			G = nx.from_pandas_edgelist(df_edges.iloc[:, [0, 1]])
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), nx.density(G), np.nan, nx.is_connected(G)])
		except:
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), np.nan, np.nan, np.nan])

df_details = pd.DataFrame(list_details, columns=["Group", "Subgroup", "Num. nodes", "Num. edges", "Density", "Diameter", "Is connected"])
df_details.to_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp), index=False)

df_details = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp))
df_details

   Group  Subgroup  Num. nodes  Num. edges   Density  Diameter  Is connected
0     AR         1        5444     1479135  0.099835       NaN          True
1     AR         2        5444     1479135  0.099835       NaN          True
2    CRS         1        5444     1479135  0.099835       NaN          True
3    CRS         2        5444     1479135  0.099835       NaN          True
4    OSA         1        5444     1479135  0.099835       NaN          True
5    OSA         2        5444     1479135  0.099835       NaN          True
6   LPRD         1        5444     1479135  0.099835       NaN          True
7   LPRD         2        5444     1479135  0.099835       NaN          True
8    SGB         1        5444     1479135  0.099835       NaN          True
9    SGB         2        5444     1479135  0.099835       NaN          True
10  LSNB         1        5444     1479135  0.099835       NaN          True
11  LSNB         2        5438     1479135  0.100055       NaN          True
12   RCC         1        5443     1479135  0.099871       NaN          True
13   RCC         2        5444     1479135  0.099835       NaN          True
14    BC         1        5444     1479135  0.099835       NaN          True
15    BC         2        5444     1479135  0.099835       NaN          True
16   BPH         1        5444     1479135  0.099835       NaN          True
17   BPH         2        5444     1479135  0.099835       NaN          True
18   PCa         1        5444     1479135  0.099835       NaN          True
19   PCa         2        5444     1479135  0.099835       NaN          True
20    PD         1        5444     1479135  0.099835       NaN          True
21    PD         2        5444     1479135  0.099835       NaN          True