### Imports

In [1]:
import json
import numpy as np
import pandas as pd
import pingouin as pg
import seaborn as sn

print(pg.__version__) # 0.5.3
print(pd.__version__) # 2.0.3
print(np.__version__) # 1.24.3
print(sn.__version__) # 0.13.0

from utils_MS import *

# %load_ext autotime

0.5.3
2.2.2
1.26.4
0.13.2

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.6.1.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
# def run(exp):

### Parameters

In [3]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"]

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

data_variations = params["data_variations"]
print("Data variations:", data_variations)

apply_transformation = params["apply_transformation"]
print("Apply transformation:", apply_transformation)

threshold_corr = params["threshold_corr"]
print("Threshold corr:\t", threshold_corr)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

groups_id_no = params["groups_id_no"]
print("Groups id (no):\t", groups_id_no)

Exp:		 exp9
Data variations: ['none']
Apply transformation: False
Threshold corr:	 0.5
Groups id:	 ['AR', 'CRS', 'OSA', 'LPRD', 'SGB', 'LSNB', 'RCC', 'BC', 'BPH', 'PCa', 'PD']
Subgroups id:	 {'AR': ['1', '2'], 'CRS': ['1', '2'], 'OSA': ['1', '2'], 'LPRD': ['1', '2'], 'SGB': ['1', '2'], 'LSNB': ['1', '2'], 'RCC': ['1', '2'], 'BC': ['1', '2'], 'BPH': ['1', '2'], 'PCa': ['1', '2'], 'PD': ['1', '2']}
Groups id (no):	 ['Blank', 'QC', 'Std']

In [4]:
# Remove
# groups_id = ["OSA"]

### Load dataset

In [5]:
# read raw data
df_join_raw = pd.read_csv("experiments/input/{}_raw.csv".format(exp), index_col=0)
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
0,1,69.99951,Unknown,0.57533,-2.21576,-1.87702,-1.51884,-1.39884,-1.29892,-1.21306,...,0.98788,-0.84910,-0.00751,0.45284,0.43153,-0.04444,0.46331,0.02780,-1.09413,-1.07540
1,1,70.04025,Unknown,2.51970,0.52452,0.86264,1.22016,1.33995,1.43969,1.52539,...,3.04923,2.96805,2.60501,3.06450,3.04323,2.56814,3.07496,2.64025,4.43489,2.05710
2,1,70.04151,Unknown,0.58098,-0.48955,-0.21483,0.07565,0.17297,0.25400,0.32363,...,1.67929,1.93973,1.11480,1.48813,1.47085,1.08484,1.49663,1.14343,0.52253,1.85662
3,1,70.04908,Unknown,2.57051,-0.10795,0.21509,0.55668,0.67112,0.76641,0.84829,...,2.38948,1.70959,1.86469,2.30371,2.28339,1.82946,2.31369,1.89836,0.67806,0.69874
4,1,70.06267,Unknown,1.15787,-0.15137,0.12754,0.29794,0.42245,0.52127,0.60354,...,2.60041,1.39557,1.36967,1.75502,1.73727,1.33853,1.76374,1.39940,1.12760,2.77683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1,732.79951,Unknown,2.21477,-0.58849,-0.38930,-0.17867,-0.10810,4.23613,-0.04934,...,0.97794,0.89484,0.53114,0.81967,0.80618,0.50653,0.82628,0.55450,0.10928,0.17849
5440,1,748.76437,Unknown,0.72580,-1.43132,-1.05285,-0.65267,-0.51859,-0.40695,-0.31103,...,1.16682,1.08808,0.89559,1.39809,1.37400,0.85432,1.40992,0.93504,0.20434,0.27869
5441,1,794.79590,Unknown,1.65124,-1.20428,-0.80051,-0.37358,-0.23053,-0.11143,-0.00910,...,1.03778,0.97033,1.21288,1.75795,1.73195,1.16780,1.77073,1.25592,0.32484,0.38565
5442,1,800.81295,Unknown,1.51148,-1.03648,-0.60768,-0.15429,-0.00238,0.12410,0.23278,...,1.34152,1.28640,1.55386,2.12317,2.09588,1.50710,2.13658,1.59856,0.75971,0.81518
5443,1,860.74167,Unknown,1.94236,-1.79295,-1.44649,6.03212,-1.08016,-0.95742,-0.85522,...,0.54552,0.46021,0.26878,0.75559,0.73328,0.22915,0.76655,0.30656,-0.34353,-0.27863

In [6]:
# get metadata
df_join_raw_metadata = df_join_raw.iloc[:, :2]
df_join_raw_metadata

      Average Rt  Average Mz
0              1    69.99951
1              1    70.04025
2              1    70.04151
3              1    70.04908
4              1    70.06267
...          ...         ...
5439           1   732.79951
5440           1   748.76437
5441           1   794.79590
5442           1   800.81295
5443           1   860.74167

[5444 rows x 2 columns]

In [7]:
# filter by samples
columns_sample = [column for column in df_join_raw.columns if column.split("_")[0] not in groups_id_no]
df_join_raw_intensity = df_join_raw.loc[:, columns_sample]
df_join_raw_intensity = df_join_raw_intensity.iloc[:, 3:]
df_join_raw_intensity

,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,AR_1.8,AR_1.9,AR_1.10,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
0,0.57533,-2.21576,-1.87702,-1.51884,-1.39884,-1.29892,-1.21306,-1.13763,-0.90208,-0.76795,...,0.98788,-0.84910,-0.00751,0.45284,0.43153,-0.04444,0.46331,0.02780,-1.09413,-1.07540
1,2.51970,0.52452,0.86264,1.22016,1.33995,1.43969,1.52539,1.60068,1.83580,1.96968,...,3.04923,2.96805,2.60501,3.06450,3.04323,2.56814,3.07496,2.64025,4.43489,2.05710
2,0.58098,-0.48955,-0.21483,0.07565,0.17297,0.25400,0.32363,0.38481,0.57584,0.68462,...,1.67929,1.93973,1.11480,1.48813,1.47085,1.08484,1.49663,1.14343,0.52253,1.85662
3,2.57051,-0.10795,0.21509,0.55668,0.67112,0.76641,0.84829,0.92023,1.14487,1.27278,...,2.38948,1.70959,1.86469,2.30371,2.28339,1.82946,2.31369,1.89836,0.67806,0.69874
4,1.15787,-0.15137,0.12754,0.29794,0.42245,0.52127,0.60354,0.67423,0.88796,1.00628,...,2.60041,1.39557,1.36967,1.75502,1.73727,1.33853,1.76374,1.39940,1.12760,2.77683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,2.21477,-0.58849,-0.38930,-0.17867,-0.10810,4.23613,-0.04934,0.00114,0.12100,0.21208,...,0.97794,0.89484,0.53114,0.81967,0.80618,0.50653,0.82628,0.55450,0.10928,0.17849
5440,0.72580,-1.43132,-1.05285,-0.65267,-0.51859,-0.40695,-0.31103,-0.22674,0.03643,0.18629,...,1.16682,1.08808,0.89559,1.39809,1.37400,0.85432,1.40992,0.93504,0.20434,0.27869
5441,1.65124,-1.20428,-0.80051,-0.37358,-0.23053,-0.11143,-0.00910,0.08082,0.36159,0.47160,...,1.03778,0.97033,1.21288,1.75795,1.73195,1.16780,1.77073,1.25592,0.32484,0.38565
5442,1.51148,-1.03648,-0.60768,-0.15429,-0.00238,0.12410,0.23278,0.32828,0.62644,0.79623,...,1.34152,1.28640,1.55386,2.12317,2.09588,1.50710,2.13658,1.59856,0.75971,0.81518
5443,1.94236,-1.79295,-1.44649,6.03212,-1.08016,-0.95742,-0.85522,-0.76741,-0.50192,-0.35494,...,0.54552,0.46021,0.26878,0.75559,0.73328,0.22915,0.76655,0.30656,-0.34353,-0.27863

In [8]:
df_join_raw_intensity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5444 entries, 0 to 5443
Columns: 308 entries, AR_1.1 to PD_2.14
dtypes: float64(308)
memory usage: 12.8 MB

In [9]:
check_dataset(df_join_raw_intensity)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 61931
Count zero:	 0
Count positive:	 1614821
Count greater than 1:	 1361642
Count less than -1:	 8037

### Generate graphs

In [10]:
# Transformation (log10)

if apply_transformation:
	df_join_raw_log = log10_global(df_join_raw_intensity)
else:
	df_join_raw_log = df_join_raw_intensity.copy()
df_join_raw_log.head()

,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,AR_1.8,AR_1.9,AR_1.10,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
0,0.57533,-2.21576,-1.87702,-1.51884,-1.39884,-1.29892,-1.21306,-1.13763,-0.90208,-0.76795,...,0.98788,-0.84910,-0.00751,0.45284,0.43153,-0.04444,0.46331,0.02780,-1.09413,-1.07540
1,2.51970,0.52452,0.86264,1.22016,1.33995,1.43969,1.52539,1.60068,1.83580,1.96968,...,3.04923,2.96805,2.60501,3.06450,3.04323,2.56814,3.07496,2.64025,4.43489,2.05710
2,0.58098,-0.48955,-0.21483,0.07565,0.17297,0.25400,0.32363,0.38481,0.57584,0.68462,...,1.67929,1.93973,1.11480,1.48813,1.47085,1.08484,1.49663,1.14343,0.52253,1.85662
3,2.57051,-0.10795,0.21509,0.55668,0.67112,0.76641,0.84829,0.92023,1.14487,1.27278,...,2.38948,1.70959,1.86469,2.30371,2.28339,1.82946,2.31369,1.89836,0.67806,0.69874
4,1.15787,-0.15137,0.12754,0.29794,0.42245,0.52127,0.60354,0.67423,0.88796,1.00628,...,2.60041,1.39557,1.36967,1.75502,1.73727,1.33853,1.76374,1.39940,1.12760,2.77683

In [11]:
check_dataset(df_join_raw_log)

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 61931
Count zero:	 0
Count positive:	 1614821
Count greater than 1:	 1361642
Count less than -1:	 8037

In [12]:
# split graph in groups and subgroups

""" def split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id, by_group=False):
	list_df_groups_subgroups = []
	for group in groups_id:
		df_aux = df_join_raw_log.filter(like=group)
		list_aux = []
		
		if by_group:
			list_aux.append(df_aux)
		else:
			for subgroup in subgroups_id[group]:
				list_aux.append(df_aux.filter(like="{}_{}.".format(group, subgroup)))
		list_df_groups_subgroups.append(list_aux)
	return list_df_groups_subgroups """

dict_df_groups_subgroups = split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id)
dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,AR_1.8,AR_1.9,AR_1.10,AR_1.11,AR_1.12,AR_1.13,AR_1.14
0,0.57533,-2.21576,-1.87702,-1.51884,-1.39884,-1.29892,-1.21306,-1.13763,-0.90208,-0.76795,-0.72852,-0.69120,-0.62204,-0.58983
1,2.51970,0.52452,0.86264,1.22016,1.33995,1.43969,1.52539,1.60068,1.83580,1.96968,2.00904,2.04629,2.11532,2.14747
2,0.58098,-0.48955,-0.21483,0.07565,0.17297,0.25400,0.32363,0.38481,0.57584,0.68462,0.71660,0.74686,0.80295,0.82907
3,2.57051,-0.10795,0.21509,0.55668,0.67112,0.76641,0.84829,0.92023,1.14487,1.27278,1.31039,1.34598,1.41193,1.44265
4,1.15787,-0.15137,0.12754,0.29794,0.42245,0.52127,0.60354,0.67423,0.88796,1.00628,1.04073,1.07320,1.13309,1.16087

In [13]:
check_dataset(dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 8664
Count zero:	 0
Count positive:	 67552
Count greater than 1:	 53482
Count less than -1:	 1907

In [14]:
# No apply transpose for kneighbors_graph
# dict_groups_subgroups_t = dict_df_groups_subgroups.copy()

# Aplly Transpose
dict_groups_subgroups_t = transpose_global(dict_df_groups_subgroups)

dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,0.57533,2.51970,0.58098,2.57051,1.15787,1.27213,2.62029,2.63990,2.65040,2.73757,...,1.64684,1.98987,-0.30933,1.23702,1.87136,2.21477,0.72580,1.65124,1.51148,1.94236
1,-2.21576,0.52452,-0.48955,-0.10795,-0.15137,0.10341,0.38295,0.46580,0.41341,0.57550,...,0.05434,-0.07692,-2.00218,-0.30250,-0.26303,-0.58849,-1.43132,-1.20428,-1.03648,-1.79295
2,-1.87702,0.86264,-0.21483,0.21509,0.12754,0.36245,0.63531,0.71463,0.67240,0.81397,...,0.42073,0.22067,-1.63513,0.01170,-0.03679,-0.38930,-1.05285,-0.80051,-0.60768,-1.44649
3,-1.51884,1.22016,0.07565,0.55668,0.29794,0.63636,0.90215,0.97773,0.94624,1.06613,...,0.80815,0.53533,-1.24701,0.34392,0.20243,-0.17867,-0.65267,-0.37358,-0.15429,6.03212
4,-1.39884,1.33995,0.17297,0.67112,0.42245,0.72813,0.99156,1.06588,1.03799,1.15061,...,0.93795,0.64076,-1.11697,0.45524,0.28258,-0.10810,-0.51859,-0.23053,-0.00238,-1.08016

In [15]:
check_dataset(dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 8664
Count zero:	 0
Count positive:	 67552
Count greater than 1:	 53482
Count less than -1:	 1907

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import LedoitWolf
from sklearn.neighbors import kneighbors_graph

def correlation_ledoitwolf_global(exp, dict_groups_subgroups_t):
	dict_groups_subgroups_t_corr = {}
	for group_id, dict_groups in dict_groups_subgroups_t.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			print(group_id, subgroup_id, df_subgroup.shape)
			
			""" import numpy as np
			cov = np.cov(df_subgroup.values, rowvar=False)
			cond = np.linalg.cond(cov)
			print("Condition number:", cond, cond > 1e8) # ill-conditioned if > 1e8 (True, instable) """

			scaler = StandardScaler()
			df_subgroup_scaled = scaler.fit_transform(df_subgroup)
			lw = LedoitWolf()
			lw.fit(df_subgroup_scaled)

			# Matriz de covarianza regularizada
			cov = lw.covariance_
			std = np.sqrt(np.diag(cov))
			corr = cov / np.outer(std, std)
			matrix = pd.DataFrame(corr)
		
			dict_aux[subgroup_id] = matrix
			
			matrix.to_csv("experiments/output/{}/correlations/{}_{}.csv".format(exp, group_id, subgroup_id), index=True)
		dict_groups_subgroups_t_corr[group_id] = dict_aux
	return dict_groups_subgroups_t_corr

def correlation_kneighbors_graph_global(exp, dict_groups_subgroups_t):
	dict_groups_subgroups_t_corr = {}
	for group_id, dict_groups in dict_groups_subgroups_t.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			print(group_id, subgroup_id, df_subgroup.shape)
			
			""" import numpy as np
			cov = np.cov(df_subgroup.values, rowvar=False)
			cond = np.linalg.cond(cov)
			print("Condition number:", cond, cond > 1e8) # ill-conditioned if > 1e8 (True, instable) """
			
			k = 10
			scaler = StandardScaler()
			df_subgroup_scaled = scaler.fit_transform(df_subgroup)
			A = kneighbors_graph(
				df_subgroup_scaled, # X, X_scaled
				n_neighbors=k,
				metric="euclidean", # "cosine",
				mode="distance",
				include_self=True
			)
			matrix = pd.DataFrame(A.toarray())
		
			dict_aux[subgroup_id] = matrix
			
			matrix.to_csv("experiments/output/{}/correlations/{}_{}.csv".format(exp, group_id, subgroup_id), index=True)
		dict_groups_subgroups_t_corr[group_id] = dict_aux
	return dict_groups_subgroups_t_corr

In [17]:
# Correlation matrix (partial correlation)

# Option 1
# dict_groups_subgroups_t_corr = correlation_global(exp, dict_groups_subgroups_t)

# Option 2
dict_groups_subgroups_t_corr = correlation_ledoitwolf_global(exp, dict_groups_subgroups_t)

# Option 3
# dict_groups_subgroups_t_corr = correlation_kneighbors_graph_global(exp, dict_groups_subgroups_t)

dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

AR 1 (14, 5444)

AR 2 (14, 5444)
CRS 1 (14, 5444)
CRS 2 (14, 5444)
OSA 1 (14, 5444)
OSA 2 (14, 5444)
LPRD 1 (14, 5444)
LPRD 2 (14, 5444)
SGB 1 (14, 5444)
SGB 2 (14, 5444)
LSNB 1 (14, 5444)
LSNB 2 (14, 5444)
RCC 1 (14, 5444)
RCC 2 (14, 5444)
BC 1 (14, 5444)
BC 2 (14, 5444)
BPH 1 (14, 5444)
BPH 2 (14, 5444)
PCa 1 (14, 5444)
PCa 2 (14, 5444)
PD 1 (14, 5444)
PD 2 (14, 5444)

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,1.000000,0.483011,0.409727,0.503280,0.451822,0.443424,0.502444,0.502741,0.502932,0.270128,...,0.432015,0.274301,0.443558,0.225076,0.499472,0.199005,0.478539,0.500200,0.483861,0.116111
1,0.483011,1.000000,0.475342,0.482293,0.494763,0.492350,0.474019,0.475901,0.477357,0.271608,...,0.487156,0.299942,0.492509,0.268724,0.462120,0.186330,0.503059,0.495426,0.503278,0.085012
2,0.409727,0.475342,1.000000,0.408250,0.494198,0.499032,0.392128,0.395670,0.398457,0.245460,...,0.501639,0.299142,0.499203,0.292187,0.371011,0.152380,0.480102,0.438994,0.474329,0.039925
3,0.503280,0.482293,0.408250,1.000000,0.450721,0.442221,0.502584,0.502852,0.503020,0.269904,...,0.430710,0.273640,0.442355,0.224128,0.499774,0.199086,0.477748,0.499918,0.483158,0.116583
4,0.451822,0.494763,0.494198,0.450721,1.000000,0.500202,0.438474,0.441198,0.443328,0.263049,...,0.499471,0.307506,0.501023,0.289025,0.421492,0.165764,0.497002,0.472223,0.494256,0.038880

In [18]:
# Check correlation matrices

dict_groups_subgroups_t_corr

{'AR': {'1':           0         1         2         3         4         5         6     \
  0     1.000000  0.483011  0.409727  0.503280  0.451822  0.443424  0.502444
  1     0.483011  1.000000  0.475342  0.482293  0.494763  0.492350  0.474019
  2     0.409727  0.475342  1.000000  0.408250  0.494198  0.499032  0.392128
  3     0.503280  0.482293  0.408250  1.000000  0.450721  0.442221  0.502584
  4     0.451822  0.494763  0.494198  0.450721  1.000000  0.500202  0.438474
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.199005  0.186330  0.152380  0.199086  0.165764  0.169879  0.199631
  5440  0.478539  0.503059  0.480102  0.477748  0.497002  0.495242  0.468717
  5441  0.500200  0.495426  0.438994  0.499918  0.472223  0.466655  0.496195
  5442  0.483861  0.503278  0.474329  0.483158  0.494256  0.491712  0.475038
  5443  0.116111  0.085012  0.039925  0.116583  0.038880  0.059596  0.121355

            7         8         9     ...      5434      5435      5436  \
  0     0.502741  0.502932  0.270128  ...  0.432015  0.274301  0.443558
  1     0.475901  0.477357  0.271608  ...  0.487156  0.299942  0.492509
  2     0.395670  0.398457  0.245460  ...  0.501639  0.299142  0.499203
  3     0.502852  0.503020  0.269904  ...  0.430710  0.273640  0.442355
  4     0.441198  0.443328  0.263049  ...  0.499471  0.307506  0.501023
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.199560  0.199489  0.051317  ...  0.162317  0.303563  0.167552
  5440  0.470760  0.472345  0.270471  ...  0.490738  0.301258  0.495402
  5441  0.497108  0.497791  0.277701  ...  0.457440  0.284746  0.466696
  5442  0.476887  0.478317  0.271807  ...  0.486380  0.299643  0.491870
  5443  0.120363  0.119560  0.033346  ...  0.051433  0.030440  0.057902

            5437      5438      5439      5440      5441      5442      5443
  0     0.225076  0.499472  0.199005  0.478539  0.500200  0.483861  0.116111
  1     0.268724  0.462120  0.186330  0.503059  0.495426  0.503278  0.085012
  2     0.292187  0.371011  0.152380  0.480102  0.438994  0.474329  0.039925
  3     0.224128  0.499774  0.199086  0.477748  0.499918  0.483158  0.116583
  4     0.289025  0.421492  0.165764  0.497002  0.472223  0.494256  0.038880
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.023227  0.199893  1.000000  0.184084  0.196452  0.186761  0.002797
  5440  0.272117  0.455919  0.184084  1.000000  0.492554  0.502958  0.081279
  5441  0.243095  0.489903  0.196452  0.492554  1.000000  0.495951  0.105997
  5442  0.268009  0.463321  0.186761  0.502958  0.495951  1.000000  0.085758
  5443  0.012148  0.127345  0.002797  0.081279  0.105997  0.085758  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000 -0.066523  0.049880  0.097879 -0.125417 -0.101498 -0.101602
  1    -0.066523  1.000000  0.100178  0.032263 -0.065331 -0.052408 -0.052492
  2     0.049880  0.100178  1.000000 -0.129366 -0.178726 -0.102192 -0.101113
  3     0.097879  0.032263 -0.129366  1.000000  0.200815  0.180868  0.180809
  4    -0.125417 -0.065331 -0.178726  0.200815  1.000000  0.471241  0.471220
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.389117 -0.093382  0.017540  0.201737  0.187732  0.231065  0.231310
  5440  0.429914 -0.089513 -0.089566  0.144537  0.002511  0.039940  0.039072
  5441  0.301064  0.120719  0.023500  0.048447  0.142697  0.203983  0.204053
  5442  0.325527  0.050733  0.041863  0.091297  0.191133  0.246834  0.246908
  5443  0.395051 -0.066004  0.066253  0.138500  0.045888  0.074709  0.073886

            7         8         9     ...      5434      5435      5436  \
  0    -0.130698 -0.132109  0.140497  ...  0.326660  0.360305  0.221250
  1    -0.070510 -0.072044 -0.079463  ...  0.120243 -0.113957  0.127505
  2    -0.070583 -0.063484 -0.113679  ... -0.025476 -0.015413 -0.003869
  3     0.176711  0.188025  0.206548  ...  0.226717  0.213036 -0.064861
  4     0.404527  0.391542  0.355700  ...  0.184314  0.186567 -0.015903
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.165790  0.156386  0.376856  ...  0.448515  0.480781  0.189475
  5440 -0.013029 -0.018749  0.217031  ...  0.354565  0.383589  0.226802
  5441  0.115647  0.104522  0.326355  ...  0.458833  0.373264  0.308774
  5442  0.164685  0.153543  0.373571  ...  0.464831  0.419025  0.303752
  5443  0.032250  0.027031  0.204371  ...  0.320614  0.362266  0.209742

            5437      5438      5439      5440      5441      5442      5443
  0    -0.078270  0.382164  0.389117  0.429914  0.301064  0.325527  0.395051
  1     0.154567  0.051757 -0.093382 -0.089513  0.120719  0.050733 -0.066004
  2    -0.026185  0.002884  0.017540 -0.089566  0.023500  0.041863  0.066253
  3    -0.021717  0.206466  0.201737  0.144537  0.048447  0.091297  0.138500
  4     0.172047  0.128163  0.187732  0.002511  0.142697  0.191133  0.045888
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.065735  0.469220  1.000000  0.392190  0.404910  0.453702  0.389449
  5440 -0.077856  0.396619  0.392190  1.000000  0.325238  0.328182  0.449308
  5441  0.201613  0.448431  0.404910  0.325238  1.000000  0.486478  0.293467
  5442  0.197447  0.450298  0.453702  0.328182  0.486478  1.000000  0.328531
  5443 -0.103603  0.354419  0.389449  0.449308  0.293467  0.328531  1.000000

  [5444 rows x 5444 columns]},
 'CRS': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.068457  0.417053  0.417068  0.185908  0.417084  0.417085
  1    -0.068457  1.000000 -0.065357 -0.065161 -0.074140 -0.066461 -0.066439
  2     0.417053 -0.065357  1.000000  0.417088  0.183855  0.417059  0.417062
  3     0.417068 -0.065161  0.417088  1.000000  0.184702  0.417077  0.417079
  4     0.185908 -0.074140  0.183855  0.184702  1.000000  0.185936  0.185872
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.319416  0.012524 -0.320951 -0.320449 -0.083815 -0.318188 -0.318308
  5440 -0.132787  0.108747 -0.133537 -0.131634 -0.031758 -0.132426 -0.132470
  5441 -0.215101  0.024849 -0.214799 -0.215985 -0.097631 -0.214479 -0.214504
  5442 -0.325830 -0.022552 -0.326606 -0.326449 -0.117746 -0.325399 -0.325446
  5443 -0.196263 -0.001352 -0.197245 -0.196753 -0.042205 -0.194703 -0.194826

            7         8         9     ...      5434      5435      5436  \
  0     0.417086  0.417066  0.417064  ... -0.261671 -0.207809 -0.247282
  1    -0.066364 -0.066607 -0.065552  ...  0.065346  0.007518 -0.053735
  2     0.417068  0.417031  0.417097  ... -0.261726 -0.208896 -0.248516
  3     0.417083  0.417054  0.417092  ... -0.261149 -0.208335 -0.249164
  4     0.185724  0.186339  0.184253  ... -0.128898  0.026407 -0.064517
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.318587 -0.316709 -0.320184  ...  0.150398  0.342342  0.357673
  5440 -0.132572 -0.131401 -0.133289  ...  0.133979  0.108034 -0.076036
  5441 -0.214571 -0.214031 -0.214594  ...  0.177948  0.242202  0.311609
  5442 -0.325559 -0.324547 -0.326294  ...  0.247598  0.336110  0.297133
  5443 -0.195121 -0.194523 -0.196426  ...  0.190566  0.212204  0.256404

            5437      5438      5439      5440      5441      5442      5443
  0    -0.246704 -0.218508 -0.319416 -0.132787 -0.215101 -0.325830 -0.196263
  1     0.108075 -0.133157  0.012524  0.108747  0.024849 -0.022552 -0.001352
  2    -0.247029 -0.219372 -0.320951 -0.133537 -0.214799 -0.326606 -0.197245
  3    -0.245966 -0.220337 -0.320449 -0.131634 -0.215985 -0.326449 -0.196753
  4    -0.090231 -0.082526 -0.083815 -0.031758 -0.097631 -0.117746 -0.042205
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.189232  0.300600  1.000000  0.132985  0.245294  0.340394  0.270144
  5440  0.169322 -0.095646  0.132985  1.000000 -0.107189  0.102470 -0.060437
  5441  0.200754  0.292151  0.245294 -0.107189  1.000000  0.304669  0.194655
  5442  0.276689  0.269361  0.340394  0.102470  0.304669  1.000000  0.199674
  5443  0.190366  0.237623  0.270144 -0.060437  0.194655  0.199674  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000  0.051547 -0.110804 -0.239049 -0.238683 -0.238223 -0.238256
  1     0.051547  1.000000 -0.134996  0.033524  0.035235  0.034092  0.034100
  2    -0.110804 -0.134996  1.000000  0.104986  0.102786  0.103929  0.103954
  3    -0.239049  0.033524  0.104986  1.000000  0.449668  0.449680  0.449684
  4    -0.238683  0.035235  0.102786  0.449668  1.000000  0.449731  0.449731
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.038227  0.040443  0.104412  0.202356  0.201799  0.201488  0.201522
  5440  0.066642 -0.084019  0.058723  0.094882  0.091021  0.091254  0.091351
  5441 -0.106755  0.128293  0.047540  0.361080  0.361853  0.361739  0.361727
  5442 -0.078205  0.069061  0.067515  0.306032  0.306476  0.306303  0.306301
  5443 -0.149384 -0.122818  0.122084  0.217342  0.218267  0.217637  0.217640

            7         8         9     ...      5434      5435      5436  \
  0    -0.238313 -0.238351 -0.238375  ... -0.123473 -0.143302 -0.237148
  1     0.034118  0.034117  0.034128  ...  0.056505  0.096035  0.027722
  2     0.103998  0.104030  0.104049  ...  0.119971  0.160780  0.105745
  3     0.449693  0.449697  0.449700  ...  0.390367  0.296292  0.449641
  4     0.449732  0.449732  0.449732  ...  0.388532  0.295171  0.449497
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.201592  0.201624  0.201651  ...  0.321172  0.352901  0.200384
  5440  0.091576  0.091688  0.091783  ...  0.260447  0.231998  0.096274
  5441  0.361691  0.361670  0.361654  ...  0.390373  0.348813  0.359574
  5442  0.306286  0.306278  0.306270  ...  0.360065  0.351882  0.304922
  5443  0.217649  0.217652  0.217652  ...  0.244990  0.291840  0.215877

            5437      5438      5439      5440      5441      5442      5443
  0    -0.244758  0.014496 -0.038227  0.066642 -0.106755 -0.078205 -0.149384
  1     0.025820 -0.092385  0.040443 -0.084019  0.128293  0.069061 -0.122818
  2     0.128300  0.140095  0.104412  0.058723  0.047540  0.067515  0.122084
  3     0.391757  0.145241  0.202356  0.094882  0.361080  0.306032  0.217342
  4     0.394157  0.141416  0.201799  0.091021  0.361853  0.306476  0.218267
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.122855  0.354434  1.000000  0.280431  0.352895  0.381414  0.288417
  5440  0.012730  0.376934  0.280431  1.000000  0.175478  0.213045  0.221136
  5441  0.271368  0.203209  0.352895  0.175478  1.000000  0.427085  0.200762
  5442  0.221119  0.252847  0.381414  0.213045  0.427085  1.000000  0.231874
  5443  0.276707  0.292577  0.288417  0.221136  0.200762  0.231874  1.000000

  [5444 rows x 5444 columns]},
 'OSA': {'1':           0         1         2         3         4         5         6     \
  0     1.000000  0.051338 -0.166534 -0.167012 -0.165540 -0.166866 -0.166838
  1     0.051338  1.000000  0.039932  0.043719  0.037105  0.040724  0.039706
  2    -0.166534  0.039932  1.000000  0.486363  0.486360  0.486407  0.486396
  3    -0.167012  0.043719  0.486363  1.000000  0.486326  0.486391  0.486394
  4    -0.165540  0.037105  0.486360  0.486326  1.000000  0.486368  0.486366
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.068777 -0.044610  0.163040  0.164322  0.162082  0.162740  0.164601
  5440 -0.192833  0.171922  0.234595  0.236037  0.232271  0.234422  0.235061
  5441 -0.108375  0.063265  0.188056  0.187501  0.186348  0.186736  0.187628
  5442 -0.097215 -0.017694  0.304180  0.302734  0.302637  0.302784  0.303439
  5443 -0.078200  0.086403  0.205816  0.204492  0.203223  0.204578  0.204740

            7         8         9     ...      5434      5435      5436  \
  0    -0.166548 -0.166585 -0.166610  ... -0.081322 -0.134308 -0.167591
  1     0.039296  0.039577  0.039797  ...  0.155785  0.038347  0.046975
  2     0.486404  0.486403  0.486402  ...  0.276921  0.293956  0.486089
  3     0.486386  0.486390  0.486393  ...  0.277807  0.292706  0.486225
  4     0.486385  0.486383  0.486381  ...  0.276266  0.292500  0.486177
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.163630  0.163677  0.163714  ...  0.262826  0.277734  0.159513
  5440  0.234056  0.234188  0.234288  ...  0.311865  0.326234  0.234680
  5441  0.187153  0.187182  0.187201  ...  0.371476  0.402690  0.184635
  5442  0.303384  0.303348  0.303317  ...  0.366220  0.411290  0.298586
  5443  0.204506  0.204512  0.204511  ...  0.343298  0.347873  0.201540

            5437      5438      5439      5440      5441      5442      5443
  0    -0.109880 -0.137913 -0.068777 -0.192833 -0.108375 -0.097215 -0.078200
  1     0.051281  0.055184 -0.044610  0.171922  0.063265 -0.017694  0.086403
  2     0.084837  0.272929  0.163040  0.234595  0.188056  0.304180  0.205816
  3     0.088015  0.271970  0.164322  0.236037  0.187501  0.302734  0.204492
  4     0.088055  0.271408  0.162082  0.232271  0.186348  0.302637  0.203223
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.068656  0.277167  1.000000  0.246471  0.326884  0.331735  0.266241
  5440  0.050507  0.349903  0.246471  1.000000  0.357393  0.247268  0.293010
  5441 -0.051360  0.405364  0.326884  0.357393  1.000000  0.412224  0.411510
  5442 -0.050735  0.385710  0.331735  0.247268  0.412224  1.000000  0.398699
  5443  0.036794  0.338801  0.266241  0.293010  0.411510  0.398699  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000 -0.303107  0.259107  0.433041  0.432954  0.433036  0.433046
  1    -0.303107  1.000000 -0.165084 -0.306130 -0.305398 -0.303515 -0.304496
  2     0.259107 -0.165084  1.000000  0.258442  0.258101  0.258896  0.258667
  3     0.433041 -0.306130  0.258442  1.000000  0.432972  0.433011  0.433039
  4     0.432954 -0.305398  0.258101  0.432972  1.000000  0.433038  0.433036
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.058193 -0.207530 -0.031770  0.060851  0.058197  0.057675  0.058412
  5440  0.028039 -0.157420  0.001417  0.029901  0.029081  0.028406  0.028646
  5441  0.008850 -0.063130 -0.051687  0.009641  0.006857  0.007209  0.007697
  5442  0.169027 -0.128995 -0.008686  0.169764  0.167257  0.168135  0.168313
  5443  0.432920 -0.301292  0.258659  0.432864  0.432807  0.432902  0.432882

            7         8         9     ...      5434      5435      5436  \
  0     0.432828  0.433065  0.433067  ... -0.006496  0.076433  0.432984
  1    -0.304964 -0.302183 -0.302405  ... -0.132660 -0.161039 -0.306558
  2     0.258067  0.259379  0.259311  ... -0.010645 -0.026155  0.257308
  3     0.432837  0.433014  0.433020  ... -0.004379  0.077597  0.433032
  4     0.432876  0.432962  0.432966  ... -0.010845  0.073093  0.432950
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.055441  0.057583  0.057761  ...  0.269855  0.355128  0.060734
  5440  0.026659  0.027985  0.028107  ...  0.166803  0.230031  0.030475
  5441  0.005698  0.008153  0.008231  ...  0.263486  0.141014  0.008986
  5442  0.166748  0.168951  0.168980  ...  0.181217  0.293940  0.169057
  5443  0.432555  0.432943  0.432943  ... -0.003482  0.076590  0.432916

            5437      5438      5439      5440      5441      5442      5443
  0    -0.149045  0.061722  0.058193  0.028039  0.008850  0.169027  0.432920
  1     0.059949 -0.169356 -0.207530 -0.157420 -0.063130 -0.128995 -0.301292
  2    -0.108031  0.001261 -0.031770  0.001417 -0.051687 -0.008686  0.258659
  3    -0.147213  0.063217  0.060851  0.029901  0.009641  0.169764  0.432864
  4    -0.147753  0.063202  0.058197  0.029081  0.006857  0.167257  0.432807
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.210593  0.259124  1.000000  0.274780  0.219115  0.296405  0.060097
  5440  0.150756  0.420017  0.274780  1.000000 -0.075515  0.225656  0.031555
  5441  0.033264 -0.081514  0.219115 -0.075515  1.000000  0.136842  0.009402
  5442  0.003379  0.209818  0.296405  0.225656  0.136842  1.000000  0.169957
  5443 -0.143512  0.065866  0.060097  0.031555  0.009402  0.169957  1.000000

  [5444 rows x 5444 columns]},
 'LPRD': {'1':           0         1         2         3         4         5         6     \
  0     1.000000 -0.262676  0.445485  0.445392  0.445484  0.445499  0.445497
  1    -0.262676  1.000000 -0.262049 -0.257933 -0.263823 -0.262851 -0.263014
  2     0.445485 -0.262049  1.000000  0.445434  0.445451  0.445476  0.445475
  3     0.445392 -0.257933  0.445434  1.000000  0.445298  0.445367  0.445358
  4     0.445484 -0.263823  0.445451  0.445298  1.000000  0.445495  0.445497
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.117258  0.065936  0.118311  0.123678  0.114590  0.117023  0.116557
  5440  0.200934 -0.151854  0.202634  0.204107  0.200680  0.201090  0.201050
  5441 -0.084677 -0.020910 -0.086889 -0.087861 -0.083725 -0.083761 -0.083881
  5442 -0.037996  0.028419 -0.039845 -0.040843 -0.037195 -0.037145 -0.037127
  5443  0.161207 -0.103186  0.162246  0.163731  0.159968  0.161387  0.160913

            7         8         9     ...      5434      5435      5436  \
  0     0.445500  0.445496  0.445501  ...  0.000069  0.200091 -0.147038
  1    -0.262605 -0.262395 -0.262517  ... -0.001623 -0.102540  0.085198
  2     0.445483  0.445478  0.445485  ... -0.000803  0.200609 -0.148627
  3     0.445382  0.445380  0.445388  ... -0.000906  0.203472 -0.150901
  4     0.445491  0.445491  0.445489  ...  0.000952  0.198744 -0.144192
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.117151  0.117342  0.117216  ...  0.076892  0.267899 -0.086020
  5440  0.201331  0.201432  0.201318  ...  0.113402  0.258200 -0.084615
  5441 -0.084213 -0.083841 -0.084429  ...  0.299057  0.051283  0.261105
  5442 -0.037436 -0.037100 -0.037562  ...  0.311906 -0.001635  0.225151
  5443  0.161150  0.161226  0.161134  ...  0.138706  0.346279 -0.070659

            5437      5438      5439      5440      5441      5442      5443
  0     0.079110  0.153569  0.117258  0.200934 -0.084677 -0.037996  0.161207
  1    -0.000096 -0.086523  0.065936 -0.151854 -0.020910  0.028419 -0.103186
  2     0.078097  0.154227  0.118311  0.202634 -0.086889 -0.039845  0.162246
  3     0.079457  0.156042  0.123678  0.204107 -0.087861 -0.040843  0.163731
  4     0.079401  0.152153  0.114590  0.200680 -0.083725 -0.037195  0.159968
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.083804  0.317946  1.000000  0.093028  0.090836  0.074689  0.296930
  5440  0.092492  0.132860  0.093028  1.000000 -0.069622 -0.154302  0.173121
  5441  0.125386  0.153603  0.090836 -0.069622  1.000000  0.376058  0.128628
  5442  0.156527  0.139052  0.074689 -0.154302  0.376058  1.000000  0.104672
  5443  0.108857  0.439088  0.296930  0.173121  0.128628  0.104672  1.000000

  [5444 rows x 5444 columns],
  '2':           0         1         2         3         4         5         6     \
  0     1.000000 -0.134109 -0.101340  0.495828  0.495889  0.495897  0.495893
  1    -0.134109  1.000000 -0.109139 -0.125428 -0.132163 -0.127333 -0.127160
  2    -0.101340 -0.109139  1.000000 -0.101192 -0.100426 -0.101108 -0.101121
  3     0.495828 -0.125428 -0.101192  1.000000  0.495922  0.495983  0.495984
  4     0.495889 -0.132163 -0.100426  0.495922  1.000000  0.495939  0.495938
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.160218  0.171376 -0.049715  0.162227  0.158675  0.161971  0.162031

In [19]:
check_dataset(dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][1]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 14360024
Count zero:	 0
Count positive:	 15277112
Count greater than 1:	 286
Count less than -1:	 0

In [20]:
def build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=0.3):
	dict_groups_subgroups_t_corr_g = {}
	for group_id, dict_groups in dict_groups_subgroups_t_corr.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			# Percentil Correlaciones conservadas 	Densidad esperadas
			# 90		10 %						Alta
			# 95		5 %							Media
			# 97.5		2.5 %						Baja
			# 99		1 %							Muy baja
			threshold = np.percentile(np.abs(df_subgroup), 95)
			
			df_weighted_edges = (df_subgroup.where(np.triu(np.ones(df_subgroup.shape), k=1).astype(bool)).stack())
			df_weighted_edges = df_weighted_edges.dropna().to_frame()
			df_weighted_edges.reset_index(inplace=True)
			df_weighted_edges.columns = ["source", "target", "weight"]
			df_weighted_edges = df_weighted_edges[df_weighted_edges["weight"].abs() >= threshold]
			df_weighted_edges["subgroup"] = [subgroup_id] * len(df_weighted_edges)
			dict_aux[subgroup_id] = df_weighted_edges
			
			df_weighted_edges.to_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight"])
			# print(groups_id[i], subgroups_id[groups_id[i]][j], G.number_of_nodes(), G.number_of_edges())
			# nx.write_gexf(G, "experiments/output/{}/preprocessing/graphs/graphs_{}_{}.gexf".format(exp, groups_id[i], subgroups_id[groups_id[i]][j]))
		dict_groups_subgroups_t_corr_g[group_id] = dict_aux
	return dict_groups_subgroups_t_corr_g

In [21]:
# Build graph (corpus graphs)

# dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

   source  target    weight subgroup
0       0       1  0.483011        1
1       0       2  0.409727        1
2       0       3  0.503280        1
3       0       4  0.451822        1
4       0       5  0.443424        1

In [22]:
def create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups, df_join_raw_metadata):	
	for group_id in tqdm(groups_id):
		for subgroup_id in tqdm(subgroups_id[group_id]):
			df_weighted_edges = pd.read_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id))
			# print(df_weighted_edges)
			G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight", "subgroup"])
			dict_id_idx = dict(zip(list(G.nodes()), range(G.number_of_nodes())))
			G = nx.relabel_nodes(G, dict_id_idx)

			df_nodes = dict_df_groups_subgroups[group_id][subgroup_id].loc[list(dict_id_idx.keys())] # A_1.1, A_1.2, A_1.3
			# from IPython.display import display
			# display(df_nodes)

			# nodes, with node features
			metadata = df_join_raw_metadata.loc[df_nodes.index] # Average Rt, Average Mz
			# intensity = df_join_raw_log.loc[df_nodes.index] # A_1.1, A_1.2, A_1.3, A_2.1, ...

			""" e = 1e-8
			mz = metadata.iloc[:, 1].values
			rt = metadata.iloc[:, 0].values
			intensity_mean = df_nodes.mean(axis=1).values
			intensity_std = df_nodes.std(axis=1).values
			intensity_cv = intensity_std / intensity_mean
			presence_ratio = (df_nodes > 0).mean(axis=1)

			mz_log = np.log10(mz + e)
			# intensity_mean_log = np.log10(intensity_mean + e)
			
			# mz_z = (mz_log - mz_log.mean()) / mz_log.std() # z-score
			rt_z = (rt - rt.mean()) / rt.std() # z-score
			# intensity_mean_z = (intensity_mean_log - intensity_mean_log.mean()) / intensity_mean_log.std() # z-score

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": mz_log,
				"rt": rt_z,
				"intensity_mean": intensity_mean,
				"intensity_std": intensity_std,
				"intensity_cv": intensity_cv,
				"presence_ratio": presence_ratio
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			# df_node_features.insert(0, "idx", list(dict_id_idx.values()))
			# df_node_features.insert(1, "id", list(dict_id_idx.keys()))
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features) """

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": metadata.iloc[:, 1].values,
				"rt": metadata.iloc[:, 0].values,
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features)

			# edges
			edges = list(G.edges())
			df_edges = pd.DataFrame(edges, columns=["source", "target"])
			df_edges["weight"] = [G.get_edge_data(*edge)["weight"] for edge in edges]
			df_edges["subgroup"] = [G.get_edge_data(*edge)["subgroup"] for edge in edges]
			df_edges.to_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)

In [23]:
# create dataset - nodes/edge data for PyTorch Geometric/DGL framework

# IMPORTANT
dict_df_groups_subgroups_ = split_groups_subgroups(df_join_raw_intensity, groups_id, subgroups_id) # Important (intesities without Log)

for data_variation in data_variations:
	if data_variation == "none":
		create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, df_join_raw_metadata)
	else:
		# dynamic graph to static graph
		create_graph_data_directed_variation(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, data_variation)

100%|██████████| 2/2 [00:06<00:00,  3.12s/it]
100%|██████████| 2/2 [00:06<00:00,  3.30s/it]]
100%|██████████| 2/2 [00:07<00:00,  3.96s/it]]
100%|██████████| 2/2 [00:06<00:00,  3.26s/it]]
100%|██████████| 2/2 [00:08<00:00,  4.23s/it]]
100%|██████████| 2/2 [00:06<00:00,  3.19s/it]]
100%|██████████| 2/2 [00:06<00:00,  3.25s/it]]
100%|██████████| 2/2 [00:08<00:00,  4.26s/it]]
100%|██████████| 2/2 [00:06<00:00,  3.25s/it]]
100%|██████████| 2/2 [00:08<00:00,  4.21s/it]]
100%|██████████| 2/2 [00:06<00:00,  3.28s/it]t]
100%|██████████| 11/11 [01:18<00:00,  7.15s/it]

In [24]:
# details
list_details = []
	
for group_id in groups_id:
	subgroups_id_ = []
	for data_variation in data_variations:
		if data_variation == "none":
			subgroups_id_ += subgroups_id[group_id]
		else:
			subgroups_id_ += [data_variation]
	# print(subgroups)
	
	for subgroup_id_ in subgroups_id_:
		try:
			df_edges = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id_))

			G = nx.from_pandas_edgelist(df_edges.iloc[:, [0, 1]])
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), nx.density(G), np.nan, nx.is_connected(G)])
		except:
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), np.nan, np.nan, np.nan])

df_details = pd.DataFrame(list_details, columns=["Group", "Subgroup", "Num. nodes", "Num. edges", "Density", "Diameter", "Is connected"])
df_details.to_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp), index=False)

df_details = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp))
df_details

   Group  Subgroup  Num. nodes  Num. edges   Density  Diameter  Is connected
0     AR         1        5382      738207  0.050980       NaN         False
1     AR         2        5433      738207  0.050027       NaN          True
2    CRS         1        5444      738207  0.049826       NaN          True
3    CRS         2        5444      738207  0.049826       NaN          True
4    OSA         1        5444      738207  0.049826       NaN          True
5    OSA         2        5444      738207  0.049826       NaN          True
6   LPRD         1        5444      738207  0.049826       NaN          True
7   LPRD         2        5444      738207  0.049826       NaN          True
8    SGB         1        5444      738207  0.049826       NaN          True
9    SGB         2        5444      738207  0.049826       NaN          True
10  LSNB         1        5444      738207  0.049826       NaN          True
11  LSNB         2        5374      738207  0.051132       NaN         False
12   RCC         1        5403      738207  0.050585       NaN         False
13   RCC         2        5444      738207  0.049826       NaN          True
14    BC         1        5444      738207  0.049826       NaN          True
15    BC         2        5444      738207  0.049826       NaN          True
16   BPH         1        5386      738207  0.050904       NaN         False
17   BPH         2        5444      738207  0.049826       NaN          True
18   PCa         1        5444      738207  0.049826       NaN          True
19   PCa         2        5443      738207  0.049844       NaN          True
20    PD         1        5443      738207  0.049844       NaN          True
21    PD         2        5425      738207  0.050175       NaN         False