### Imports

In [ ]:
import json
import numpy as np
import pandas as pd
import pingouin as pg
import seaborn as sn

print(pg.__version__) # 0.5.3
print(pd.__version__) # 2.0.3
print(np.__version__) # 1.24.3
print(sn.__version__) # 0.13.0

from utils_MS import *

# %load_ext autotime

In [ ]:
# def run(exp):

### Parameters

In [ ]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"]

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

data_variations = params["data_variations"]
print("Data variations:", data_variations)

apply_transformation = params["apply_transformation"]
print("Apply transformation:", apply_transformation)

threshold_corr = params["threshold_corr"]
print("Threshold corr:\t", threshold_corr)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

groups_id_no = params["groups_id_no"]
print("Groups id (no):\t", groups_id_no)

In [ ]:
# Remove
# groups_id = ["LSNB", "BC", "RCC", "BPH", "PD"] # "OSA" Memory issue
# groups_id = ["AR", "BC"]

### Load dataset

In [ ]:
# read raw data
df_join_raw = pd.read_csv("experiments/input/{}_raw.csv".format(exp), index_col=0)
df_join_raw

In [ ]:
# get metadata
df_join_raw_metadata = df_join_raw.iloc[:, :2]
df_join_raw_metadata

In [ ]:
# filter by samples
columns_sample = [column for column in df_join_raw.columns if column.split("_")[0] not in groups_id_no]
df_join_raw_intensity = df_join_raw.loc[:, columns_sample]
df_join_raw_intensity = df_join_raw_intensity.iloc[:, 3:]
df_join_raw_intensity

In [ ]:
df_join_raw_intensity.info()

In [ ]:
check_dataset(df_join_raw_intensity)

### Generate graphs

In [ ]:
# Transformation (log10)

if apply_transformation:
	df_join_raw_log = log10_global(df_join_raw_intensity)
else:
	df_join_raw_log = df_join_raw_intensity.copy()
df_join_raw_log.head()

In [ ]:
check_dataset(df_join_raw_log)

In [ ]:
# split graph in groups and subgroups

""" def split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id, by_group=False):
	list_df_groups_subgroups = []
	for group in groups_id:
		df_aux = df_join_raw_log.filter(like=group)
		list_aux = []
		
		if by_group:
			list_aux.append(df_aux)
		else:
			for subgroup in subgroups_id[group]:
				list_aux.append(df_aux.filter(like="{}_{}.".format(group, subgroup)))
		list_df_groups_subgroups.append(list_aux)
	return list_df_groups_subgroups """

dict_df_groups_subgroups = split_groups_subgroups(df_join_raw_log, groups_id, subgroups_id)
dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

In [ ]:
check_dataset(dict_df_groups_subgroups[groups_id[0]][subgroups_id[groups_id[0]][0]])

In [ ]:
# No apply transpose for kneighbors_graph
# dict_groups_subgroups_t = dict_df_groups_subgroups.copy()

# Aplly Transpose
dict_groups_subgroups_t = transpose_global(dict_df_groups_subgroups)

dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

In [ ]:
check_dataset(dict_groups_subgroups_t[groups_id[0]][subgroups_id[groups_id[0]][0]])

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import LedoitWolf
from sklearn.neighbors import kneighbors_graph

def correlation_ledoitwolf_global(exp, dict_groups_subgroups_t):
	dict_groups_subgroups_t_corr = {}
	for group_id, dict_groups in dict_groups_subgroups_t.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			print(group_id, subgroup_id, df_subgroup.shape)
			
			""" import numpy as np
			cov = np.cov(df_subgroup.values, rowvar=False)
			cond = np.linalg.cond(cov)
			print("Condition number:", cond, cond > 1e8) # ill-conditioned if > 1e8 (True, instable) """

			scaler = StandardScaler()
			df_subgroup_scaled = scaler.fit_transform(df_subgroup)
			lw = LedoitWolf()
			lw.fit(df_subgroup_scaled)

			# Matriz de covarianza regularizada
			cov = lw.covariance_
			std = np.sqrt(np.diag(cov))
			corr = cov / np.outer(std, std)
			matrix = pd.DataFrame(corr)
		
			dict_aux[subgroup_id] = matrix
			
			matrix.to_csv("experiments/output/{}/correlations/{}_{}.csv".format(exp, group_id, subgroup_id), index=True)
		dict_groups_subgroups_t_corr[group_id] = dict_aux
	return dict_groups_subgroups_t_corr

def correlation_kneighbors_graph_global(exp, dict_groups_subgroups_t):
	dict_groups_subgroups_t_corr = {}
	for group_id, dict_groups in dict_groups_subgroups_t.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			print(group_id, subgroup_id, df_subgroup.shape)
			
			""" import numpy as np
			cov = np.cov(df_subgroup.values, rowvar=False)
			cond = np.linalg.cond(cov)
			print("Condition number:", cond, cond > 1e8) # ill-conditioned if > 1e8 (True, instable) """
			
			k = 10
			scaler = StandardScaler()
			df_subgroup_scaled = scaler.fit_transform(df_subgroup)
			A = kneighbors_graph(
				df_subgroup_scaled, # X, X_scaled
				n_neighbors=k,
				metric="euclidean", # "cosine",
				mode="distance",
				include_self=True
			)
			matrix = pd.DataFrame(A.toarray())
		
			dict_aux[subgroup_id] = matrix
			
			matrix.to_csv("experiments/output/{}/correlations/{}_{}.csv".format(exp, group_id, subgroup_id), index=True)
		dict_groups_subgroups_t_corr[group_id] = dict_aux
	return dict_groups_subgroups_t_corr

In [17]:
# Correlation matrix (partial correlation)

# Option 1
# dict_groups_subgroups_t_corr = correlation_global(exp, dict_groups_subgroups_t)

# Option 2
dict_groups_subgroups_t_corr = correlation_ledoitwolf_global(exp, dict_groups_subgroups_t)

# Option 3
# dict_groups_subgroups_t_corr = correlation_kneighbors_graph_global(exp, dict_groups_subgroups_t)

dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

disease 10 (241, 5444)
disease 11 (23, 5444)
disease 12 (69, 5444)
disease 13 (116, 5444)
disease 14 (106, 5444)
disease 15 (103, 5444)
disease 16 (143, 5444)
disease 17 (87, 5444)
disease 18 (105, 5444)
disease 2 (83, 5444)
disease 3 (78, 5444)
disease 4 (232, 5444)
disease 5 (121, 5444)
disease 6 (178, 5444)
disease 7 (85, 5444)
disease 8 (75, 5444)
disease 9 (28, 5444)

,0,1,2,3,4,5,6,7,8,9,...,5434,5435,5436,5437,5438,5439,5440,5441,5442,5443
0,1.000000,0.174581,0.165038,0.212890,0.159773,0.176521,0.182648,0.181443,0.169069,0.188352,...,0.143699,0.122297,0.111452,0.039771,0.138912,0.100034,0.199383,0.156175,0.147559,0.160229
1,0.174581,1.000000,0.086543,0.247080,0.390980,0.393033,0.383695,0.350129,0.335462,0.278491,...,0.265565,0.274280,0.160716,0.236543,0.236555,0.246695,0.356938,0.250359,0.303985,0.267378
2,0.165038,0.086543,1.000000,0.097880,0.069158,0.065091,0.046552,0.044415,0.018479,0.024209,...,0.155852,0.125760,0.194264,0.143943,0.112840,0.077547,0.095005,0.132008,0.150810,0.098847
3,0.212890,0.247080,0.097880,1.000000,0.462738,0.473673,0.453659,0.485622,0.458887,0.453186,...,0.334667,0.339696,0.158398,0.201391,0.276562,0.249136,0.331116,0.338701,0.349476,0.275583
4,0.159773,0.390980,0.069158,0.462738,1.000000,0.787010,0.753084,0.695534,0.633428,0.592446,...,0.245584,0.229727,0.037284,0.127705,0.223469,0.189945,0.305924,0.244023,0.240023,0.216285

In [18]:
# Check correlation matrices

dict_groups_subgroups_t_corr

{'disease': {'1':           0         1         2         3         4         5         6     \
  0     1.000000  0.174581  0.165038  0.212890  0.159773  0.176521  0.182648
  1     0.174581  1.000000  0.086543  0.247080  0.390980  0.393033  0.383695
  2     0.165038  0.086543  1.000000  0.097880  0.069158  0.065091  0.046552
  3     0.212890  0.247080  0.097880  1.000000  0.462738  0.473673  0.453659
  4     0.159773  0.390980  0.069158  0.462738  1.000000  0.787010  0.753084
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.100034  0.246695  0.077547  0.249136  0.189945  0.186858  0.187776
  5440  0.199383  0.356938  0.095005  0.331116  0.305924  0.301003  0.282564
  5441  0.156175  0.250359  0.132008  0.338701  0.244023  0.248213  0.241919
  5442  0.147559  0.303985  0.150810  0.349476  0.240023  0.236497  0.240413
  5443  0.160229  0.267378  0.098847  0.275583  0.216285  0.182179  0.172228

            7         8         9     ...      5434      5435      5436  \
  0     0.181443  0.169069  0.188352  ...  0.143699  0.122297  0.111452
  1     0.350129  0.335462  0.278491  ...  0.265565  0.274280  0.160716
  2     0.044415  0.018479  0.024209  ...  0.155852  0.125760  0.194264
  3     0.485622  0.458887  0.453186  ...  0.334667  0.339696  0.158398
  4     0.695534  0.633428  0.592446  ...  0.245584  0.229727  0.037284
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.196149  0.150342  0.180741  ...  0.525281  0.681998  0.210816
  5440  0.280357  0.216990  0.250112  ...  0.532549  0.629524  0.227793
  5441  0.272911  0.225936  0.269379  ...  0.653892  0.633404  0.379350
  5442  0.255149  0.212637  0.236295  ...  0.751017  0.770373  0.440437
  5443  0.211925  0.144597  0.186335  ...  0.513214  0.613001  0.189622

            5437      5438      5439      5440      5441      5442      5443
  0     0.039771  0.138912  0.100034  0.199383  0.156175  0.147559  0.160229
  1     0.236543  0.236555  0.246695  0.356938  0.250359  0.303985  0.267378
  2     0.143943  0.112840  0.077547  0.095005  0.132008  0.150810  0.098847
  3     0.201391  0.276562  0.249136  0.331116  0.338701  0.349476  0.275583
  4     0.127705  0.223469  0.189945  0.305924  0.244023  0.240023  0.216285
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.306584  0.599964  1.000000  0.655410  0.511970  0.606714  0.603626
  5440  0.273228  0.638216  0.655410  1.000000  0.499561  0.596594  0.628730
  5441  0.402313  0.514907  0.511970  0.499561  1.000000  0.686266  0.488957
  5442  0.455638  0.639927  0.606714  0.596594  0.686266  1.000000  0.588092
  5443  0.276156  0.552409  0.603626  0.628730  0.488957  0.588092  1.000000

  [5444 rows x 5444 columns],
  '10':           0         1         2         3         4         5         6     \
  0     1.000000 -0.099759  0.137136  0.243397  0.175159  0.218324  0.187037
  1    -0.099759  1.000000 -0.060463 -0.171677  0.098839  0.018507  0.010348
  2     0.137136 -0.060463  1.000000  0.258796  0.266520  0.304204  0.239426
  3     0.243397 -0.171677  0.258796  1.000000  0.519684  0.576455  0.570324
  4     0.175159  0.098839  0.266520  0.519684  1.000000  0.811490  0.799891
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.070825  0.183760 -0.007675 -0.049230  0.025493  0.028967 -0.011156
  5440 -0.079943  0.178327 -0.077891 -0.105418  0.016249  0.028667 -0.019631
  5441 -0.017656  0.109811 -0.079612 -0.032732  0.001515  0.009346 -0.039435
  5442 -0.003406  0.099989 -0.110694 -0.016068  0.002089 -0.005645 -0.032353
  5443 -0.085583  0.149019 -0.002423  0.026612  0.133758  0.100786  0.091793

            7         8         9     ...      5434      5435      5436  \
  0     0.195841  0.220551  0.196302  ... -0.014002 -0.038092  0.055892
  1    -0.007701  0.000502 -0.020413  ...  0.062735  0.053728  0.065526
  2     0.295272  0.249168  0.243926  ... -0.171913 -0.126883 -0.049693
  3     0.586170  0.576216  0.621364  ... -0.101035 -0.014965  0.045557
  4     0.762295  0.741884  0.705322  ... -0.073804  0.005914  0.037406
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.014625 -0.004413 -0.005996  ...  0.582360  0.680965  0.425009
  5440 -0.016925  0.000395 -0.032203  ...  0.571153  0.647735  0.268687
  5441 -0.037879 -0.043564 -0.039235  ...  0.750933  0.712895  0.539347
  5442 -0.006383 -0.036197 -0.032065  ...  0.754627  0.773716  0.563351
  5443  0.088540  0.078313  0.089519  ...  0.467492  0.579450  0.319027

            5437      5438      5439      5440      5441      5442      5443
  0     0.038658  0.009539 -0.070825 -0.079943 -0.017656 -0.003406 -0.085583
  1    -0.146276  0.089352  0.183760  0.178327  0.109811  0.099989  0.149019
  2     0.078006 -0.204730 -0.007675 -0.077891 -0.079612 -0.110694 -0.002423
  3     0.155025 -0.087869 -0.049230 -0.105418 -0.032732 -0.016068  0.026612
  4     0.173794 -0.037901  0.025493  0.016249  0.001515  0.002089  0.133758
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.275456  0.633329  1.000000  0.671074  0.634894  0.723889  0.657183
  5440  0.260678  0.647237  0.671074  1.000000  0.590186  0.652582  0.597678
  5441  0.317676  0.690638  0.634894  0.590186  1.000000  0.762277  0.521927
  5442  0.355025  0.726184  0.723889  0.652582  0.762277  1.000000  0.593178
  5443  0.297796  0.533286  0.657183  0.597678  0.521927  0.593178  1.000000

  [5444 rows x 5444 columns],
  '11':           0         1         2         3         4         5         6     \
  0     1.000000  0.043884  0.001694 -0.094579 -0.129984 -0.250378 -0.162909
  1     0.043884  1.000000 -0.179506  0.094559 -0.071252 -0.057999 -0.121095
  2     0.001694 -0.179506  1.000000  0.005144  0.135480  0.114143  0.035047
  3    -0.094579  0.094559  0.005144  1.000000  0.264308  0.286235  0.300392
  4    -0.129984 -0.071252  0.135480  0.264308  1.000000  0.382527  0.379052
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.183682 -0.033062  0.006553 -0.035924  0.070058  0.029679  0.016334
  5440 -0.273862  0.032252 -0.008913  0.052513  0.118209  0.174294  0.160910
  5441 -0.201470 -0.183349  0.104984 -0.028226  0.097504  0.046479  0.036408
  5442 -0.138779 -0.263619  0.103270 -0.021562  0.067862  0.053465  0.107334
  5443 -0.132156 -0.027063  0.132357 -0.122570 -0.097941 -0.110861 -0.124490

            7         8         9     ...      5434      5435      5436  \
  0    -0.121886 -0.166403 -0.085835  ... -0.140371 -0.257972  0.169406
  1    -0.088273 -0.017930 -0.082038  ... -0.347712 -0.179128 -0.173095
  2     0.059560 -0.006303  0.006424  ...  0.099825  0.065497  0.010233
  3     0.314765  0.334757  0.325679  ...  0.097892 -0.020503  0.103062
  4     0.354090  0.309721  0.259135  ...  0.091874  0.118728 -0.060911
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.010485  0.001519 -0.046625  ...  0.235159  0.425229 -0.110325
  5440  0.147105  0.132183  0.074823  ...  0.211451  0.445126 -0.183734
  5441  0.010727 -0.022181 -0.033274  ...  0.387131  0.386766  0.183492
  5442  0.080719  0.048496  0.028533  ...  0.429547  0.448546  0.145672
  5443 -0.124973 -0.117150 -0.159537  ...  0.142744  0.308000 -0.159418

            5437      5438      5439      5440      5441      5442      5443
  0     0.047596 -0.182376 -0.183682 -0.273862 -0.201470 -0.138779 -0.132156
  1    -0.156430 -0.121303 -0.033062  0.032252 -0.183349 -0.263619 -0.027063
  2    -0.042159  0.072990  0.006553 -0.008913  0.104984  0.103270  0.132357
  3     0.118171 -0.004078 -0.035924  0.052513 -0.028226 -0.021562 -0.122570
  4    -0.011249  0.159124  0.070058  0.118209  0.097504  0.067862 -0.097941
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.082665  0.464464  1.000000  0.429370  0.313007  0.349694  0.419638
  5440 -0.164921  0.336364  0.429370  1.000000  0.269642  0.309142  0.314942
  5441  0.141225  0.377911  0.313007  0.269642  1.000000  0.436939  0.201650
  5442  0.074813  0.411312  0.349694  0.309142  0.436939  1.000000  0.251326
  5443 -0.164865  0.301172  0.419638  0.314942  0.201650  0.251326  1.000000

  [5444 rows x 5444 columns],
  '12':           0         1         2         3         4         5         6     \
  0     1.000000 -0.165164  0.016430 -0.212712 -0.152939 -0.232380 -0.202585
  1    -0.165164  1.000000  0.019727  0.175641  0.294328  0.306077  0.313326
  2     0.016430  0.019727  1.000000 -0.201814 -0.168570 -0.114266 -0.094764
  3    -0.212712  0.175641 -0.201814  1.000000  0.444368  0.433969  0.399455
  4    -0.152939  0.294328 -0.168570  0.444368  1.000000  0.666787  0.601277
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.132906  0.261085 -0.083384  0.023861  0.026657 -0.002520  0.021950
  5440 -0.175867  0.290608 -0.135868  0.044133  0.083598  0.090076  0.100756
  5441 -0.049568  0.135337 -0.088206  0.156314 -0.026951 -0.070969  0.025207
  5442 -0.122818  0.205131 -0.084977  0.173218  0.021738 -0.009438  0.070550
  5443 -0.158587  0.237805 -0.020937  0.081592  0.025432 -0.032847  0.026525

            7         8         9     ...      5434      5435      5436  \
  0    -0.187073 -0.296264 -0.228126  ... -0.073059 -0.133682 -0.122364
  1     0.286744  0.284855  0.293408  ...  0.168581  0.177144  0.078141
  2    -0.145732 -0.124646 -0.119700  ... -0.075334 -0.126896 -0.005337
  3     0.452520  0.410273  0.391990  ...  0.109848  0.150310  0.136506
  4     0.664200  0.520209  0.504256  ... -0.006866  0.066828  0.089681
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.027612  0.098493  0.061968  ...  0.482229  0.594213  0.111760
  5440  0.061145  0.126357  0.091836  ...  0.390661  0.480761  0.042328
  5441 -0.059954 -0.045008 -0.104981  ...  0.647984  0.548239  0.273049
  5442 -0.001393  0.042983  0.009004  ...  0.658596  0.687172  0.286843
  5443 -0.049373  0.026910  0.003730  ...  0.466300  0.559273  0.188820

            5437      5438      5439      5440      5441      5442      5443
  0    -0.095356 -0.159929 -0.132906 -0.175867 -0.049568 -0.122818 -0.158587
  1     0.168535  0.212993  0.261085  0.290608  0.135337  0.205131  0.237805
  2     0.015864 -0.087593 -0.083384 -0.135868 -0.088206 -0.084977 -0.020937
  3     0.092157  0.120274  0.023861  0.044133  0.156314  0.173218  0.081592
  4     0.152721  0.128256  0.026657  0.083598 -0.026951  0.021738  0.025432
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.218841  0.593250  1.000000  0.567512  0.435914  0.577166  0.573045
  5440  0.068012  0.515363  0.567512  1.000000  0.326684  0.430478  0.468096
  5441  0.273660  0.476682  0.435914  0.326684  1.000000  0.615819  0.442447
  5442  0.329615  0.588180  0.577166  0.430478  0.615819  1.000000  0.566223
  5443  0.237365  0.611524  0.573045  0.468096  0.442447  0.566223  1.000000

  [5444 rows x 5444 columns],
  '13':           0         1         2         3         4         5         6     \
  0     1.000000  0.088747 -0.059659  0.169356  0.004682  0.016678  0.093941
  1     0.088747  1.000000  0.164740  0.149236  0.109747  0.176274  0.140484
  2    -0.059659  0.164740  1.000000 -0.066698 -0.063763 -0.051555 -0.060814
  3     0.169356  0.149236 -0.066698  1.000000  0.249573  0.350051  0.408330
  4     0.004682  0.109747 -0.063763  0.249573  1.000000  0.428016  0.418478
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.004557  0.264297  0.161372  0.217316  0.117134  0.144110  0.136935
  5440  0.020203  0.304609  0.156001  0.274306  0.137209  0.199545  0.177686
  5441  0.041872  0.133904  0.096311  0.109715  0.005496  0.034554  0.016820
  5442  0.076461  0.245806  0.159353  0.242276  0.052373  0.103963  0.082201
  5443  0.055981  0.365513  0.214439  0.309916  0.146601  0.179980  0.153585

            7         8         9     ...      5434      5435      5436  \
  0     0.088545  0.180106  0.144142  ...  0.121334  0.123909  0.102867
  1     0.260916  0.154178  0.152429  ...  0.214510  0.298675  0.097154
  2    -0.042726 -0.052706 -0.073840  ...  0.197548  0.248613  0.246066
  3     0.380352  0.492818  0.476625  ...  0.236174  0.309715  0.126210
  4     0.418533  0.435489  0.418010  ...  0.053925  0.137602 -0.006847
  ...        ...       ...       ...  ...       ...       ...       ...
  5439  0.143831  0.152179  0.155339  ...  0.337110  0.365905  0.236604
  5440  0.221788  0.206138  0.207935  ...  0.377308  0.433187  0.246046
  5441  0.060779  0.051646  0.043245  ...  0.472957  0.363402  0.314648
  5442  0.142698  0.097392  0.084076  ...  0.561786  0.602478  0.408796
  5443  0.208945  0.206649  0.194063  ...  0.535619  0.615820  0.382055

            5437      5438      5439      5440      5441      5442      5443
  0     0.153184  0.000728  0.004557  0.020203  0.041872  0.076461  0.055981
  1     0.137998  0.300049  0.264297  0.304609  0.133904  0.245806  0.365513
  2     0.250365  0.023287  0.161372  0.156001  0.096311  0.159353  0.214439
  3     0.217877  0.182305  0.217316  0.274306  0.109715  0.242276  0.309916
  4     0.026994  0.112310  0.117134  0.137209  0.005496  0.052373  0.146601
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.297604  0.315312  1.000000  0.349818  0.241712  0.333939  0.497628
  5440  0.256898  0.350707  0.349818  1.000000  0.293787  0.367234  0.601924
  5441  0.393746  0.476555  0.241712  0.293787  1.000000  0.328741  0.406040
  5442  0.451440  0.313815  0.333939  0.367234  0.328741  1.000000  0.532019
  5443  0.396063  0.503321  0.497628  0.601924  0.406040  0.532019  1.000000

  [5444 rows x 5444 columns],
  '14':           0         1         2         3         4         5         6     \
  0     1.000000 -0.061714  0.426787  0.678725  0.743253  0.649116  0.737502
  1    -0.061714  1.000000  0.042726 -0.080344 -0.049812 -0.079266 -0.049260
  2     0.426787  0.042726  1.000000  0.405478  0.436780  0.378090  0.436901
  3     0.678725 -0.080344  0.405478  1.000000  0.693998  0.613090  0.696890
  4     0.743253 -0.049812  0.436780  0.693998  1.000000  0.658650  0.749874
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.036856 -0.019110 -0.058186 -0.066230 -0.038186 -0.056545 -0.041860
  5440 -0.110181  0.022466 -0.040405 -0.037390 -0.088961 -0.094695 -0.081501
  5441 -0.241049  0.096691 -0.179524 -0.227423 -0.237779 -0.238454 -0.240668
  5442 -0.146512  0.049875 -0.111157 -0.175002 -0.146256 -0.155856 -0.150246
  5443  0.049966  0.028846  0.079697  0.033419  0.060447  0.034670  0.060394

            7         8         9     ...      5434      5435      5436  \
  0     0.695664  0.736806  0.735802  ... -0.242292 -0.083624  0.115834
  1    -0.053171 -0.050639 -0.050685  ...  0.090144  0.013582  0.087385
  2     0.411420  0.439310  0.439394  ... -0.184225 -0.047366  0.004870
  3     0.666495  0.697949  0.698282  ... -0.224695 -0.067820  0.045067
  4     0.714394  0.749590  0.749224  ... -0.242527 -0.080350  0.093508
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.046705 -0.044401 -0.045445  ...  0.382406  0.521570  0.142730
  5440 -0.084485 -0.084001 -0.083508  ...  0.384609  0.419875  0.015383
  5441 -0.237387 -0.244101 -0.245039  ...  0.588788  0.506132  0.292544
  5442 -0.153127 -0.153536 -0.154789  ...  0.549703  0.544820  0.314230
  5443  0.049944  0.057157  0.056425  ...  0.368703  0.520926  0.203112

            5437      5438      5439      5440      5441      5442      5443
  0     0.082954 -0.127534 -0.036856 -0.110181 -0.241049 -0.146512  0.049966
  1    -0.057620 -0.016525 -0.019110  0.022466  0.096691  0.049875  0.028846
  2    -0.051263 -0.084196 -0.058186 -0.040405 -0.179524 -0.111157  0.079697
  3     0.036176 -0.090327 -0.066230 -0.037390 -0.227423 -0.175002  0.033419
  4     0.069619 -0.118542 -0.038186 -0.088961 -0.237779 -0.146256  0.060447
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.257896  0.481388  1.000000  0.363268  0.470255  0.525065  0.455398
  5440  0.088979  0.480338  0.363268  1.000000  0.367095  0.478446  0.427974
  5441  0.345585  0.533278  0.470255  0.367095  1.000000  0.592004  0.425672
  5442  0.310317  0.556862  0.525065  0.478446  0.592004  1.000000  0.491360
  5443  0.242100  0.512995  0.455398  0.427974  0.425672  0.491360  1.000000

  [5444 rows x 5444 columns],
  '15':           0         1         2         3         4         5         6     \
  0     1.000000  0.159344  0.178547  0.521292  0.418505  0.521231  0.458908
  1     0.159344  1.000000  0.139195  0.257358  0.256384  0.257298  0.234207
  2     0.178547  0.139195  1.000000  0.273037  0.222569  0.278260  0.246146
  3     0.521292  0.257358  0.273037  1.000000  0.649118  0.792146  0.715893
  4     0.418505  0.256384  0.222569  0.649118  1.000000  0.650364  0.580652
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.087761  0.142119  0.162726 -0.025578  0.033769 -0.019607 -0.038587
  5440 -0.084755  0.117367  0.060351 -0.015254 -0.045390 -0.007511 -0.031947
  5441 -0.134826  0.116738  0.076517 -0.098735  0.006408 -0.090975 -0.101908
  5442 -0.112391  0.004087 -0.011879 -0.067952  0.027093 -0.062363 -0.078524
  5443 -0.007109  0.158106  0.116771  0.059174  0.031010  0.064879  0.045215

            7         8         9     ...      5434      5435      5436  \
  0     0.522785  0.522076  0.521430  ... -0.180259 -0.115815  0.053936
  1     0.251493  0.254648  0.257444  ...  0.029193  0.066998  0.114232
  2     0.278112  0.277624  0.276941  ... -0.105508  0.059652 -0.038933
  3     0.792495  0.792720  0.792842  ... -0.139856 -0.053820  0.142702
  4     0.649891  0.649962  0.650020  ... -0.034423  0.014132  0.274427
  ...        ...       ...       ...  ...       ...       ...       ...
  5439 -0.024907 -0.023657 -0.022765  ...  0.474429  0.538095  0.064974
  5440 -0.013342 -0.012440 -0.011560  ...  0.448187  0.583231  0.121461
  5441 -0.095488 -0.094922 -0.094310  ...  0.535856  0.594220  0.240571
  5442 -0.066352 -0.065690 -0.065100  ...  0.549671  0.603109  0.220006
  5443  0.061198  0.062010  0.062523  ...  0.359422  0.459396  0.109033

            5437      5438      5439      5440      5441      5442      5443
  0    -0.016095 -0.101571 -0.087761 -0.084755 -0.134826 -0.112391 -0.007109
  1    -0.079689  0.077748  0.142119  0.117367  0.116738  0.004087  0.158106
  2    -0.099661  0.095569  0.162726  0.060351  0.076517 -0.011879  0.116771
  3     0.026137 -0.053457 -0.025578 -0.015254 -0.098735 -0.067952  0.059174
  4     0.098329  0.004668  0.033769 -0.045390  0.006408  0.027093  0.031010
  ...        ...       ...       ...       ...       ...       ...       ...
  5439  0.126347  0.509109  1.000000  0.479185  0.460022  0.508126  0.496969
  5440  0.186516  0.460305  0.479185  1.000000  0.481991  0.544742  0.473546
  5441  0.260525  0.477094  0.460022  0.481991  1.000000  0.595810  0.366400
  5442  0.252136  0.492062  0.508126  0.544742  0.595810  1.000000  0.454999
  5443 -0.062018  0.449987  0.496969  0.473546  0.366400  0.454999  1.000000

  [5444 rows x 5444 columns],
  '16':           0         1         2         3         4         5         6     \
  0     1.000000 -0.027127  0.294563  0.410642  0.449172  0.416556  0.458593
  1    -0.027127  1.000000 -0.003546  0.028442 -0.005272  0.052636  0.023196
  2     0.294563 -0.003546  1.000000  0.454354  0.498935  0.459790  0.506876
  3     0.410642  0.028442  0.454354  1.000000  0.691455  0.650748  0.706515
  4     0.449172 -0.005272  0.498935  0.691455  1.000000  0.704694  0.768275
  ...        ...       ...       ...       ...       ...       ...       ...
  5439 -0.008870 -0.050789 -0.000092 -0.044657 -0.028215  0.014286 -0.008765

In [19]:
check_dataset(dict_groups_subgroups_t_corr[groups_id[0]][subgroups_id[groups_id[0]][1]])

Checking dataset
Count infinite:	 0
Count nan:	 0
Count negative:	 7535862
Count zero:	 5612
Count positive:	 22095662
Count greater than 1:	 0
Count less than -1:	 0

In [20]:
def build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=0.3):
	dict_groups_subgroups_t_corr_g = {}
	for group_id, dict_groups in dict_groups_subgroups_t_corr.items():
		dict_aux = {}
		for subgroup_id, df_subgroup in dict_groups.items():
			# Percentil Correlaciones conservadas 	Densidad
			# 50	    50 %	                    Muy densa
            # 75	    25 %	                    Densa
            # 90	    10 %	                    Moderadamente dispersa
            # 95	    5 %	                        Dispersa
            # 99	    1 %	                        Muy dispersa
			threshold = np.percentile(np.abs(df_subgroup), 90)
			
			df_weighted_edges = (df_subgroup.where(np.triu(np.ones(df_subgroup.shape), k=1).astype(bool)).stack())
			df_weighted_edges = df_weighted_edges.dropna().to_frame()
			df_weighted_edges.reset_index(inplace=True)
			df_weighted_edges.columns = ["source", "target", "weight"]
			df_weighted_edges = df_weighted_edges[df_weighted_edges["weight"].abs() >= threshold]
			df_weighted_edges["subgroup"] = [subgroup_id] * len(df_weighted_edges)
			dict_aux[subgroup_id] = df_weighted_edges
			
			df_weighted_edges.to_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight"])
			# print(groups_id[i], subgroups_id[groups_id[i]][j], G.number_of_nodes(), G.number_of_edges())
			# nx.write_gexf(G, "experiments/output/{}/preprocessing/graphs/graphs_{}_{}.gexf".format(exp, groups_id[i], subgroups_id[groups_id[i]][j]))
		dict_groups_subgroups_t_corr_g[group_id] = dict_aux
	return dict_groups_subgroups_t_corr_g

In [21]:
# Build graph (corpus graphs)

# dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g = build_graph_weight_global_directed_new(exp, dict_groups_subgroups_t_corr, threshold=threshold_corr)
dict_groups_subgroups_t_corr_g[groups_id[0]][subgroups_id[groups_id[0]][0]].head()

    source  target    weight subgroup
42       0      43  0.513130        1
49       0      50  0.540938        1
50       0      51  0.580704        1
58       0      59  0.531386        1
63       0      64  0.632894        1

In [22]:
def create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups, df_join_raw_metadata):	
	for group_id in tqdm(groups_id):
		for subgroup_id in tqdm(subgroups_id[group_id]):
			df_weighted_edges = pd.read_csv("experiments/output/{}/preprocessing/edges/{}_{}.csv".format(exp, group_id, subgroup_id))
			# print(df_weighted_edges)
			G = nx.from_pandas_edgelist(df_weighted_edges, "source", "target", edge_attr=["weight", "subgroup"])
			dict_id_idx = dict(zip(list(G.nodes()), range(G.number_of_nodes())))
			G = nx.relabel_nodes(G, dict_id_idx)

			df_nodes = dict_df_groups_subgroups[group_id][subgroup_id].loc[list(dict_id_idx.keys())] # A_1.1, A_1.2, A_1.3
			# from IPython.display import display
			# display(df_nodes)

			# nodes, with node features
			metadata = df_join_raw_metadata.loc[df_nodes.index] # Average Rt, Average Mz
			# intensity = df_join_raw_log.loc[df_nodes.index] # A_1.1, A_1.2, A_1.3, A_2.1, ...

			""" e = 1e-8
			mz = metadata.iloc[:, 1].values
			rt = metadata.iloc[:, 0].values
			intensity_mean = df_nodes.mean(axis=1).values
			intensity_std = df_nodes.std(axis=1).values
			intensity_cv = intensity_std / intensity_mean
			presence_ratio = (df_nodes > 0).mean(axis=1)

			mz_log = np.log10(mz + e)
			# intensity_mean_log = np.log10(intensity_mean + e)
			
			# mz_z = (mz_log - mz_log.mean()) / mz_log.std() # z-score
			rt_z = (rt - rt.mean()) / rt.std() # z-score
			# intensity_mean_z = (intensity_mean_log - intensity_mean_log.mean()) / intensity_mean_log.std() # z-score

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": mz_log,
				"rt": rt_z,
				"intensity_mean": intensity_mean,
				"intensity_std": intensity_std,
				"intensity_cv": intensity_cv,
				"presence_ratio": presence_ratio
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			# df_node_features.insert(0, "idx", list(dict_id_idx.values()))
			# df_node_features.insert(1, "id", list(dict_id_idx.keys()))
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features) """

			data_node = {
				"idx": list(dict_id_idx.values()),
				"id": list(dict_id_idx.keys()),
				"mz": metadata.iloc[:, 1].values,
				"rt": metadata.iloc[:, 0].values,
			}
			for i in range(len(df_nodes.columns)):
				data_node[i] = df_nodes.iloc[:, i]

			df_node_features = pd.DataFrame(data_node)
			df_node_features.to_csv("experiments/output/{}/preprocessing/graphs_data/nodes_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)
			# print(df_node_features)

			# edges
			edges = list(G.edges())
			df_edges = pd.DataFrame(edges, columns=["source", "target"])
			df_edges["weight"] = [G.get_edge_data(*edge)["weight"] for edge in edges]
			df_edges["subgroup"] = [G.get_edge_data(*edge)["subgroup"] for edge in edges]
			df_edges.to_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id), index=False)

In [23]:
# create dataset - nodes/edge data for PyTorch Geometric/DGL framework

# IMPORTANT
dict_df_groups_subgroups_ = split_groups_subgroups(df_join_raw_intensity, groups_id, subgroups_id) # Important (intesities without Log)

for data_variation in data_variations:
	if data_variation == "none":
		create_graph_data_directed_features(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, df_join_raw_metadata)
	else:
		# dynamic graph to static graph
		create_graph_data_directed_variation(exp, groups_id, subgroups_id, dict_df_groups_subgroups_, data_variation)

100%|██████████| 18/18 [02:25<00:00,  8.06s/it]
100%|██████████| 1/1 [02:25<00:00, 145.07s/it]

In [24]:
# details
list_details = []
	
for group_id in groups_id:
	subgroups_id_ = []
	for data_variation in data_variations:
		if data_variation == "none":
			subgroups_id_ += subgroups_id[group_id]
		else:
			subgroups_id_ += [data_variation]
	# print(subgroups)
	
	for subgroup_id_ in subgroups_id_:
		try:
			df_edges = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/edges_{}_{}.csv".format(exp, group_id, subgroup_id_))

			G = nx.from_pandas_edgelist(df_edges.iloc[:, [0, 1]])
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), nx.density(G), np.nan, nx.is_connected(G)])
		except:
			list_details.append([group_id, subgroup_id_, G.number_of_nodes(), G.number_of_edges(), np.nan, np.nan, np.nan])

df_details = pd.DataFrame(list_details, columns=["Group", "Subgroup", "Num. nodes", "Num. edges", "Density", "Diameter", "Is connected"])
df_details.to_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp), index=False)

df_details = pd.read_csv("experiments/output/{}/preprocessing/graphs_data/summary.csv".format(exp))
df_details

,Group,Subgroup,Num. nodes,Num. edges,Density,Diameter,Is connected
0,disease,1,5346,1479135,0.103529,NaN,False
1,disease,10,5392,1479135,0.101770,NaN,False
2,disease,11,5444,1479135,0.099835,NaN,True
3,disease,12,5417,1479135,0.100832,NaN,False
4,disease,13,5438,1479135,0.100055,NaN,False
5,disease,14,5444,1479135,0.099835,NaN,True
6,disease,15,5431,1479135,0.100313,NaN,True
7,disease,16,5438,1479135,0.100055,NaN,True
8,disease,17,5412,1479135,0.101019,NaN,True
9,disease,18,5438,1479135,0.100055,NaN,True
10,disease,2,5441,1479135,0.099945,NaN,True
11,disease,3,5443,1479135,0.099871,NaN,True
12,disease,4,5430,1479135,0.100350,NaN,True
13,disease,5,5439,1479135,0.100018,NaN,True
14,disease,6,5427,1479135,0.100461,NaN,True
15,disease,7,5433,1479135,0.100239,NaN,True
16,disease,8,5428,1479135,0.100424,NaN,True
17,disease,9,5434,1479135,0.100202,NaN,False