In [1]:
# Torch version
!python -c "import torch; print(torch.__version__)"

# Cuda version
!python -c "import torch; print(torch.version.cuda)"

2.6.0+cu124
12.4

In [2]:
# Uninstall
# !pip uninstall torch-scatter torch-sparse torch-cluster torch-spline-conv pyg-lib -y

In [3]:
# Update Torch
# !pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu124

In [4]:
# Install PyG (automatic)
# !pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-{torch.__version__}.html
# !pip install torch_geometric

In [5]:
# Verify instalation
import torch
import torch_geometric
import torch_scatter

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch_scatter.__version__)
print(torch_geometric.__version__)

2.6.0+cu124
12.4
True
2.1.2+pt26cu124
2.7.0

In [6]:
from model_PyG import *
from utils import *

In [7]:
import json
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
import time
import torch
import torch.nn.functional as F
import torch_geometric.transforms as T

from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from torch_geometric.data import InMemoryDataset, Data
from torch_geometric.nn.conv.gcn_conv import gcn_norm
from torch_geometric.transforms import Compose
from torch_geometric.utils import dense_to_sparse, negative_sampling
from torch.nn.functional import binary_cross_entropy_with_logits
from torch.optim import Adam

In [8]:
import torch_geometric
print(torch_geometric.__version__)

np.random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

2.7.0

### Parameters

In [9]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"] # Change to static, e.g. "exp1"

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

raw_data_file = params["raw_data_file"]
print("Raw data:\t", raw_data_file)

methods = params["methods"]
print("Methods:\t", methods)

apply_transformation = params["apply_transformation"]
print("Has transformation:", apply_transformation)

dimension = params["dimension"]
print("Dimension:\t", dimension)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

cuda = params["cuda"]
print("Cuda:\t", cuda)

epochs = params["epochs"]
print("Epochs:\t", epochs)

lr = params["lr"]
print("Lr:\t", lr)

Exp:		 exp106
Raw data:	 ACM-DBLP
Methods:	 ['t-gae']
Has transformation: False
Dimension:	 1024
Groups id:	 ['ACM-DBLP']
Subgroups id:	 {'ACM-DBLP': ['1', '2']}
Cuda:	 1
Epochs:	 500
Lr:	 0.0001

### Setup

In [10]:
# Parameters models

dataset = exp
encoders = ["ORI", "GIN", "GINE"] # ["GIN", "GINE"] # ["GIN", "GINE"] # ["GIN", "GINE"] # Change
device = torch.device(f"cuda:{cuda}" if torch.cuda.is_available() else "cpu")
# device = torch.device("cpu")

NUM_HIDDEN_LAYERS = 12
HIDDEN_DIM = [1024] * NUM_HIDDEN_LAYERS + [1024]
output_feature_size = dimension # 128
# lr = 0.001
# epochs = 100

In [11]:
# Create datasets (groups and subgroups)

list_train_set = []

for group_id in groups_id:
	train_set = []
	for subgroup_id in subgroups_id[group_id]:
		train_set.append("{}_{}".format(group_id, subgroup_id))
	list_train_set.append(train_set)
list_train_set

[['ACM-DBLP_1', 'ACM-DBLP_2']]

### Create Data (PyG)

In [12]:
# Only for GIN
""" transform = Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	T.AddSelfLoops(fill_value=1.0),
	T.ToDevice(device)
]) """

# For GIN and GINE
transform = T.Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	# T.AddSelfLoops(attr="edge_attr", fill_value="mean"),
	# T.AddLaplacianEigenvectorPE(k=3, attr_name=None, is_undirected=True),
	# T.AddRandomWalkPE(walk_length=8, attr_name=None),
	T.ToDevice(device)
])

In [13]:
print("Loading training datasets")
has_edge_attributes = False
with_mean1 = True
with_mean2 = True

list_train_loader = []

if raw_data_file == "ACM_DBLP":
	group_id = groups_id[0]
	
	# Read dataset
	b = np.load("data/ACM-DBLP.npz")

	# Node matching
	test_pairs = b["test_pairs"].astype(np.int32)
	pos_pairs = b["pos_pairs"].astype(np.int32)
	df_node_alignment_truth = pd.DataFrame(np.concatenate((test_pairs, pos_pairs), axis=0))
	df_node_alignment_truth

	# Data preparation
	subgroup_id = 1
	edge_index1 = torch.tensor(b[f"edge_index{subgroup_id}"], dtype=torch.long)
	x1 = torch.tensor(b[f"x{subgroup_id}"], dtype=torch.float)

	subgroup_id = 2
	edge_index2 = torch.tensor(b[f"edge_index{subgroup_id}"], dtype=torch.long)
	x2 = torch.tensor(b[f"x{subgroup_id}"], dtype=torch.float)

elif raw_data_file == "Douban Online_Offline":
	group_id = groups_id[0]
	
	# Read dataset
	a1, f1, a2, f2, test_pairs = load_douban()

	# Node matching
	test_pairs = torch.tensor(np.array(test_pairs, dtype=int)) - 1
	test_pairs = test_pairs.numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs.T)
	df_node_alignment_truth

	# Create data
	edge_index1, _ = dense_to_sparse(torch.from_numpy(a1.toarray()))
	x1 = torch.from_numpy(f1.toarray()).float()

	edge_index2, _= dense_to_sparse(torch.from_numpy(a2.toarray()))
	x2 = torch.from_numpy(f2.toarray()).float()

	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "Cora1-Cora2":
	group_id = groups_id[0]
		
	# Read dataset
	loader = load_npz("data/cora.npz")
	data = loader["adj_matrix"]
	samples = data.shape[0]
	features = data.shape[1]
	values = data.data
	coo_data = data.tocoo()
	# indices = torch.LongTensor([coo_data.row, coo_data.col])
	indices = np.array([coo_data.row, coo_data.col])

	# Node matching
	N = 2708
	test_pairs = [[i, i] for i in range(N)]
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	node_features = loader["node_attr"]
	node_features = node_features.toarray()

	edge_index1 = torch.tensor(indices, dtype=torch.long)
	x1 = torch.tensor(node_features, dtype=torch.float)

	edge_index2 = torch.tensor(indices, dtype=torch.long)
	x2 = torch.tensor(node_features, dtype=torch.float)

	with_mean1 = False
	with_mean2 = True

elif raw_data_file == "flickr-lastfm":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/flickr-lastfm.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "douban":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/douban.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "flickr-myspace":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/flickr-myspace.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "ACM-DBLP":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/ACM-DBLP.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	# edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	# edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	# edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = False
	with_mean1 = True
	with_mean2 = True

elif raw_data_file == "cora":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/cora.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	# edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	# edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	# edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = False
	with_mean1 = False
	with_mean2 = True
	
# Create data
train_loader = {}

# Include edge_attr
subgroup_id = 1
data1 = Data(x=x1, edge_index=edge_index1)
if has_edge_attributes:
    data1.edge_attr = edge_attr1
else:
	data1 = add_edge_attributes(data1)
print(subgroup_id, data1)
info_data(data1, include_vectors=True)

subgroup_id = 2
data2 = Data(x=x2, edge_index=edge_index2)
if has_edge_attributes:
    data2.edge_attr = edge_attr2
else:
	data2 = add_edge_attributes(data2)
print(subgroup_id, data2)
info_data(data2, include_vectors=True)

# Normalize
normalize_node_edge_features(data1, data2, with_mean1=with_mean1, with_mean2=with_mean2) # Important

# Apply transform
subgroup_id = 1
data1 = transform(data1)
print(subgroup_id, data1)
# info(data1)

subgroup_id = 2
data2 = transform(data2)
print(subgroup_id, data2)
# info(data2)

# Include edge_weight
subgroup_id = 1
edge_index_norm1, edge_weight_norm1 = gcn_norm(
	data1.edge_index, num_nodes=data1.num_nodes, add_self_loops=False
)
data1.edge_index = edge_index_norm1
data1.edge_weight = edge_weight_norm1
train_loader[f"{group_id}_{subgroup_id}"] = data1
print(1, data1)

subgroup_id = 2
edge_index_norm2, edge_weight_norm2 = gcn_norm(
	data2.edge_index, num_nodes=data2.num_nodes, add_self_loops=False
)
data2.edge_index = edge_index_norm2
data2.edge_weight = edge_weight_norm2
train_loader[f"{group_id}_{subgroup_id}"] = data2
print(2, data2)

info_data(data1, include_vectors=True)
info_data(data2, include_vectors=True)

list_train_loader.append(train_loader)

Loading training datasets
1 Data(x=[9872, 17], edge_index=[2, 79122], edge_attr=[79122, 4])
Validate:	 True
Num. nodes:	 9872
Num. edges:	 79122
Num. features:	 17
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..., 9870, 9870, 9871],
        [   1,    2,    3,  ..., 1586, 2482, 4454]])
tensor([[61., 42., 16.,  ..., 14.,  1., 22.],
        [54., 18., 12.,  ..., 11.,  0., 16.],
        [54., 61.,  9.,  ..., 10.,  0., 39.],
        ...,
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  1.]])
tensor([[5.0000e+00, 1.3661e-02, 1.9170e+00, 9.2901e-01],
        [3.2000e+01, 1.0667e-01, 1.0993e+01, 9.5597e-01],
        [1.4000e+01, 4.4304e-02, 4.1508e+00, 8.7719e-01],
        ...,
        [3.0000e+00, 2.1429e-01, 1.1592e+00, 8.1650e-01],
        [3.0000e+00, 2.7273e-01, 1.1148e+00, 1.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 4.0825e-01]])
2 Data(x=[9916, 17], edge_index=[2, 89616], edge_attr=[89616, 4])
Validate:	 True
Num. nodes:	 9916
Num. edges:	 89616
Num. features:	 17
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..., 9915, 9915, 9915],
        [ 450, 4031, 4447,  ..., 2565, 3529, 5843]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 4., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.]])
tensor([[3.0000, 0.3000, 1.4871, 0.9045],
        [4.0000, 0.5000, 2.0085, 1.0000],
        [5.0000, 0.4545, 2.7328, 0.6667],
        ...,
        [4.0000, 0.6667, 1.8064, 1.0000],
        [4.0000, 0.1739, 2.1043, 0.5774],
        [4.0000, 0.5000, 1.9139, 0.8944]])
1 Data(x=[9872, 17], edge_index=[2, 79122], edge_attr=[79122, 4])
2 Data(x=[9916, 17], edge_index=[2, 89616], edge_attr=[89616, 4])
1 Data(x=[9872, 17], edge_index=[2, 79122], edge_attr=[79122, 4], edge_weight=[79122])
2 Data(x=[9916, 17], edge_index=[2, 89616], edge_attr=[89616, 4], edge_weight=[89616])
Validate:	 True
Num. nodes:	 9872
Num. edges:	 79122
Num. features:	 17
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..., 9870, 9870, 9871],
        [   1,    2,    3,  ..., 1586, 2482, 4454]], device='cuda:1')
tensor([[35.9977, 29.8167, 16.9089,  ..., 11.3303,  0.9390, 11.2458],
        [31.8366, 12.6461, 12.6217,  ...,  8.8336, -0.1510,  8.0856],
        [31.8366, 43.4100,  9.4064,  ...,  8.0014, -0.1510, 20.1998],
        ...,
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ...,  0.5113, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510,  0.1850]],
       device='cuda:1')
tensor([[-0.2277, -1.1920, -0.3072,  0.8449],
        [ 3.7580, -0.8807,  4.2052,  0.9504],
        [ 1.1009, -1.0894,  0.8035,  0.6423],
        ...,
        [-0.5230, -0.5204, -0.6839,  0.4049],
        [-0.5230, -0.3248, -0.7060,  1.1226],
        [-0.9658, -1.2377, -1.2603, -1.1918]], device='cuda:1')
Validate:	 True
Num. nodes:	 9916
Num. edges:	 89616
Num. features:	 17
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..., 9915, 9915, 9915],
        [ 450, 4031, 4447,  ..., 2565, 3529, 5843]], device='cuda:1')
tensor([[-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        ...,
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209,  4.2091,  0.1850],
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ...,  0.5113, -0.1510, -0.3417]],
       device='cuda:1')
tensor([[-0.5230, -0.2335, -0.5209,  0.7492],
        [-0.3753,  0.4360, -0.2617,  1.1226],
        [-0.2277,  0.2838,  0.0984, -0.1811],
        ...,
        [-0.3753,  0.9939, -0.3621,  1.1226],
        [-0.3753, -0.6556, -0.2141, -0.5305],
        [-0.3753,  0.4360, -0.3087,  0.7097]], device='cuda:1')

### Train

In [ ]:
def fit_TGAE_subgraph(model, encoder, exp, group_id, subgroups_id, train_loader, train_set, no_samples, epochs, lr):
	list_loss = []

	optimizer = Adam(model.parameters(), lr=lr, weight_decay=5e-4)
	
	# Initialize early stopping
	patience = 10
	delta = 1e-4
	warmup = 10
	early_stopping = EarlyStopping(patience=patience, delta=delta, warmup=warmup, verbose=True)

	loop_obj = tqdm(range(1, epochs + 1))
	
	# Train mode
	model.train() # Set the model to training mode (enables dropout and BN updates)
	
	for epoch in loop_obj:
		loop_obj.set_description(f"Epoch: {epoch}")
		
		optimizer.zero_grad() # Reset accumulated gradients before backpropagation
		
		loss = torch.tensor(0.0, device=device)
		
		for ts in random.sample(train_set, k=len(train_set)): # shuffle train_set
			data = train_loader[ts]

			# Encoder
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
				# z = F.normalize(z, dim=1)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)
			elif encoder == "ORI":
				z = model(data.x, data.edge_index, data.edge_weight)

			# Positive edges
			pos_edge_index = data.edge_index
			
			# Negative edges
			# option 1
			neg_edge_index = negative_sampling(
				edge_index=data.edge_index,
				num_nodes=z.size(0),
				num_neg_samples=pos_edge_index.size(1), # Change 2 to other value if needed
				method="sparse"
			)

			# option 2 Negative edges (dynamic)
			""" ratio = neg_ratio_schedule(epoch, epochs)
			num_neg = compute_num_neg_samples(
				edge_index=edge_index,
				num_nodes=z.size(0),
				ratio=ratio
			)
			neg_edge_index = negative_sampling(
				edge_index=edge_index,
				num_nodes=z.size(0),
				num_neg_samples=num_neg,
				method="sparse"
			) """
			
			# Decoder
			# option 1
			pos_logits = (z[pos_edge_index[0]] * z[pos_edge_index[1]]).sum(dim=1)
			neg_logits = (z[neg_edge_index[0]] * z[neg_edge_index[1]]).sum(dim=1)
			
			# option 2
			""" pos_logits = F.cosine_similarity(
				z[pos_edge_index[0]],
				z[pos_edge_index[1]],
				dim=1
			)
			neg_logits = F.cosine_similarity(
				z[neg_edge_index[0]],
				z[neg_edge_index[1]],
				dim=1
			) """

			# Loss
			pos_labels = torch.ones_like(pos_logits)
			neg_labels = torch.zeros_like(neg_logits)

			# option 1
			""" loss_pos = binary_cross_entropy_with_logits(pos_logits, pos_labels)
			loss_neg = binary_cross_entropy_with_logits(neg_logits, neg_labels)
			loss += loss_pos + loss_neg """

			# option 2
			# num_pos = pos_edge_index.size(1)
			# num_neg = neg_edge_index.size(1)
			# pos_weight = torch.tensor([num_neg / num_pos], device=device)
			logits = torch.cat([pos_logits, neg_logits], dim=0)
			labels = torch.cat([pos_labels, neg_labels], dim=0)
			loss_temp = F.binary_cross_entropy_with_logits(logits, labels) #, pos_weight=pos_weight) # with pos_weight
			loss += loss_temp
			
		loss = loss / no_samples
		loss.backward() # Compute gradients of the loss w.r.t. model parameters
		optimizer.step() # Update model parameters using computed gradients

		loop_obj.set_postfix_str(f"Loss: {loss.item():.4f}")
		list_loss.append(loss.item())

		# Check early stopping condition
		early_stopping.check_early_stop(loss.item(), epoch)
		if early_stopping.stop_training:
			print(f"Early stopping at epoch {epoch}")
			break
		# torch.cuda.empty_cache()
	# Evaluation (for others dataset)
	list_df_node_embeddings = []

	model.eval() # Set the model to evaluation mode (disables dropout and BN updates)
	with torch.no_grad():
		for subgroup_id in subgroups_id:

			# Get node embeddings
			data = train_loader[f"{group_id}_{subgroup_id}"]
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)
			elif encoder == "ORI":
				z = model(data.x, data.edge_index, data.edge_weight)
			
			df_node_embeddings = pd.DataFrame(z.cpu().numpy())
			df_node_embeddings["subgroup_id"] = [subgroup_id] * len(df_node_embeddings)
			
			# Get node ids to replace original Id (this is only for MS data)
			""" df_nodes = pd.read_csv(f"experiments/output/{exp}/preprocessing/graphs_data/nodes_{group_id}_{subgroup_id}.csv")
			# idx, id, mz, rt, intensity_mean, intensity_cv
			df_node_embeddings.insert(0, "Id", df_nodes["id"].values) """

			df_node_embeddings.insert(0, "Id", range(len(df_node_embeddings))) # this is only for no MS data
			list_df_node_embeddings.append(df_node_embeddings)

		# Concat node embeddings
		df_node_embeddings_concat = pd.concat(list_df_node_embeddings, ignore_index=True)
		
		# Save node embeddings
		df_node_embeddings_concat.to_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", index=False)
	
	# Save loss
	np.save(f"experiments/output/{exp}/loss/{encoder}_{group_id}.npy", np.array(list_loss))

	del loss, z
	# torch.cuda.synchronize()
	torch.cuda.empty_cache()

In [15]:
encoders

['ORI', 'GIN', 'GINE']

In [16]:
list_train_set

[['ACM-DBLP_1', 'ACM-DBLP_2']]

In [17]:
list_train_loader

[{'ACM-DBLP_1': Data(x=[9872, 17], edge_index=[2, 79122], edge_attr=[79122, 4], edge_weight=[79122]),
  'ACM-DBLP_2': Data(x=[9916, 17], edge_index=[2, 89616], edge_attr=[89616, 4], edge_weight=[89616])}]

In [18]:
list_runtime = []

for encoder in encoders:
	for i, train_loader in enumerate(list_train_loader):
		""" np.random.seed(0)
		torch.manual_seed(0)
		torch.cuda.manual_seed(0)
		torch.cuda.manual_seed_all(0)
		torch.backends.cudnn.deterministic = True
		torch.backends.cudnn.benchmark = False """

		group_id = groups_id[i]
		subgroup_id = subgroups_id[group_id]

		train_set = list_train_set[i]

		no_samples = len(train_set) # * (1 + 1)  # num datasets * num of samples by dataset 
		input_dim = train_loader[train_set[0]].num_node_features

		if encoder == "GIN":
			model = TGAE_GIN(NUM_HIDDEN_LAYERS, 
						input_dim,
						HIDDEN_DIM,
						output_feature_size).to(device)
		elif encoder == "GINE":
			edge_dim = train_loader[train_set[0]].edge_attr.size(1)

			model = TGAE_GINE(NUM_HIDDEN_LAYERS,
						input_dim,
						HIDDEN_DIM,
						output_feature_size, edge_dim).to(device)
		elif encoder == "ORI":
			model = TGAE_Original(NUM_HIDDEN_LAYERS,
						input_dim,
						HIDDEN_DIM,
						output_feature_size).to(device)

		print("Fitting model")
		print(encoder, dataset, train_set, lr, epochs, input_dim, output_feature_size, no_samples)

		# Calculate elapsed time
		start_time = time.perf_counter()
		
		fit_TGAE_subgraph(model, encoder, dataset, group_id, subgroup_id, train_loader, train_set, no_samples, epochs, lr)

		end_time = time.perf_counter()
		execution_time = end_time - start_time

		list_runtime.append(execution_time)

Fitting model
ORI exp106 ['ACM-DBLP_1', 'ACM-DBLP_2'] 0.0001 500 17 1024 2

Epoch: 349:  70%|██████▉   | 348/500 [02:36<01:08,  2.23it/s, Loss: 0.3982]

Stopping early as no improvement has been observed.
Early stopping at epoch 349
Fitting model
GIN exp106 ['ACM-DBLP_1', 'ACM-DBLP_2'] 0.0001 500 17 1024 2

Epoch: 168:  33%|███▎      | 167/500 [02:48<05:35,  1.01s/it, Loss: 0.3871]

Stopping early as no improvement has been observed.
Early stopping at epoch 168
Fitting model
GINE exp106 ['ACM-DBLP_1', 'ACM-DBLP_2'] 0.0001 500 17 1024 2

Epoch: 430:  86%|████████▌ | 429/500 [08:05<01:20,  1.13s/it, Loss: 0.4042]

Stopping early as no improvement has been observed.
Early stopping at epoch 430

### Similarity analysis

In [19]:
k = 1 # Change
# list_count_meta = []

for encoder in encoders:
	for group_id in groups_id:
		df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
		# Id, 0, 1,	2, ..., subgroup_id

		subgroups_id_ = subgroups_id[group_id]

		# Calculate distance matrix (KNN)
		knn = NearestNeighbors(n_neighbors=k, metric="euclidean")

		df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroups_id_[0]]
		x = df_node_embeddings.iloc[:, 1:-1].values

		df_node_alignment = pd.DataFrame()
		df_node_alignment[f"{group_id}_{subgroups_id_[0]}"] = df_node_embeddings["Id"].values

		for subgroup_id in subgroups_id_[1:]:
			df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroup_id]
			y = df_node_embeddings.iloc[:, 1:-1].values

			knn.fit(y)
			distances, indices = knn.kneighbors(x)
			indices = indices.squeeze() # (N,)

			df_node_alignment[f"{group_id}_{subgroup_id}"] = df_node_embeddings["Id"].values[indices]
			
			""" df_node_alignment[f"distances"] = distances
			avg_distances = df_node_alignment["distances"].mean()
			df_node_alignment = df_node_alignment[df_node_alignment["distances"] <= avg_distances].iloc[:, :-1]
			df_node_alignment """
		
		# Save previus node alignment
		df_node_alignment.to_csv(f"experiments/output/{exp}/filter_raw/node_alignment_{encoder}_{group_id}.csv")
		display(df_node_alignment)

		# Find node alignment for all datasets
		""" df_node_alignment_filter = df_node_alignment[df_node_alignment.nunique(axis=1) == 1]
		list_count_meta.append([encoder, group_id, len(df_node_alignment_filter), len(df_node_alignment)])
		# print(len(df_node_alignment_filter))
		# display(df_node_alignment_filter)
		print(f"{encoder}-{group_id}: {len(df_node_alignment_filter)}")
		
		# Save common node id
		# common_node_id = df_node_alignment_filter.iloc[:, 0].values
		# np.save(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy", np.array(common_node_id)) """

		# Save common node id as .csv
		df_common_node_id = df_node_alignment.iloc[:, [0, 1]].copy() # df_common_node_id = df_node_alignment_filter.iloc[:, [0, 1]].copy()
		df_common_node_id.sort_values(by=df_common_node_id.columns[0], inplace=True)
		df_common_node_id.to_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", index=False, header=False)

# Intersection and Union
""" list_common_node_id = []
for encoder in encoders:
	for group_id in groups_id:
		# Read common node
		common_node_id = np.load(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy")
		list_common_node_id.append(common_node_id)

	common_node_id_union = list(set.union(*map(set, list_common_node_id)))
	common_node_id_intersection = list(set.intersection(*map(set, list_common_node_id)))

	# Save common node id
	np.save(f"experiments/output/{exp}/common_nodes/{encoder}_union.npy", np.array(common_node_id_union))
	np.save(f"experiments/output/{exp}/common_nodes/{encoder}_intersection.npy", np.array(common_node_id_intersection)) """

      ACM-DBLP_1  ACM-DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        5642
9870        9870        5284
9871        9871        2962

[9872 rows x 2 columns]

      ACM-DBLP_1  ACM-DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        2258
9870        9870        9404
9871        9871        7124

[9872 rows x 2 columns]

      ACM-DBLP_1  ACM-DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        6758
9868        9868        9011
9869        9869        2258
9870        9870        5284
9871        9871        2368

[9872 rows x 2 columns]

' list_common_node_id = []\nfor encoder in encoders:\n\tfor group_id in groups_id:\n\t\t# Read common node\n\t\tcommon_node_id = np.load(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy")\n\t\tlist_common_node_id.append(common_node_id)\n\n\tcommon_node_id_union = list(set.union(*map(set, list_common_node_id)))\n\tcommon_node_id_intersection = list(set.intersection(*map(set, list_common_node_id)))\n\n\t# Save common node id\n\tnp.save(f"experiments/output/{exp}/common_nodes/{encoder}_union.npy", np.array(common_node_id_union))\n\tnp.save(f"experiments/output/{exp}/common_nodes/{encoder}_intersection.npy", np.array(common_node_id_intersection)) '

### Evaluation

In [20]:
df_node_alignment_truth

         0     1
0     9686  5356
1     1303  6620
2     3080  1745
3     5071  7441
4     2476  3459
...    ...   ...
6320  3770  7937
6321  6314  1944
6322  6379   136
6323  6689  2746
6324  5414  4062

[6325 rows x 2 columns]

In [21]:
list_accuracy = []
list_encoder = []

for encoder in encoders:
	for group_id in groups_id:
		# Read node alignment
		df_common_node_id = pd.read_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", header=None)
		# df_common_node_id[[0, 1]] = np.sort(df_common_node_id[[0, 1]], axis=1)

		# Evaluation
		df_matching = df_common_node_id.merge(df_node_alignment_truth, on=[0, 1], how="inner")

		# Accuracy
		accuracy = len(df_matching) / len(df_node_alignment_truth)
		
		list_accuracy.append(accuracy)
		list_encoder.append(encoder)

##### Summary

In [22]:
dict_summary = {
	"Dataset": [raw_data_file] * len(encoders),
	"Model": list_encoder,
	"Accuracy": list_accuracy,
	"Runtime": list_runtime
}
df_summary = pd.DataFrame(dict_summary)
df_summary

    Dataset Model  Accuracy     Runtime
0  ACM-DBLP   ORI  0.594941  165.449806
1  ACM-DBLP   GIN  0.579130  177.401442
2  ACM-DBLP  GINE  0.579605  494.940341

### Evaluation (based on PlanetAlign)

In [23]:
# Get node embeddings
dict_node_embeddings = {}
for encoder in encoders:
	list_node_embeddings = []
	for group_id in groups_id:
		df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
		# Id, 0, 1,	2, ..., subgroup_id

		for subgroup_id in subgroups_id[group_id]:
			df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroup_id]
			list_node_embeddings.append(df_node_embeddings)
	dict_node_embeddings[encoder] = list_node_embeddings

In [24]:
dict_node_embeddings

{'ORI': [        Id         0         1         2         3         4         5  \
  0        0 -0.197898  0.088115 -0.390187  0.029399 -0.040156 -0.504372
  1        1  0.020203 -0.284813  0.018559 -0.229247  0.251266 -0.663811
  2        2 -0.142015 -0.162797 -0.480829  0.067704 -0.286718 -0.270100
  3        3 -0.122216 -0.036749 -0.235517  0.048686 -0.002606 -0.285599
  4        4  0.143009  0.216094  0.023243  0.171887  0.056080  0.129330
  ...    ...       ...       ...       ...       ...       ...       ...
  9867  9867 -0.002302 -0.079015  0.012295 -0.017874  0.032145 -0.015225
  9868  9868  0.010427 -0.033209  0.056148  0.131866  0.005186  0.044449
  9869  9869  0.008192 -0.069267  0.031061  0.093679  0.007376 -0.057815
  9870  9870 -0.016993 -0.016766 -0.008230  0.035430 -0.036187 -0.017368
  9871  9871  0.084408  0.066200 -0.028000  0.005625  0.032536 -0.008433

               6         7         8  ...      1015      1016      1017  \
  0    -0.152131 -0.064741 -0.435226  ...  0.152874 -0.111517  0.470615
  1    -0.005611 -0.276786  0.161006  ... -0.189969 -0.279929  0.576527
  2    -0.457461 -0.064959 -0.686350  ... -0.061483 -0.102026  0.658998
  3    -0.131525 -0.289819 -0.101139  ...  0.013954  0.114119  0.073411
  4     0.012488  0.048415  0.405331  ... -0.067133 -0.071501  0.360768
  ...        ...       ...       ...  ...       ...       ...       ...
  9867 -0.146821 -0.009811 -0.045324  ...  0.014628 -0.060635  0.000365
  9868  0.025954 -0.004548 -0.046518  ...  0.068839  0.046856 -0.050647
  9869 -0.036537 -0.006942  0.038088  ... -0.029554  0.012424 -0.008896
  9870 -0.082232  0.039112 -0.058108  ...  0.030783  0.000077  0.018446
  9871 -0.037566  0.043210 -0.135063  ...  0.072178 -0.056052  0.064509

            1018      1019      1020      1021      1022      1023  subgroup_id
  0    -0.191389  0.477963 -0.631947 -0.117005  0.636127 -0.265193            1
  1     0.024593  0.520614 -0.475957 -0.235774  0.524581 -0.370483            1
  2    -0.400340  0.777268 -0.404614  0.410492  0.313590 -0.550285            1
  3    -0.044978  0.381234  0.031806 -0.056798  0.287076 -0.136549            1
  4    -0.221473 -0.072923 -0.040185 -0.131145 -0.186883  0.371196            1
  ...        ...       ...       ...       ...       ...       ...          ...
  9867 -0.000364 -0.002148  0.101874  0.062298 -0.077011 -0.059677            1
  9868 -0.020909  0.003262 -0.052111  0.073722  0.051859  0.013512            1
  9869  0.035967  0.046610  0.012647  0.033335  0.020349 -0.045094            1
  9870 -0.035385 -0.014452 -0.005320  0.019663 -0.005964 -0.036744            1
  9871 -0.011811  0.008502 -0.027866  0.081452  0.020329 -0.106790            1

  [9872 rows x 1026 columns],
           Id         0         1         2         3         4         5  \
  9872      0  0.014902  0.006592  0.000409 -0.045430  0.116172 -0.019757
  9873      1  0.173745 -0.178478 -0.027860  0.068954  0.077393  0.015657
  9874      2 -0.000645 -0.048112  0.014982  0.064430  0.029348  0.045755
  9875      3  0.011826 -0.080708 -0.060920  0.011379 -0.013405  0.020623
  9876      4  0.094814  0.148244  0.140124 -0.070834  0.013939  0.156715
  ...     ...       ...       ...       ...       ...       ...       ...
  19783  9911 -0.077277 -0.042205 -0.025626 -0.057102 -0.051444  0.021457
  19784  9912  0.008305 -0.025231 -0.029900  0.015525 -0.053007 -0.021853
  19785  9913 -0.007862 -0.016540 -0.014117 -0.017105 -0.015193 -0.049426
  19786  9914  0.044479  0.026704  0.000141 -0.032233 -0.045970  0.007427
  19787  9915 -0.004601 -0.009640  0.027757  0.006455 -0.065336 -0.042616

                6         7         8  ...      1015      1016      1017  \
  9872  -0.045981 -0.112966 -0.142874  ...  0.005967 -0.068803  0.101097
  9873  -0.005254  0.056758  0.097888  ... -0.093743  0.053923 -0.041476
  9874   0.028601  0.002259 -0.015810  ...  0.056891  0.108479 -0.052696
  9875  -0.071993 -0.109618  0.088654  ...  0.042672 -0.002085  0.141266
  9876   0.080524 -0.019912  0.185855  ...  0.007023  0.028090  0.090798
  ...         ...       ...       ...  ...       ...       ...       ...
  19783  0.054445  0.047860  0.036561  ... -0.056298  0.071662 -0.029962
  19784 -0.071485  0.092171 -0.055024  ... -0.036983 -0.012014  0.076472
  19785 -0.053203 -0.078417 -0.027139  ...  0.048937 -0.095200 -0.022709
  19786  0.109300 -0.023825 -0.073773  ...  0.010171 -0.104360 -0.045299
  19787 -0.070671  0.050266 -0.019316  ...  0.050044  0.026275 -0.079601

             1018      1019      1020      1021      1022      1023  subgroup_id
  9872  -0.087405  0.082891 -0.095476  0.074765 -0.029593 -0.021448            2
  9873  -0.058008  0.034826  0.014646  0.110906  0.046302 -0.071695            2
  9874  -0.045760 -0.000918 -0.082613  0.053501  0.006953  0.087871            2
  9875   0.065387  0.238443  0.193181  0.025271 -0.029055 -0.093483            2
  9876  -0.025293  0.061660 -0.113696  0.058700 -0.205684  0.078254            2
  ...         ...       ...       ...       ...       ...       ...          ...
  19783  0.044048 -0.000540  0.027070  0.014826 -0.006374  0.040932            2
  19784 -0.042410 -0.000466 -0.055943  0.105063 -0.008956  0.001328            2
  19785  0.057692 -0.015341  0.026489 -0.025672 -0.005159  0.017692            2
  19786  0.027527 -0.019553  0.099264 -0.035362  0.053751 -0.085296            2
  19787 -0.012554 -0.016135 -0.017427 -0.038078 -0.075000 -0.049126            2

  [9916 rows x 1026 columns]],
 'GIN': [        Id         0         1         2         3         4         5  \
  0        0  0.158342  0.001899  0.227141  0.141517  0.220830  0.226062
  1        1 -0.129716 -0.114668  0.232077  0.186902 -0.007244 -0.047036
  2        2  0.191585  0.006381  0.162843  0.624131  0.206253  0.451923
  3        3  0.153650  0.121331  0.289848  0.106043  0.094161  0.223683
  4        4  0.015336 -0.262524 -0.004946  0.367859  0.147370 -0.008887
  ...    ...       ...       ...       ...       ...       ...       ...
  9867  9867 -0.037005 -0.045224 -0.017162 -0.083046 -0.071530  0.156951
  9868  9868  0.105995  0.055895  0.045299 -0.062120  0.101878  0.046498
  9869  9869  0.037629  0.006557  0.090193  0.096364 -0.017889 -0.042286
  9870  9870  0.052755 -0.040263 -0.050392  0.032994 -0.009084  0.105140
  9871  9871 -0.026703  0.010964 -0.088800  0.027524 -0.005437 -0.012321

               6         7         8  ...      1015      1016      1017  \
  0     0.506046  0.415070  0.195257  ...  0.027694 -0.171557 -0.264353
  1     0.101211  0.394779 -0.030905  ...  0.072068 -0.168828 -0.536249
  2     0.371607  0.370747  0.427720  ... -0.032117 -0.047789 -0.145145
  3     0.249333  0.067373  0.188346  ... -0.074873  0.061683 -0.036414
  4     0.157404 -0.084373  0.040773  ...  0.028657  0.042061 -0.187821
  ...        ...       ...       ...  ...       ...       ...       ...
  9867  0.060539 -0.064898 -0.114538  ... -0.017018  0.054419 -0.085709
  9868 -0.022470  0.039682  0.077184  ...  0.032458 -0.016128  0.083872
  9869  0.091045  0.022522  0.055067  ... -0.049850  0.037190  0.120402
  9870 -0.002318  0.026952  0.025949  ... -0.024952 -0.102004 -0.014980
  9871  0.079786  0.050376 -0.082632  ...  0.008559  0.079411  0.078378

            1018      1019      1020      1021      1022      1023  subgroup_id
  0     0.241720 -0.789902  0.027900  0.412288  0.323308  0.056046            1
  1     0.177016 -0.500192  0.010433  0.327439  0.428876 -0.283765            1
  2     0.117412 -1.101156 -0.056064  0.305190  0.513978  0.346690            1
  3     0.084523 -0.423481 -0.073621  0.134762  0.152506  0.240618            1
  4    -0.102009 -0.316056 -0.261635 -0.238288  0.084287 -0.273129            1
  ...        ...       ...       ...       ...       ...       ...          ...
  9867  0.015702  0.078229 -0.121099  0.071148 -0.047386 -0.016805            1
  9868 -0.045202  0.057300 -0.024591 -0.005022  0.040943  0.161647            1
  9869 -0.061023 -0.056498 -0.033096 -0.010108  0.022377 -0.001333            1
  9870 -0.012259  0.039122  0.041315 -0.003807 -0.066578  0.072769            1
  9871  0.037778  0.002552  0.001497  0.116859 -0.007423 -0.043456            1

  [9872 rows x 1026 columns],
           Id         0         1         2         3         4         5  \
  9872      0 -0.031325  0.004863 -0.008554  0.053169 -0.055125  0.084201
  9873      1  0.029880 -0.119791  0.098741  0.094734 -0.040927 -0.093512
  9874      2 -0.038206  0.038005 -0.013348 -0.000292  0.109520 -0.111420
  9875      3  0.097360  0.152358  0.091886  0.153527  0.038253  0.040640
  9876      4 -0.020787 -0.221825 -0.043635  0.236805  0.002397 -0.027135
  ...     ...       ...       ...       ...       ...       ...       ...
  19783  9911 -0.096835  0.081523  0.025241 -0.042455  0.012231 -0.043484
  19784  9912 -0.010607 -0.130615  0.061155 -0.037351  0.101693 -0.004659
  19785  9913 -0.065802 -0.009393  0.071904 -0.088114 -0.010608  0.041868
  19786  9914 -0.013211  0.010416  0.048610  0.028717 -0.024349  0.044689
  19787  9915  0.058800 -0.020650 -0.124830 -0.101821  0.042740 -0.061567

                6         7         8  ...      1015      1016      1017  \
  9872  -0.014272 -0.010274  0.014823  ...  0.055763 -0.005520  0.065036
  9873   0.088106  0.076931 -0.025033  ... -0.038860  0.063248 -0.048434
  9874  -0.128885 -0.012990  0.099918  ... -0.005526 -0.026528  0.087651
  9875   0.114934 -0.024794  0.057172  ... -0.061361  0.043818 -0.049248
  9876   0.086507 -0.026040 -0.036216  ...  0.066109  0.094090 -0.149299
  ...         ...       ...       ...  ...       ...       ...       ...
  19783 -0.058715 -0.008279 -0.028319  ...  0.034971 -0.036667  0.001809
  19784 -0.046426 -0.062158  0.026627  ...  0.025366  0.112970  0.046590
  19785 -0.064255  0.075291 -0.080267  ... -0.086255 -0.019985  0.019284
  19786 -0.111929  0.016633  0.057967  ...  0.007892  0.040212  0.082493
  19787  0.026365  0.021818 -0.016595  ...  0.015846 -0.081892  0.120621

             1018      1019      1020      1021      1022      1023  subgroup_id
  9872  -0.050332  0.029570  0.043911  0.006227  0.031449  0.061551            2
  9873  -0.000561  0.057246 -0.036570  0.087212 -0.039055 -0.039545            2
  9874  -0.124246  0.086992 -0.123289 -0.015162  0.090182  0.048903            2
  9875  -0.027874 -0.062451  0.057280  0.006718 -0.031611  0.000442            2
  9876  -0.030282 -0.194267 -0.239003 -0.055513  0.048664 -0.223141            2
  ...         ...       ...       ...       ...       ...       ...          ...
  19783 -0.098801 -0.040876 -0.070814 -0.016963  0.015687  0.042903            2
  19784  0.011114 -0.038580 -0.060334  0.001842  0.042264 -0.068483            2
  19785  0.150283  0.060876  0.058881 -0.026337  0.009113  0.009045            2
  19786  0.080966  0.037337 -0.004246  0.061273  0.041050  0.073346            2
  19787  0.013878 -0.087859 -0.016662 -0.063844  0.014214 -0.031368            2

  [9916 rows x 1026 columns]],
 'GINE': [        Id         0         1         2         3         4         5  \
  0        0 -0.430193  0.281922 -0.001805  0.012452 -0.002486 -0.625501
  1        1 -0.546381  0.226400  0.053490  0.294675  0.053639 -0.563056
  2        2 -0.430980  0.224305 -0.085815 -0.058313 -0.133190 -0.337639
  3        3 -0.028005  0.106487 -0.174206 -0.197179  0.103175 -0.077608
  4        4 -0.086197  0.081916  0.001997 -0.104172  0.165974  0.099802
  ...    ...       ...       ...       ...       ...       ...       ...
  9867  9867  0.043215  0.108555  0.000201  0.147222  0.003042  0.033690
  9868  9868  0.047136  0.046987  0.000961  0.006305 -0.017221 -0.089046
  9869  9869 -0.060156  0.068799 -0.042402  0.008366  0.065110  0.009603
  9870  9870 -0.002098 -0.094652  0.061210 -0.062698 -0.028580  0.054160
  9871  9871 -0.011634  0.090425  0.011457  0.047214  0.061460 -0.005348

               6         7         8  ...      1015      1016      1017  \
  0     0.183817 -0.105545 -0.084453  ...  0.151070 -0.212258 -0.498325
  1     0.060028 -0.060991 -0.114311  ...  0.173500 -0.440882 -0.553253
  2     0.113461 -0.249192  0.099005  ...  0.264843  0.026495 -0.654240
  3    -0.118136  0.140593 -0.032537  ...  0.042791 -0.043805 -0.259670
  4     0.191074 -0.092022 -0.158133  ...  0.390029  0.098833 -0.019169
  ...        ...       ...       ...  ...       ...       ...       ...
  9867 -0.026528 -0.059362  0.040256  ... -0.030124 -0.058250 -0.007377
  9868  0.118496  0.046968 -0.026114  ...  0.063927 -0.010099 -0.056526
  9869 -0.009748  0.072937 -0.009142  ...  0.094189  0.001381 -0.112522
  9870  0.016337 -0.009964  0.047074  ... -0.027963  0.046764  0.069430
  9871  0.025962 -0.017781  0.014648  ...  0.064399 -0.017110  0.004231

            1018      1019      1020      1021      1022      1023  subgroup_id
  0     0.465456  0.216053 -0.006726 -0.770230  0.225711  0.141450            1
  1     0.275728  0.126607 -0.172911 -0.557705  0.131668 -0.007256            1
  2     0.564833  0.418098  0.187938 -0.729255  0.308674  0.118604            1
  3     0.167810  0.013506 -0.124645 -0.138622  0.007198 -0.065714            1
  4     0.315531 -0.213566  0.062376 -0.412996  0.027282  0.013870            1
  ...        ...       ...       ...       ...       ...       ...          ...
  9867 -0.045405  0.027863  0.001980  0.097859  0.022323 -0.029902            1
  9868 -0.046742  0.017485  0.051020  0.066071  0.012248  0.056058            1
  9869 -0.078146  0.012819 -0.095219  0.082107 -0.100872 -0.014460            1
  9870  0.093067 -0.032752 -0.033112  0.057426  0.030326 -0.044855            1
  9871 -0.026710  0.023988  0.009281 -0.015709 -0.119893 -0.001829            1

  [9872 rows x 1026 columns],
           Id         0         1         2         3         4         5  \
  9872      0  0.018417 -0.014450  0.090908 -0.027369  0.055922  0.132752
  9873      1 -0.126657 -0.037232 -0.008149  0.039889  0.059823  0.040236
  9874      2 -0.013104 -0.046203  0.030389  0.048824 -0.055016 -0.042632
  9875      3 -0.032867  0.086476 -0.211817 -0.020494 -0.050893  0.129708
  9876      4 -0.016604  0.036801  0.014268 -0.051942  0.079697 -0.002638
  ...     ...       ...       ...       ...       ...       ...       ...
  19783  9911 -0.020422 -0.049767  0.015689 -0.039961 -0.095446  0.012575
  19784  9912  0.032435 -0.065138 -0.069478  0.003283 -0.048500 -0.122431
  19785  9913  0.058495  0.028052  0.086296 -0.024835 -0.063099  0.182475
  19786  9914  0.013673 -0.008746  0.037199 -0.067532  0.073750 -0.065706
  19787  9915  0.112586 -0.056586  0.041951 -0.064170 -0.035334  0.014627

                6         7         8  ...      1015      1016      1017  \
  9872  -0.086864 -0.042608  0.027778  ... -0.065300  0.101754  0.135361
  9873  -0.102231  0.037961  0.047734  ...  0.028866 -0.044461 -0.060904
  9874   0.088357  0.047222 -0.031751  ...  0.080771 -0.053588 -0.055008
  9875  -0.131342  0.039744 -0.016369  ... -0.080225 -0.003921  0.013310
  9876   0.122403  0.012166 -0.081855  ...  0.254334  0.025408 -0.085384
  ...         ...       ...       ...  ...       ...       ...       ...
  19783  0.006400 -0.042057 -0.048528  ...  0.028477 -0.020096 -0.040814
  19784 -0.094056 -0.026517  0.009439  ... -0.102817  0.121262  0.065708
  19785  0.023156  0.012910  0.002155  ... -0.063334  0.034173  0.033388
  19786 -0.027698 -0.025392  0.001312  ... -0.011250  0.039001  0.051083
  19787  0.013069  0.009166  0.078568  ... -0.111004  0.050234  0.073161

             1018      1019      1020      1021      1022      1023  subgroup_id
  9872   0.030578  0.090508  0.002109 -0.037015 -0.059530  0.009708            2
  9873   0.058694 -0.040908 -0.145798  0.032214 -0.095795 -0.012339            2
  9874  -0.007743  0.039048  0.069844  0.041967 -0.055299  0.005621            2
  9875   0.053951  0.060247 -0.067042 -0.036418  0.036314 -0.052247            2
  9876   0.141776 -0.028638 -0.021979 -0.075167  0.099227  0.105984            2
  ...         ...       ...       ...       ...       ...       ...          ...
  19783  0.004680  0.012471  0.024388 -0.032881  0.038116 -0.050323            2
  19784 -0.011012 -0.001719 -0.012460 -0.008454 -0.055023  0.013883            2
  19785  0.065838  0.023691 -0.104201  0.072589 -0.097418  0.026661            2
  19786  0.005054  0.000409  0.015984  0.033578 -0.022513 -0.007250            2
  19787  0.080597 -0.088017  0.038659  0.091715  0.127585 -0.096125            2

  [9916 rows x 1026 columns]]}

In [25]:
# Evaluation
list_metrics = []

df_node_alignment_truth_ = torch.tensor(df_node_alignment_truth.values)

for encoder in encoders:
	list_node_embeddings = dict_node_embeddings[encoder]
	# Id, 0, 1,	2, ..., subgroup_id

	emb1 = list_node_embeddings[0].iloc[:, 1:-1]
	emb2 = list_node_embeddings[1].iloc[:, 1:-1]

	emb1_ = torch.tensor(emb1.values)
	emb2_ = torch.tensor(emb2.values)

	# Similarity matrix
	# Option 1
	# S = pairwise_cosine_similarity(emb1_, emb2_)

	# Option 2
	""" S = cosine_similarity(emb1, emb2)
	S = torch.tensor(S) """

	# Option 3
	S = pairwise_distances(emb1, emb2, metric="euclidean")
	S = torch.tensor(S)
	S = -S # convert distances matrix to similarity matrix
	
	# Option 4
	""" S = torch.cdist(emb1_, emb2_, 2)
	S = -S # convert distances matrix to similarity matrix """

	hits = hits_ks_scores(S, df_node_alignment_truth_, mode="mean")
	mrr = mrr_score(S, df_node_alignment_truth_, mode="mean")
	print(encoder, hits, mrr)
	
	list_metrics.append(list(hits.values()) + [mrr])

ORI {1: 0.6000790596008301, 10: 0.8759683966636658, 30: 0.9270355701446533, 50: 0.941660076379776} 0.6933231353759766
GIN {1: 0.5839525461196899, 10: 0.85138338804245, 30: 0.9015019834041595, 50: 0.9212648272514343} 0.6739005446434021
GINE {1: 0.5815019905567169, 10: 0.8655335903167725, 30: 0.9129644334316254, 50: 0.9325691759586334} 0.6773796677589417

In [26]:
list_summary = []
for k in range(len(list_metrics)):
    list_summary.append([raw_data_file] + [encoders[k]] + list_metrics[k] + [list_runtime[k]])
list_summary

[['ACM-DBLP',
  'ORI',
  0.6000790596008301,
  0.8759683966636658,
  0.9270355701446533,
  0.941660076379776,
  0.6933231353759766,
  165.4498062870116],
 ['ACM-DBLP',
  'GIN',
  0.5839525461196899,
  0.85138338804245,
  0.9015019834041595,
  0.9212648272514343,
  0.6739005446434021,
  177.40144186501857],
 ['ACM-DBLP',
  'GINE',
  0.5815019905567169,
  0.8655335903167725,
  0.9129644334316254,
  0.9325691759586334,
  0.6773796677589417,
  494.9403406890342]]

In [27]:
columns = ["Dataset", "Encoder"] + [f"Hits@{k}" for k in list(hits.keys())] +  ["MRR", "Runtime"]
df_summary = pd.DataFrame(list_summary, columns=columns)
df_summary

,Dataset,Encoder,Hits@1,Hits@10,Hits@30,Hits@50,MRR,Runtime
0,ACM-DBLP,ORI,0.600079,0.875968,0.927036,0.941660,0.693323,165.449806
1,ACM-DBLP,GIN,0.583953,0.851383,0.901502,0.921265,0.673901,177.401442
2,ACM-DBLP,GINE,0.581502,0.865534,0.912964,0.932569,0.677380,494.940341

In [28]:
df_text = df_summary.map(lambda x: f"{x}".replace(".", ","))
df_text

,Dataset,Encoder,Hits@1,Hits@10,Hits@30,Hits@50,MRR,Runtime
0,ACM-DBLP,ORI,"0,6000790596008301","0,8759683966636658","0,9270355701446533","0,941660076379776","0,6933231353759766","165,4498062870116"
1,ACM-DBLP,GIN,"0,5839525461196899","0,85138338804245","0,9015019834041595","0,9212648272514343","0,6739005446434021","177,40144186501857"
2,ACM-DBLP,GINE,"0,5815019905567169","0,8655335903167725","0,9129644334316254","0,9325691759586334","0,6773796677589417","494,9403406890342"

In [29]:
print(NUM_HIDDEN_LAYERS)
print(HIDDEN_DIM)
print(output_feature_size)

12
[1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024]
1024